################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../include/ffmpeg/libavformat/4xm.c \
../include/ffmpeg/libavformat/a64.c \
../include/ffmpeg/libavformat/aacdec.c \
../include/ffmpeg/libavformat/ac3dec.c \
../include/ffmpeg/libavformat/act.c \
../include/ffmpeg/libavformat/adp.c \
../include/ffmpeg/libavformat/adtsenc.c \
../include/ffmpeg/libavformat/adxdec.c \
../include/ffmpeg/libavformat/aea.c \
../include/ffmpeg/libavformat/afc.c \
../include/ffmpeg/libavformat/aiffdec.c \
../include/ffmpeg/libavformat/aiffenc.c \
../include/ffmpeg/libavformat/allformats.c \
../include/ffmpeg/libavformat/amr.c \
../include/ffmpeg/libavformat/anm.c \
../include/ffmpeg/libavformat/apc.c \
../include/ffmpeg/libavformat/ape.c \
../include/ffmpeg/libavformat/apetag.c \
../include/ffmpeg/libavformat/aqtitledec.c \
../include/ffmpeg/libavformat/asf.c \
../include/ffmpeg/libavformat/asfcrypt.c \
../include/ffmpeg/libavformat/asfdec.c \
../include/ffmpeg/libavformat/asfenc.c \
../include/ffmpeg/libavformat/assdec.c \
../include/ffmpeg/libavformat/assenc.c \
../include/ffmpeg/libavformat/ast.c \
../include/ffmpeg/libavformat/astdec.c \
../include/ffmpeg/libavformat/astenc.c \
../include/ffmpeg/libavformat/au.c \
../include/ffmpeg/libavformat/audiointerleave.c \
../include/ffmpeg/libavformat/avc.c \
../include/ffmpeg/libavformat/avidec.c \
../include/ffmpeg/libavformat/avienc.c \
../include/ffmpeg/libavformat/avio.c \
../include/ffmpeg/libavformat/aviobuf.c \
../include/ffmpeg/libavformat/avisynth.c \
../include/ffmpeg/libavformat/avlanguage.c \
../include/ffmpeg/libavformat/avr.c \
../include/ffmpeg/libavformat/avs.c \
../include/ffmpeg/libavformat/bethsoftvid.c \
../include/ffmpeg/libavformat/bfi.c \
../include/ffmpeg/libavformat/bink.c \
../include/ffmpeg/libavformat/bintext.c \
../include/ffmpeg/libavformat/bit.c \
../include/ffmpeg/libavformat/bluray.c \
../include/ffmpeg/libavformat/bmv.c \
../include/ffmpeg/libavformat/boadec.c \
../include/ffmpeg/libavformat/brstm.c \
../include/ffmpeg/libavformat/c93.c \
../include/ffmpeg/libavformat/cache.c \
../include/ffmpeg/libavformat/caf.c \
../include/ffmpeg/libavformat/cafdec.c \
../include/ffmpeg/libavformat/cafenc.c \
../include/ffmpeg/libavformat/cavsvideodec.c \
../include/ffmpeg/libavformat/cdg.c \
../include/ffmpeg/libavformat/cdxl.c \
../include/ffmpeg/libavformat/cinedec.c \
../include/ffmpeg/libavformat/concat.c \
../include/ffmpeg/libavformat/concatdec.c \
../include/ffmpeg/libavformat/crcenc.c \
../include/ffmpeg/libavformat/crypto.c \
../include/ffmpeg/libavformat/cutils.c \
../include/ffmpeg/libavformat/data_uri.c \
../include/ffmpeg/libavformat/dauddec.c \
../include/ffmpeg/libavformat/daudenc.c \
../include/ffmpeg/libavformat/dfa.c \
../include/ffmpeg/libavformat/diracdec.c \
../include/ffmpeg/libavformat/dnxhddec.c \
../include/ffmpeg/libavformat/dsfdec.c \
../include/ffmpeg/libavformat/dsicin.c \
../include/ffmpeg/libavformat/dtsdec.c \
../include/ffmpeg/libavformat/dtshddec.c \
../include/ffmpeg/libavformat/dump.c \
../include/ffmpeg/libavformat/dv.c \
../include/ffmpeg/libavformat/dvenc.c \
../include/ffmpeg/libavformat/dxa.c \
../include/ffmpeg/libavformat/eacdata.c \
../include/ffmpeg/libavformat/electronicarts.c \
../include/ffmpeg/libavformat/epafdec.c \
../include/ffmpeg/libavformat/ffmdec.c \
../include/ffmpeg/libavformat/ffmenc.c \
../include/ffmpeg/libavformat/ffmetadec.c \
../include/ffmpeg/libavformat/ffmetaenc.c \
../include/ffmpeg/libavformat/file.c \
../include/ffmpeg/libavformat/file_open.c \
../include/ffmpeg/libavformat/filmstripdec.c \
../include/ffmpeg/libavformat/filmstripenc.c \
../include/ffmpeg/libavformat/flac_picture.c \
../include/ffmpeg/libavformat/flacdec.c \
../include/ffmpeg/libavformat/flacenc.c \
../include/ffmpeg/libavformat/flacenc_header.c \
../include/ffmpeg/libavformat/flic.c \
../include/ffmpeg/libavformat/flvdec.c \
../include/ffmpeg/libavformat/flvenc.c \
../include/ffmpeg/libavformat/format.c \
../include/ffmpeg/libavformat/framecrcenc.c \
../include/ffmpeg/libavformat/framehash.c \
../include/ffmpeg/libavformat/frmdec.c \
../include/ffmpeg/libavformat/ftp.c \
../include/ffmpeg/libavformat/g722.c \
../include/ffmpeg/libavformat/g723_1.c \
../include/ffmpeg/libavformat/g729dec.c \
../include/ffmpeg/libavformat/gif.c \
../include/ffmpeg/libavformat/gifdec.c \
../include/ffmpeg/libavformat/golomb_tab.c \
../include/ffmpeg/libavformat/gopher.c \
../include/ffmpeg/libavformat/gsmdec.c \
../include/ffmpeg/libavformat/gxf.c \
../include/ffmpeg/libavformat/gxfenc.c \
../include/ffmpeg/libavformat/h261dec.c \
../include/ffmpeg/libavformat/h263dec.c \
../include/ffmpeg/libavformat/h264dec.c \
../include/ffmpeg/libavformat/hdsenc.c \
../include/ffmpeg/libavformat/hevc.c \
../include/ffmpeg/libavformat/hevcdec.c \
../include/ffmpeg/libavformat/hls.c \
../include/ffmpeg/libavformat/hlsenc.c \
../include/ffmpeg/libavformat/hlsproto.c \
../include/ffmpeg/libavformat/hnm.c \
../include/ffmpeg/libavformat/http.c \
../include/ffmpeg/libavformat/httpauth.c \
../include/ffmpeg/libavformat/icodec.c \
../include/ffmpeg/libavformat/icoenc.c \
../include/ffmpeg/libavformat/id3v1.c \
../include/ffmpeg/libavformat/id3v2.c \
../include/ffmpeg/libavformat/id3v2enc.c \
../include/ffmpeg/libavformat/idcin.c \
../include/ffmpeg/libavformat/idroqdec.c \
../include/ffmpeg/libavformat/idroqenc.c \
../include/ffmpeg/libavformat/iff.c \
../include/ffmpeg/libavformat/ilbc.c \
../include/ffmpeg/libavformat/img2.c \
../include/ffmpeg/libavformat/img2_alias_pix.c \
../include/ffmpeg/libavformat/img2_brender_pix.c \
../include/ffmpeg/libavformat/img2dec.c \
../include/ffmpeg/libavformat/img2enc.c \
../include/ffmpeg/libavformat/ingenientdec.c \
../include/ffmpeg/libavformat/ipmovie.c \
../include/ffmpeg/libavformat/ircam.c \
../include/ffmpeg/libavformat/ircamdec.c \
../include/ffmpeg/libavformat/ircamenc.c \
../include/ffmpeg/libavformat/isom.c \
../include/ffmpeg/libavformat/iss.c \
../include/ffmpeg/libavformat/iv8.c \
../include/ffmpeg/libavformat/ivfdec.c \
../include/ffmpeg/libavformat/ivfenc.c \
../include/ffmpeg/libavformat/jacosubdec.c \
../include/ffmpeg/libavformat/jacosubenc.c \
../include/ffmpeg/libavformat/jvdec.c \
../include/ffmpeg/libavformat/latmenc.c \
../include/ffmpeg/libavformat/libgme.c \
../include/ffmpeg/libavformat/libmodplug.c \
../include/ffmpeg/libavformat/libnut.c \
../include/ffmpeg/libavformat/libquvi.c \
../include/ffmpeg/libavformat/librtmp.c \
../include/ffmpeg/libavformat/libssh.c \
../include/ffmpeg/libavformat/lmlm4.c \
../include/ffmpeg/libavformat/loasdec.c \
../include/ffmpeg/libavformat/log2_tab.c \
../include/ffmpeg/libavformat/lvfdec.c \
../include/ffmpeg/libavformat/lxfdec.c \
../include/ffmpeg/libavformat/m4vdec.c \
../include/ffmpeg/libavformat/matroska.c \
../include/ffmpeg/libavformat/matroskadec.c \
../include/ffmpeg/libavformat/matroskaenc.c \
../include/ffmpeg/libavformat/md5enc.c \
../include/ffmpeg/libavformat/md5proto.c \
../include/ffmpeg/libavformat/metadata.c \
../include/ffmpeg/libavformat/mgsts.c \
../include/ffmpeg/libavformat/microdvddec.c \
../include/ffmpeg/libavformat/microdvdenc.c \
../include/ffmpeg/libavformat/mkvtimestamp_v2.c \
../include/ffmpeg/libavformat/mlvdec.c \
../include/ffmpeg/libavformat/mm.c \
../include/ffmpeg/libavformat/mmf.c \
../include/ffmpeg/libavformat/mms.c \
../include/ffmpeg/libavformat/mmsh.c \
../include/ffmpeg/libavformat/mmst.c \
../include/ffmpeg/libavformat/mov.c \
../include/ffmpeg/libavformat/mov_chan.c \
../include/ffmpeg/libavformat/movenc.c \
../include/ffmpeg/libavformat/movenchint.c \
../include/ffmpeg/libavformat/mp3dec.c \
../include/ffmpeg/libavformat/mp3enc.c \
../include/ffmpeg/libavformat/mpc.c \
../include/ffmpeg/libavformat/mpc8.c \
../include/ffmpeg/libavformat/mpeg.c \
../include/ffmpeg/libavformat/mpegenc.c \
../include/ffmpeg/libavformat/mpegts.c \
../include/ffmpeg/libavformat/mpegtsenc.c \
../include/ffmpeg/libavformat/mpegvideodec.c \
../include/ffmpeg/libavformat/mpjpeg.c \
../include/ffmpeg/libavformat/mpl2dec.c \
../include/ffmpeg/libavformat/mpsubdec.c \
../include/ffmpeg/libavformat/msnwc_tcp.c \
../include/ffmpeg/libavformat/mtv.c \
../include/ffmpeg/libavformat/mux.c \
../include/ffmpeg/libavformat/mvdec.c \
../include/ffmpeg/libavformat/mvi.c \
../include/ffmpeg/libavformat/mxf.c \
../include/ffmpeg/libavformat/mxfdec.c \
../include/ffmpeg/libavformat/mxfenc.c \
../include/ffmpeg/libavformat/mxg.c \
../include/ffmpeg/libavformat/ncdec.c \
../include/ffmpeg/libavformat/network.c \
../include/ffmpeg/libavformat/nistspheredec.c \
../include/ffmpeg/libavformat/noproxy-test.c \
../include/ffmpeg/libavformat/nsvdec.c \
../include/ffmpeg/libavformat/nullenc.c \
../include/ffmpeg/libavformat/nut.c \
../include/ffmpeg/libavformat/nutdec.c \
../include/ffmpeg/libavformat/nutenc.c \
../include/ffmpeg/libavformat/nuv.c \
../include/ffmpeg/libavformat/oggdec.c \
../include/ffmpeg/libavformat/oggenc.c \
../include/ffmpeg/libavformat/oggparsecelt.c \
../include/ffmpeg/libavformat/oggparsedirac.c \
../include/ffmpeg/libavformat/oggparseflac.c \
../include/ffmpeg/libavformat/oggparseogm.c \
../include/ffmpeg/libavformat/oggparseopus.c \
../include/ffmpeg/libavformat/oggparseskeleton.c \
../include/ffmpeg/libavformat/oggparsespeex.c \
../include/ffmpeg/libavformat/oggparsetheora.c \
../include/ffmpeg/libavformat/oggparsevorbis.c \
../include/ffmpeg/libavformat/oggparsevp8.c \
../include/ffmpeg/libavformat/oma.c \
../include/ffmpeg/libavformat/omadec.c \
../include/ffmpeg/libavformat/omaenc.c \
../include/ffmpeg/libavformat/options.c \
../include/ffmpeg/libavformat/os_support.c \
../include/ffmpeg/libavformat/paf.c \
../include/ffmpeg/libavformat/pcm.c \
../include/ffmpeg/libavformat/pcmdec.c \
../include/ffmpeg/libavformat/pcmenc.c \
../include/ffmpeg/libavformat/pjsdec.c \
../include/ffmpeg/libavformat/pmpdec.c \
../include/ffmpeg/libavformat/psxstr.c \
../include/ffmpeg/libavformat/pva.c \
../include/ffmpeg/libavformat/pvfdec.c \
../include/ffmpeg/libavformat/qcp.c \
../include/ffmpeg/libavformat/r3d.c \
../include/ffmpeg/libavformat/rawdec.c \
../include/ffmpeg/libavformat/rawenc.c \
../include/ffmpeg/libavformat/rawvideodec.c \
../include/ffmpeg/libavformat/rdt.c \
../include/ffmpeg/libavformat/realtextdec.c \
../include/ffmpeg/libavformat/redspark.c \
../include/ffmpeg/libavformat/replaygain.c \
../include/ffmpeg/libavformat/riff.c \
../include/ffmpeg/libavformat/riffdec.c \
../include/ffmpeg/libavformat/riffenc.c \
../include/ffmpeg/libavformat/rl2.c \
../include/ffmpeg/libavformat/rm.c \
../include/ffmpeg/libavformat/rmdec.c \
../include/ffmpeg/libavformat/rmenc.c \
../include/ffmpeg/libavformat/rmsipr.c \
../include/ffmpeg/libavformat/rpl.c \
../include/ffmpeg/libavformat/rsd.c \
../include/ffmpeg/libavformat/rso.c \
../include/ffmpeg/libavformat/rsodec.c \
../include/ffmpeg/libavformat/rsoenc.c \
../include/ffmpeg/libavformat/rtmpcrypt.c \
../include/ffmpeg/libavformat/rtmpdh.c \
../include/ffmpeg/libavformat/rtmphttp.c \
../include/ffmpeg/libavformat/rtmppkt.c \
../include/ffmpeg/libavformat/rtmpproto.c \
../include/ffmpeg/libavformat/rtp.c \
../include/ffmpeg/libavformat/rtpdec.c \
../include/ffmpeg/libavformat/rtpdec_amr.c \
../include/ffmpeg/libavformat/rtpdec_asf.c \
../include/ffmpeg/libavformat/rtpdec_g726.c \
../include/ffmpeg/libavformat/rtpdec_h263.c \
../include/ffmpeg/libavformat/rtpdec_h263_rfc2190.c \
../include/ffmpeg/libavformat/rtpdec_h264.c \
../include/ffmpeg/libavformat/rtpdec_ilbc.c \
../include/ffmpeg/libavformat/rtpdec_jpeg.c \
../include/ffmpeg/libavformat/rtpdec_latm.c \
../include/ffmpeg/libavformat/rtpdec_mpeg12.c \
../include/ffmpeg/libavformat/rtpdec_mpeg4.c \
../include/ffmpeg/libavformat/rtpdec_mpegts.c \
../include/ffmpeg/libavformat/rtpdec_qcelp.c \
../include/ffmpeg/libavformat/rtpdec_qdm2.c \
../include/ffmpeg/libavformat/rtpdec_qt.c \
../include/ffmpeg/libavformat/rtpdec_svq3.c \
../include/ffmpeg/libavformat/rtpdec_vp8.c \
../include/ffmpeg/libavformat/rtpdec_xiph.c \
../include/ffmpeg/libavformat/rtpenc.c \
../include/ffmpeg/libavformat/rtpenc_aac.c \
../include/ffmpeg/libavformat/rtpenc_amr.c \
../include/ffmpeg/libavformat/rtpenc_chain.c \
../include/ffmpeg/libavformat/rtpenc_h263.c \
../include/ffmpeg/libavformat/rtpenc_h263_rfc2190.c \
../include/ffmpeg/libavformat/rtpenc_h264.c \
../include/ffmpeg/libavformat/rtpenc_jpeg.c \
../include/ffmpeg/libavformat/rtpenc_latm.c \
../include/ffmpeg/libavformat/rtpenc_mpv.c \
../include/ffmpeg/libavformat/rtpenc_vp8.c \
../include/ffmpeg/libavformat/rtpenc_xiph.c \
../include/ffmpeg/libavformat/rtpproto.c \
../include/ffmpeg/libavformat/rtsp.c \
../include/ffmpeg/libavformat/rtspdec.c \
../include/ffmpeg/libavformat/rtspenc.c \
../include/ffmpeg/libavformat/samidec.c \
../include/ffmpeg/libavformat/sapdec.c \
../include/ffmpeg/libavformat/sapenc.c \
../include/ffmpeg/libavformat/sauce.c \
../include/ffmpeg/libavformat/sbgdec.c \
../include/ffmpeg/libavformat/sctp.c \
../include/ffmpeg/libavformat/sdp.c \
../include/ffmpeg/libavformat/sdr2.c \
../include/ffmpeg/libavformat/seek-test.c \
../include/ffmpeg/libavformat/seek.c \
../include/ffmpeg/libavformat/segafilm.c \
../include/ffmpeg/libavformat/segment.c \
../include/ffmpeg/libavformat/sierravmd.c \
../include/ffmpeg/libavformat/siff.c \
../include/ffmpeg/libavformat/smacker.c \
../include/ffmpeg/libavformat/smjpeg.c \
../include/ffmpeg/libavformat/smjpegdec.c \
../include/ffmpeg/libavformat/smjpegenc.c \
../include/ffmpeg/libavformat/smoothstreamingenc.c \
../include/ffmpeg/libavformat/smush.c \
../include/ffmpeg/libavformat/sol.c \
../include/ffmpeg/libavformat/soxdec.c \
../include/ffmpeg/libavformat/soxenc.c \
../include/ffmpeg/libavformat/spdif.c \
../include/ffmpeg/libavformat/spdifdec.c \
../include/ffmpeg/libavformat/spdifenc.c \
../include/ffmpeg/libavformat/srtdec.c \
../include/ffmpeg/libavformat/srtenc.c \
../include/ffmpeg/libavformat/srtp.c \
../include/ffmpeg/libavformat/srtpproto.c \
../include/ffmpeg/libavformat/subfile.c \
../include/ffmpeg/libavformat/subtitles.c \
../include/ffmpeg/libavformat/subviewer1dec.c \
../include/ffmpeg/libavformat/subviewerdec.c \
../include/ffmpeg/libavformat/swf.c \
../include/ffmpeg/libavformat/swfdec.c \
../include/ffmpeg/libavformat/swfenc.c \
../include/ffmpeg/libavformat/takdec.c \
../include/ffmpeg/libavformat/tcp.c \
../include/ffmpeg/libavformat/tedcaptionsdec.c \
../include/ffmpeg/libavformat/tee.c \
../include/ffmpeg/libavformat/thp.c \
../include/ffmpeg/libavformat/tiertexseq.c \
../include/ffmpeg/libavformat/tls.c \
../include/ffmpeg/libavformat/tmv.c \
../include/ffmpeg/libavformat/tta.c \
../include/ffmpeg/libavformat/tty.c \
../include/ffmpeg/libavformat/txd.c \
../include/ffmpeg/libavformat/udp.c \
../include/ffmpeg/libavformat/uncodedframecrcenc.c \
../include/ffmpeg/libavformat/unix.c \
../include/ffmpeg/libavformat/url-test.c \
../include/ffmpeg/libavformat/url.c \
../include/ffmpeg/libavformat/urldecode.c \
../include/ffmpeg/libavformat/utils.c \
../include/ffmpeg/libavformat/vc1test.c \
../include/ffmpeg/libavformat/vc1testenc.c \
../include/ffmpeg/libavformat/vivo.c \
../include/ffmpeg/libavformat/voc.c \
../include/ffmpeg/libavformat/vocdec.c \
../include/ffmpeg/libavformat/vocenc.c \
../include/ffmpeg/libavformat/vorbiscomment.c \
../include/ffmpeg/libavformat/vplayerdec.c \
../include/ffmpeg/libavformat/vqf.c \
../include/ffmpeg/libavformat/w64.c \
../include/ffmpeg/libavformat/wavdec.c \
../include/ffmpeg/libavformat/wavenc.c \
../include/ffmpeg/libavformat/wc3movie.c \
../include/ffmpeg/libavformat/webvttdec.c \
../include/ffmpeg/libavformat/webvttenc.c \
../include/ffmpeg/libavformat/westwood_aud.c \
../include/ffmpeg/libavformat/westwood_vqa.c \
../include/ffmpeg/libavformat/wtv_common.c \
../include/ffmpeg/libavformat/wtvdec.c \
../include/ffmpeg/libavformat/wtvenc.c \
../include/ffmpeg/libavformat/wv.c \
../include/ffmpeg/libavformat/wvdec.c \
../include/ffmpeg/libavformat/wvenc.c \
../include/ffmpeg/libavformat/xa.c \
../include/ffmpeg/libavformat/xmv.c \
../include/ffmpeg/libavformat/xwma.c \
../include/ffmpeg/libavformat/yop.c \
../include/ffmpeg/libavformat/yuv4mpegdec.c \
../include/ffmpeg/libavformat/yuv4mpegenc.c 

OBJS += \
./include/ffmpeg/libavformat/4xm.o \
./include/ffmpeg/libavformat/a64.o \
./include/ffmpeg/libavformat/aacdec.o \
./include/ffmpeg/libavformat/ac3dec.o \
./include/ffmpeg/libavformat/act.o \
./include/ffmpeg/libavformat/adp.o \
./include/ffmpeg/libavformat/adtsenc.o \
./include/ffmpeg/libavformat/adxdec.o \
./include/ffmpeg/libavformat/aea.o \
./include/ffmpeg/libavformat/afc.o \
./include/ffmpeg/libavformat/aiffdec.o \
./include/ffmpeg/libavformat/aiffenc.o \
./include/ffmpeg/libavformat/allformats.o \
./include/ffmpeg/libavformat/amr.o \
./include/ffmpeg/libavformat/anm.o \
./include/ffmpeg/libavformat/apc.o \
./include/ffmpeg/libavformat/ape.o \
./include/ffmpeg/libavformat/apetag.o \
./include/ffmpeg/libavformat/aqtitledec.o \
./include/ffmpeg/libavformat/asf.o \
./include/ffmpeg/libavformat/asfcrypt.o \
./include/ffmpeg/libavformat/asfdec.o \
./include/ffmpeg/libavformat/asfenc.o \
./include/ffmpeg/libavformat/assdec.o \
./include/ffmpeg/libavformat/assenc.o \
./include/ffmpeg/libavformat/ast.o \
./include/ffmpeg/libavformat/astdec.o \
./include/ffmpeg/libavformat/astenc.o \
./include/ffmpeg/libavformat/au.o \
./include/ffmpeg/libavformat/audiointerleave.o \
./include/ffmpeg/libavformat/avc.o \
./include/ffmpeg/libavformat/avidec.o \
./include/ffmpeg/libavformat/avienc.o \
./include/ffmpeg/libavformat/avio.o \
./include/ffmpeg/libavformat/aviobuf.o \
./include/ffmpeg/libavformat/avisynth.o \
./include/ffmpeg/libavformat/avlanguage.o \
./include/ffmpeg/libavformat/avr.o \
./include/ffmpeg/libavformat/avs.o \
./include/ffmpeg/libavformat/bethsoftvid.o \
./include/ffmpeg/libavformat/bfi.o \
./include/ffmpeg/libavformat/bink.o \
./include/ffmpeg/libavformat/bintext.o \
./include/ffmpeg/libavformat/bit.o \
./include/ffmpeg/libavformat/bluray.o \
./include/ffmpeg/libavformat/bmv.o \
./include/ffmpeg/libavformat/boadec.o \
./include/ffmpeg/libavformat/brstm.o \
./include/ffmpeg/libavformat/c93.o \
./include/ffmpeg/libavformat/cache.o \
./include/ffmpeg/libavformat/caf.o \
./include/ffmpeg/libavformat/cafdec.o \
./include/ffmpeg/libavformat/cafenc.o \
./include/ffmpeg/libavformat/cavsvideodec.o \
./include/ffmpeg/libavformat/cdg.o \
./include/ffmpeg/libavformat/cdxl.o \
./include/ffmpeg/libavformat/cinedec.o \
./include/ffmpeg/libavformat/concat.o \
./include/ffmpeg/libavformat/concatdec.o \
./include/ffmpeg/libavformat/crcenc.o \
./include/ffmpeg/libavformat/crypto.o \
./include/ffmpeg/libavformat/cutils.o \
./include/ffmpeg/libavformat/data_uri.o \
./include/ffmpeg/libavformat/dauddec.o \
./include/ffmpeg/libavformat/daudenc.o \
./include/ffmpeg/libavformat/dfa.o \
./include/ffmpeg/libavformat/diracdec.o \
./include/ffmpeg/libavformat/dnxhddec.o \
./include/ffmpeg/libavformat/dsfdec.o \
./include/ffmpeg/libavformat/dsicin.o \
./include/ffmpeg/libavformat/dtsdec.o \
./include/ffmpeg/libavformat/dtshddec.o \
./include/ffmpeg/libavformat/dump.o \
./include/ffmpeg/libavformat/dv.o \
./include/ffmpeg/libavformat/dvenc.o \
./include/ffmpeg/libavformat/dxa.o \
./include/ffmpeg/libavformat/eacdata.o \
./include/ffmpeg/libavformat/electronicarts.o \
./include/ffmpeg/libavformat/epafdec.o \
./include/ffmpeg/libavformat/ffmdec.o \
./include/ffmpeg/libavformat/ffmenc.o \
./include/ffmpeg/libavformat/ffmetadec.o \
./include/ffmpeg/libavformat/ffmetaenc.o \
./include/ffmpeg/libavformat/file.o \
./include/ffmpeg/libavformat/file_open.o \
./include/ffmpeg/libavformat/filmstripdec.o \
./include/ffmpeg/libavformat/filmstripenc.o \
./include/ffmpeg/libavformat/flac_picture.o \
./include/ffmpeg/libavformat/flacdec.o \
./include/ffmpeg/libavformat/flacenc.o \
./include/ffmpeg/libavformat/flacenc_header.o \
./include/ffmpeg/libavformat/flic.o \
./include/ffmpeg/libavformat/flvdec.o \
./include/ffmpeg/libavformat/flvenc.o \
./include/ffmpeg/libavformat/format.o \
./include/ffmpeg/libavformat/framecrcenc.o \
./include/ffmpeg/libavformat/framehash.o \
./include/ffmpeg/libavformat/frmdec.o \
./include/ffmpeg/libavformat/ftp.o \
./include/ffmpeg/libavformat/g722.o \
./include/ffmpeg/libavformat/g723_1.o \
./include/ffmpeg/libavformat/g729dec.o \
./include/ffmpeg/libavformat/gif.o \
./include/ffmpeg/libavformat/gifdec.o \
./include/ffmpeg/libavformat/golomb_tab.o \
./include/ffmpeg/libavformat/gopher.o \
./include/ffmpeg/libavformat/gsmdec.o \
./include/ffmpeg/libavformat/gxf.o \
./include/ffmpeg/libavformat/gxfenc.o \
./include/ffmpeg/libavformat/h261dec.o \
./include/ffmpeg/libavformat/h263dec.o \
./include/ffmpeg/libavformat/h264dec.o \
./include/ffmpeg/libavformat/hdsenc.o \
./include/ffmpeg/libavformat/hevc.o \
./include/ffmpeg/libavformat/hevcdec.o \
./include/ffmpeg/libavformat/hls.o \
./include/ffmpeg/libavformat/hlsenc.o \
./include/ffmpeg/libavformat/hlsproto.o \
./include/ffmpeg/libavformat/hnm.o \
./include/ffmpeg/libavformat/http.o \
./include/ffmpeg/libavformat/httpauth.o \
./include/ffmpeg/libavformat/icodec.o \
./include/ffmpeg/libavformat/icoenc.o \
./include/ffmpeg/libavformat/id3v1.o \
./include/ffmpeg/libavformat/id3v2.o \
./include/ffmpeg/libavformat/id3v2enc.o \
./include/ffmpeg/libavformat/idcin.o \
./include/ffmpeg/libavformat/idroqdec.o \
./include/ffmpeg/libavformat/idroqenc.o \
./include/ffmpeg/libavformat/iff.o \
./include/ffmpeg/libavformat/ilbc.o \
./include/ffmpeg/libavformat/img2.o \
./include/ffmpeg/libavformat/img2_alias_pix.o \
./include/ffmpeg/libavformat/img2_brender_pix.o \
./include/ffmpeg/libavformat/img2dec.o \
./include/ffmpeg/libavformat/img2enc.o \
./include/ffmpeg/libavformat/ingenientdec.o \
./include/ffmpeg/libavformat/ipmovie.o \
./include/ffmpeg/libavformat/ircam.o \
./include/ffmpeg/libavformat/ircamdec.o \
./include/ffmpeg/libavformat/ircamenc.o \
./include/ffmpeg/libavformat/isom.o \
./include/ffmpeg/libavformat/iss.o \
./include/ffmpeg/libavformat/iv8.o \
./include/ffmpeg/libavformat/ivfdec.o \
./include/ffmpeg/libavformat/ivfenc.o \
./include/ffmpeg/libavformat/jacosubdec.o \
./include/ffmpeg/libavformat/jacosubenc.o \
./include/ffmpeg/libavformat/jvdec.o \
./include/ffmpeg/libavformat/latmenc.o \
./include/ffmpeg/libavformat/libgme.o \
./include/ffmpeg/libavformat/libmodplug.o \
./include/ffmpeg/libavformat/libnut.o \
./include/ffmpeg/libavformat/libquvi.o \
./include/ffmpeg/libavformat/librtmp.o \
./include/ffmpeg/libavformat/libssh.o \
./include/ffmpeg/libavformat/lmlm4.o \
./include/ffmpeg/libavformat/loasdec.o \
./include/ffmpeg/libavformat/log2_tab.o \
./include/ffmpeg/libavformat/lvfdec.o \
./include/ffmpeg/libavformat/lxfdec.o \
./include/ffmpeg/libavformat/m4vdec.o \
./include/ffmpeg/libavformat/matroska.o \
./include/ffmpeg/libavformat/matroskadec.o \
./include/ffmpeg/libavformat/matroskaenc.o \
./include/ffmpeg/libavformat/md5enc.o \
./include/ffmpeg/libavformat/md5proto.o \
./include/ffmpeg/libavformat/metadata.o \
./include/ffmpeg/libavformat/mgsts.o \
./include/ffmpeg/libavformat/microdvddec.o \
./include/ffmpeg/libavformat/microdvdenc.o \
./include/ffmpeg/libavformat/mkvtimestamp_v2.o \
./include/ffmpeg/libavformat/mlvdec.o \
./include/ffmpeg/libavformat/mm.o \
./include/ffmpeg/libavformat/mmf.o \
./include/ffmpeg/libavformat/mms.o \
./include/ffmpeg/libavformat/mmsh.o \
./include/ffmpeg/libavformat/mmst.o \
./include/ffmpeg/libavformat/mov.o \
./include/ffmpeg/libavformat/mov_chan.o \
./include/ffmpeg/libavformat/movenc.o \
./include/ffmpeg/libavformat/movenchint.o \
./include/ffmpeg/libavformat/mp3dec.o \
./include/ffmpeg/libavformat/mp3enc.o \
./include/ffmpeg/libavformat/mpc.o \
./include/ffmpeg/libavformat/mpc8.o \
./include/ffmpeg/libavformat/mpeg.o \
./include/ffmpeg/libavformat/mpegenc.o \
./include/ffmpeg/libavformat/mpegts.o \
./include/ffmpeg/libavformat/mpegtsenc.o \
./include/ffmpeg/libavformat/mpegvideodec.o \
./include/ffmpeg/libavformat/mpjpeg.o \
./include/ffmpeg/libavformat/mpl2dec.o \
./include/ffmpeg/libavformat/mpsubdec.o \
./include/ffmpeg/libavformat/msnwc_tcp.o \
./include/ffmpeg/libavformat/mtv.o \
./include/ffmpeg/libavformat/mux.o \
./include/ffmpeg/libavformat/mvdec.o \
./include/ffmpeg/libavformat/mvi.o \
./include/ffmpeg/libavformat/mxf.o \
./include/ffmpeg/libavformat/mxfdec.o \
./include/ffmpeg/libavformat/mxfenc.o \
./include/ffmpeg/libavformat/mxg.o \
./include/ffmpeg/libavformat/ncdec.o \
./include/ffmpeg/libavformat/network.o \
./include/ffmpeg/libavformat/nistspheredec.o \
./include/ffmpeg/libavformat/noproxy-test.o \
./include/ffmpeg/libavformat/nsvdec.o \
./include/ffmpeg/libavformat/nullenc.o \
./include/ffmpeg/libavformat/nut.o \
./include/ffmpeg/libavformat/nutdec.o \
./include/ffmpeg/libavformat/nutenc.o \
./include/ffmpeg/libavformat/nuv.o \
./include/ffmpeg/libavformat/oggdec.o \
./include/ffmpeg/libavformat/oggenc.o \
./include/ffmpeg/libavformat/oggparsecelt.o \
./include/ffmpeg/libavformat/oggparsedirac.o \
./include/ffmpeg/libavformat/oggparseflac.o \
./include/ffmpeg/libavformat/oggparseogm.o \
./include/ffmpeg/libavformat/oggparseopus.o \
./include/ffmpeg/libavformat/oggparseskeleton.o \
./include/ffmpeg/libavformat/oggparsespeex.o \
./include/ffmpeg/libavformat/oggparsetheora.o \
./include/ffmpeg/libavformat/oggparsevorbis.o \
./include/ffmpeg/libavformat/oggparsevp8.o \
./include/ffmpeg/libavformat/oma.o \
./include/ffmpeg/libavformat/omadec.o \
./include/ffmpeg/libavformat/omaenc.o \
./include/ffmpeg/libavformat/options.o \
./include/ffmpeg/libavformat/os_support.o \
./include/ffmpeg/libavformat/paf.o \
./include/ffmpeg/libavformat/pcm.o \
./include/ffmpeg/libavformat/pcmdec.o \
./include/ffmpeg/libavformat/pcmenc.o \
./include/ffmpeg/libavformat/pjsdec.o \
./include/ffmpeg/libavformat/pmpdec.o \
./include/ffmpeg/libavformat/psxstr.o \
./include/ffmpeg/libavformat/pva.o \
./include/ffmpeg/libavformat/pvfdec.o \
./include/ffmpeg/libavformat/qcp.o \
./include/ffmpeg/libavformat/r3d.o \
./include/ffmpeg/libavformat/rawdec.o \
./include/ffmpeg/libavformat/rawenc.o \
./include/ffmpeg/libavformat/rawvideodec.o \
./include/ffmpeg/libavformat/rdt.o \
./include/ffmpeg/libavformat/realtextdec.o \
./include/ffmpeg/libavformat/redspark.o \
./include/ffmpeg/libavformat/replaygain.o \
./include/ffmpeg/libavformat/riff.o \
./include/ffmpeg/libavformat/riffdec.o \
./include/ffmpeg/libavformat/riffenc.o \
./include/ffmpeg/libavformat/rl2.o \
./include/ffmpeg/libavformat/rm.o \
./include/ffmpeg/libavformat/rmdec.o \
./include/ffmpeg/libavformat/rmenc.o \
./include/ffmpeg/libavformat/rmsipr.o \
./include/ffmpeg/libavformat/rpl.o \
./include/ffmpeg/libavformat/rsd.o \
./include/ffmpeg/libavformat/rso.o \
./include/ffmpeg/libavformat/rsodec.o \
./include/ffmpeg/libavformat/rsoenc.o \
./include/ffmpeg/libavformat/rtmpcrypt.o \
./include/ffmpeg/libavformat/rtmpdh.o \
./include/ffmpeg/libavformat/rtmphttp.o \
./include/ffmpeg/libavformat/rtmppkt.o \
./include/ffmpeg/libavformat/rtmpproto.o \
./include/ffmpeg/libavformat/rtp.o \
./include/ffmpeg/libavformat/rtpdec.o \
./include/ffmpeg/libavformat/rtpdec_amr.o \
./include/ffmpeg/libavformat/rtpdec_asf.o \
./include/ffmpeg/libavformat/rtpdec_g726.o \
./include/ffmpeg/libavformat/rtpdec_h263.o \
./include/ffmpeg/libavformat/rtpdec_h263_rfc2190.o \
./include/ffmpeg/libavformat/rtpdec_h264.o \
./include/ffmpeg/libavformat/rtpdec_ilbc.o \
./include/ffmpeg/libavformat/rtpdec_jpeg.o \
./include/ffmpeg/libavformat/rtpdec_latm.o \
./include/ffmpeg/libavformat/rtpdec_mpeg12.o \
./include/ffmpeg/libavformat/rtpdec_mpeg4.o \
./include/ffmpeg/libavformat/rtpdec_mpegts.o \
./include/ffmpeg/libavformat/rtpdec_qcelp.o \
./include/ffmpeg/libavformat/rtpdec_qdm2.o \
./include/ffmpeg/libavformat/rtpdec_qt.o \
./include/ffmpeg/libavformat/rtpdec_svq3.o \
./include/ffmpeg/libavformat/rtpdec_vp8.o \
./include/ffmpeg/libavformat/rtpdec_xiph.o \
./include/ffmpeg/libavformat/rtpenc.o \
./include/ffmpeg/libavformat/rtpenc_aac.o \
./include/ffmpeg/libavformat/rtpenc_amr.o \
./include/ffmpeg/libavformat/rtpenc_chain.o \
./include/ffmpeg/libavformat/rtpenc_h263.o \
./include/ffmpeg/libavformat/rtpenc_h263_rfc2190.o \
./include/ffmpeg/libavformat/rtpenc_h264.o \
./include/ffmpeg/libavformat/rtpenc_jpeg.o \
./include/ffmpeg/libavformat/rtpenc_latm.o \
./include/ffmpeg/libavformat/rtpenc_mpv.o \
./include/ffmpeg/libavformat/rtpenc_vp8.o \
./include/ffmpeg/libavformat/rtpenc_xiph.o \
./include/ffmpeg/libavformat/rtpproto.o \
./include/ffmpeg/libavformat/rtsp.o \
./include/ffmpeg/libavformat/rtspdec.o \
./include/ffmpeg/libavformat/rtspenc.o \
./include/ffmpeg/libavformat/samidec.o \
./include/ffmpeg/libavformat/sapdec.o \
./include/ffmpeg/libavformat/sapenc.o \
./include/ffmpeg/libavformat/sauce.o \
./include/ffmpeg/libavformat/sbgdec.o \
./include/ffmpeg/libavformat/sctp.o \
./include/ffmpeg/libavformat/sdp.o \
./include/ffmpeg/libavformat/sdr2.o \
./include/ffmpeg/libavformat/seek-test.o \
./include/ffmpeg/libavformat/seek.o \
./include/ffmpeg/libavformat/segafilm.o \
./include/ffmpeg/libavformat/segment.o \
./include/ffmpeg/libavformat/sierravmd.o \
./include/ffmpeg/libavformat/siff.o \
./include/ffmpeg/libavformat/smacker.o \
./include/ffmpeg/libavformat/smjpeg.o \
./include/ffmpeg/libavformat/smjpegdec.o \
./include/ffmpeg/libavformat/smjpegenc.o \
./include/ffmpeg/libavformat/smoothstreamingenc.o \
./include/ffmpeg/libavformat/smush.o \
./include/ffmpeg/libavformat/sol.o \
./include/ffmpeg/libavformat/soxdec.o \
./include/ffmpeg/libavformat/soxenc.o \
./include/ffmpeg/libavformat/spdif.o \
./include/ffmpeg/libavformat/spdifdec.o \
./include/ffmpeg/libavformat/spdifenc.o \
./include/ffmpeg/libavformat/srtdec.o \
./include/ffmpeg/libavformat/srtenc.o \
./include/ffmpeg/libavformat/srtp.o \
./include/ffmpeg/libavformat/srtpproto.o \
./include/ffmpeg/libavformat/subfile.o \
./include/ffmpeg/libavformat/subtitles.o \
./include/ffmpeg/libavformat/subviewer1dec.o \
./include/ffmpeg/libavformat/subviewerdec.o \
./include/ffmpeg/libavformat/swf.o \
./include/ffmpeg/libavformat/swfdec.o \
./include/ffmpeg/libavformat/swfenc.o \
./include/ffmpeg/libavformat/takdec.o \
./include/ffmpeg/libavformat/tcp.o \
./include/ffmpeg/libavformat/tedcaptionsdec.o \
./include/ffmpeg/libavformat/tee.o \
./include/ffmpeg/libavformat/thp.o \
./include/ffmpeg/libavformat/tiertexseq.o \
./include/ffmpeg/libavformat/tls.o \
./include/ffmpeg/libavformat/tmv.o \
./include/ffmpeg/libavformat/tta.o \
./include/ffmpeg/libavformat/tty.o \
./include/ffmpeg/libavformat/txd.o \
./include/ffmpeg/libavformat/udp.o \
./include/ffmpeg/libavformat/uncodedframecrcenc.o \
./include/ffmpeg/libavformat/unix.o \
./include/ffmpeg/libavformat/url-test.o \
./include/ffmpeg/libavformat/url.o \
./include/ffmpeg/libavformat/urldecode.o \
./include/ffmpeg/libavformat/utils.o \
./include/ffmpeg/libavformat/vc1test.o \
./include/ffmpeg/libavformat/vc1testenc.o \
./include/ffmpeg/libavformat/vivo.o \
./include/ffmpeg/libavformat/voc.o \
./include/ffmpeg/libavformat/vocdec.o \
./include/ffmpeg/libavformat/vocenc.o \
./include/ffmpeg/libavformat/vorbiscomment.o \
./include/ffmpeg/libavformat/vplayerdec.o \
./include/ffmpeg/libavformat/vqf.o \
./include/ffmpeg/libavformat/w64.o \
./include/ffmpeg/libavformat/wavdec.o \
./include/ffmpeg/libavformat/wavenc.o \
./include/ffmpeg/libavformat/wc3movie.o \
./include/ffmpeg/libavformat/webvttdec.o \
./include/ffmpeg/libavformat/webvttenc.o \
./include/ffmpeg/libavformat/westwood_aud.o \
./include/ffmpeg/libavformat/westwood_vqa.o \
./include/ffmpeg/libavformat/wtv_common.o \
./include/ffmpeg/libavformat/wtvdec.o \
./include/ffmpeg/libavformat/wtvenc.o \
./include/ffmpeg/libavformat/wv.o \
./include/ffmpeg/libavformat/wvdec.o \
./include/ffmpeg/libavformat/wvenc.o \
./include/ffmpeg/libavformat/xa.o \
./include/ffmpeg/libavformat/xmv.o \
./include/ffmpeg/libavformat/xwma.o \
./include/ffmpeg/libavformat/yop.o \
./include/ffmpeg/libavformat/yuv4mpegdec.o \
./include/ffmpeg/libavformat/yuv4mpegenc.o 

C_DEPS += \
./include/ffmpeg/libavformat/4xm.d \
./include/ffmpeg/libavformat/a64.d \
./include/ffmpeg/libavformat/aacdec.d \
./include/ffmpeg/libavformat/ac3dec.d \
./include/ffmpeg/libavformat/act.d \
./include/ffmpeg/libavformat/adp.d \
./include/ffmpeg/libavformat/adtsenc.d \
./include/ffmpeg/libavformat/adxdec.d \
./include/ffmpeg/libavformat/aea.d \
./include/ffmpeg/libavformat/afc.d \
./include/ffmpeg/libavformat/aiffdec.d \
./include/ffmpeg/libavformat/aiffenc.d \
./include/ffmpeg/libavformat/allformats.d \
./include/ffmpeg/libavformat/amr.d \
./include/ffmpeg/libavformat/anm.d \
./include/ffmpeg/libavformat/apc.d \
./include/ffmpeg/libavformat/ape.d \
./include/ffmpeg/libavformat/apetag.d \
./include/ffmpeg/libavformat/aqtitledec.d \
./include/ffmpeg/libavformat/asf.d \
./include/ffmpeg/libavformat/asfcrypt.d \
./include/ffmpeg/libavformat/asfdec.d \
./include/ffmpeg/libavformat/asfenc.d \
./include/ffmpeg/libavformat/assdec.d \
./include/ffmpeg/libavformat/assenc.d \
./include/ffmpeg/libavformat/ast.d \
./include/ffmpeg/libavformat/astdec.d \
./include/ffmpeg/libavformat/astenc.d \
./include/ffmpeg/libavformat/au.d \
./include/ffmpeg/libavformat/audiointerleave.d \
./include/ffmpeg/libavformat/avc.d \
./include/ffmpeg/libavformat/avidec.d \
./include/ffmpeg/libavformat/avienc.d \
./include/ffmpeg/libavformat/avio.d \
./include/ffmpeg/libavformat/aviobuf.d \
./include/ffmpeg/libavformat/avisynth.d \
./include/ffmpeg/libavformat/avlanguage.d \
./include/ffmpeg/libavformat/avr.d \
./include/ffmpeg/libavformat/avs.d \
./include/ffmpeg/libavformat/bethsoftvid.d \
./include/ffmpeg/libavformat/bfi.d \
./include/ffmpeg/libavformat/bink.d \
./include/ffmpeg/libavformat/bintext.d \
./include/ffmpeg/libavformat/bit.d \
./include/ffmpeg/libavformat/bluray.d \
./include/ffmpeg/libavformat/bmv.d \
./include/ffmpeg/libavformat/boadec.d \
./include/ffmpeg/libavformat/brstm.d \
./include/ffmpeg/libavformat/c93.d \
./include/ffmpeg/libavformat/cache.d \
./include/ffmpeg/libavformat/caf.d \
./include/ffmpeg/libavformat/cafdec.d \
./include/ffmpeg/libavformat/cafenc.d \
./include/ffmpeg/libavformat/cavsvideodec.d \
./include/ffmpeg/libavformat/cdg.d \
./include/ffmpeg/libavformat/cdxl.d \
./include/ffmpeg/libavformat/cinedec.d \
./include/ffmpeg/libavformat/concat.d \
./include/ffmpeg/libavformat/concatdec.d \
./include/ffmpeg/libavformat/crcenc.d \
./include/ffmpeg/libavformat/crypto.d \
./include/ffmpeg/libavformat/cutils.d \
./include/ffmpeg/libavformat/data_uri.d \
./include/ffmpeg/libavformat/dauddec.d \
./include/ffmpeg/libavformat/daudenc.d \
./include/ffmpeg/libavformat/dfa.d \
./include/ffmpeg/libavformat/diracdec.d \
./include/ffmpeg/libavformat/dnxhddec.d \
./include/ffmpeg/libavformat/dsfdec.d \
./include/ffmpeg/libavformat/dsicin.d \
./include/ffmpeg/libavformat/dtsdec.d \
./include/ffmpeg/libavformat/dtshddec.d \
./include/ffmpeg/libavformat/dump.d \
./include/ffmpeg/libavformat/dv.d \
./include/ffmpeg/libavformat/dvenc.d \
./include/ffmpeg/libavformat/dxa.d \
./include/ffmpeg/libavformat/eacdata.d \
./include/ffmpeg/libavformat/electronicarts.d \
./include/ffmpeg/libavformat/epafdec.d \
./include/ffmpeg/libavformat/ffmdec.d \
./include/ffmpeg/libavformat/ffmenc.d \
./include/ffmpeg/libavformat/ffmetadec.d \
./include/ffmpeg/libavformat/ffmetaenc.d \
./include/ffmpeg/libavformat/file.d \
./include/ffmpeg/libavformat/file_open.d \
./include/ffmpeg/libavformat/filmstripdec.d \
./include/ffmpeg/libavformat/filmstripenc.d \
./include/ffmpeg/libavformat/flac_picture.d \
./include/ffmpeg/libavformat/flacdec.d \
./include/ffmpeg/libavformat/flacenc.d \
./include/ffmpeg/libavformat/flacenc_header.d \
./include/ffmpeg/libavformat/flic.d \
./include/ffmpeg/libavformat/flvdec.d \
./include/ffmpeg/libavformat/flvenc.d \
./include/ffmpeg/libavformat/format.d \
./include/ffmpeg/libavformat/framecrcenc.d \
./include/ffmpeg/libavformat/framehash.d \
./include/ffmpeg/libavformat/frmdec.d \
./include/ffmpeg/libavformat/ftp.d \
./include/ffmpeg/libavformat/g722.d \
./include/ffmpeg/libavformat/g723_1.d \
./include/ffmpeg/libavformat/g729dec.d \
./include/ffmpeg/libavformat/gif.d \
./include/ffmpeg/libavformat/gifdec.d \
./include/ffmpeg/libavformat/golomb_tab.d \
./include/ffmpeg/libavformat/gopher.d \
./include/ffmpeg/libavformat/gsmdec.d \
./include/ffmpeg/libavformat/gxf.d \
./include/ffmpeg/libavformat/gxfenc.d \
./include/ffmpeg/libavformat/h261dec.d \
./include/ffmpeg/libavformat/h263dec.d \
./include/ffmpeg/libavformat/h264dec.d \
./include/ffmpeg/libavformat/hdsenc.d \
./include/ffmpeg/libavformat/hevc.d \
./include/ffmpeg/libavformat/hevcdec.d \
./include/ffmpeg/libavformat/hls.d \
./include/ffmpeg/libavformat/hlsenc.d \
./include/ffmpeg/libavformat/hlsproto.d \
./include/ffmpeg/libavformat/hnm.d \
./include/ffmpeg/libavformat/http.d \
./include/ffmpeg/libavformat/httpauth.d \
./include/ffmpeg/libavformat/icodec.d \
./include/ffmpeg/libavformat/icoenc.d \
./include/ffmpeg/libavformat/id3v1.d \
./include/ffmpeg/libavformat/id3v2.d \
./include/ffmpeg/libavformat/id3v2enc.d \
./include/ffmpeg/libavformat/idcin.d \
./include/ffmpeg/libavformat/idroqdec.d \
./include/ffmpeg/libavformat/idroqenc.d \
./include/ffmpeg/libavformat/iff.d \
./include/ffmpeg/libavformat/ilbc.d \
./include/ffmpeg/libavformat/img2.d \
./include/ffmpeg/libavformat/img2_alias_pix.d \
./include/ffmpeg/libavformat/img2_brender_pix.d \
./include/ffmpeg/libavformat/img2dec.d \
./include/ffmpeg/libavformat/img2enc.d \
./include/ffmpeg/libavformat/ingenientdec.d \
./include/ffmpeg/libavformat/ipmovie.d \
./include/ffmpeg/libavformat/ircam.d \
./include/ffmpeg/libavformat/ircamdec.d \
./include/ffmpeg/libavformat/ircamenc.d \
./include/ffmpeg/libavformat/isom.d \
./include/ffmpeg/libavformat/iss.d \
./include/ffmpeg/libavformat/iv8.d \
./include/ffmpeg/libavformat/ivfdec.d \
./include/ffmpeg/libavformat/ivfenc.d \
./include/ffmpeg/libavformat/jacosubdec.d \
./include/ffmpeg/libavformat/jacosubenc.d \
./include/ffmpeg/libavformat/jvdec.d \
./include/ffmpeg/libavformat/latmenc.d \
./include/ffmpeg/libavformat/libgme.d \
./include/ffmpeg/libavformat/libmodplug.d \
./include/ffmpeg/libavformat/libnut.d \
./include/ffmpeg/libavformat/libquvi.d \
./include/ffmpeg/libavformat/librtmp.d \
./include/ffmpeg/libavformat/libssh.d \
./include/ffmpeg/libavformat/lmlm4.d \
./include/ffmpeg/libavformat/loasdec.d \
./include/ffmpeg/libavformat/log2_tab.d \
./include/ffmpeg/libavformat/lvfdec.d \
./include/ffmpeg/libavformat/lxfdec.d \
./include/ffmpeg/libavformat/m4vdec.d \
./include/ffmpeg/libavformat/matroska.d \
./include/ffmpeg/libavformat/matroskadec.d \
./include/ffmpeg/libavformat/matroskaenc.d \
./include/ffmpeg/libavformat/md5enc.d \
./include/ffmpeg/libavformat/md5proto.d \
./include/ffmpeg/libavformat/metadata.d \
./include/ffmpeg/libavformat/mgsts.d \
./include/ffmpeg/libavformat/microdvddec.d \
./include/ffmpeg/libavformat/microdvdenc.d \
./include/ffmpeg/libavformat/mkvtimestamp_v2.d \
./include/ffmpeg/libavformat/mlvdec.d \
./include/ffmpeg/libavformat/mm.d \
./include/ffmpeg/libavformat/mmf.d \
./include/ffmpeg/libavformat/mms.d \
./include/ffmpeg/libavformat/mmsh.d \
./include/ffmpeg/libavformat/mmst.d \
./include/ffmpeg/libavformat/mov.d \
./include/ffmpeg/libavformat/mov_chan.d \
./include/ffmpeg/libavformat/movenc.d \
./include/ffmpeg/libavformat/movenchint.d \
./include/ffmpeg/libavformat/mp3dec.d \
./include/ffmpeg/libavformat/mp3enc.d \
./include/ffmpeg/libavformat/mpc.d \
./include/ffmpeg/libavformat/mpc8.d \
./include/ffmpeg/libavformat/mpeg.d \
./include/ffmpeg/libavformat/mpegenc.d \
./include/ffmpeg/libavformat/mpegts.d \
./include/ffmpeg/libavformat/mpegtsenc.d \
./include/ffmpeg/libavformat/mpegvideodec.d \
./include/ffmpeg/libavformat/mpjpeg.d \
./include/ffmpeg/libavformat/mpl2dec.d \
./include/ffmpeg/libavformat/mpsubdec.d \
./include/ffmpeg/libavformat/msnwc_tcp.d \
./include/ffmpeg/libavformat/mtv.d \
./include/ffmpeg/libavformat/mux.d \
./include/ffmpeg/libavformat/mvdec.d \
./include/ffmpeg/libavformat/mvi.d \
./include/ffmpeg/libavformat/mxf.d \
./include/ffmpeg/libavformat/mxfdec.d \
./include/ffmpeg/libavformat/mxfenc.d \
./include/ffmpeg/libavformat/mxg.d \
./include/ffmpeg/libavformat/ncdec.d \
./include/ffmpeg/libavformat/network.d \
./include/ffmpeg/libavformat/nistspheredec.d \
./include/ffmpeg/libavformat/noproxy-test.d \
./include/ffmpeg/libavformat/nsvdec.d \
./include/ffmpeg/libavformat/nullenc.d \
./include/ffmpeg/libavformat/nut.d \
./include/ffmpeg/libavformat/nutdec.d \
./include/ffmpeg/libavformat/nutenc.d \
./include/ffmpeg/libavformat/nuv.d \
./include/ffmpeg/libavformat/oggdec.d \
./include/ffmpeg/libavformat/oggenc.d \
./include/ffmpeg/libavformat/oggparsecelt.d \
./include/ffmpeg/libavformat/oggparsedirac.d \
./include/ffmpeg/libavformat/oggparseflac.d \
./include/ffmpeg/libavformat/oggparseogm.d \
./include/ffmpeg/libavformat/oggparseopus.d \
./include/ffmpeg/libavformat/oggparseskeleton.d \
./include/ffmpeg/libavformat/oggparsespeex.d \
./include/ffmpeg/libavformat/oggparsetheora.d \
./include/ffmpeg/libavformat/oggparsevorbis.d \
./include/ffmpeg/libavformat/oggparsevp8.d \
./include/ffmpeg/libavformat/oma.d \
./include/ffmpeg/libavformat/omadec.d \
./include/ffmpeg/libavformat/omaenc.d \
./include/ffmpeg/libavformat/options.d \
./include/ffmpeg/libavformat/os_support.d \
./include/ffmpeg/libavformat/paf.d \
./include/ffmpeg/libavformat/pcm.d \
./include/ffmpeg/libavformat/pcmdec.d \
./include/ffmpeg/libavformat/pcmenc.d \
./include/ffmpeg/libavformat/pjsdec.d \
./include/ffmpeg/libavformat/pmpdec.d \
./include/ffmpeg/libavformat/psxstr.d \
./include/ffmpeg/libavformat/pva.d \
./include/ffmpeg/libavformat/pvfdec.d \
./include/ffmpeg/libavformat/qcp.d \
./include/ffmpeg/libavformat/r3d.d \
./include/ffmpeg/libavformat/rawdec.d \
./include/ffmpeg/libavformat/rawenc.d \
./include/ffmpeg/libavformat/rawvideodec.d \
./include/ffmpeg/libavformat/rdt.d \
./include/ffmpeg/libavformat/realtextdec.d \
./include/ffmpeg/libavformat/redspark.d \
./include/ffmpeg/libavformat/replaygain.d \
./include/ffmpeg/libavformat/riff.d \
./include/ffmpeg/libavformat/riffdec.d \
./include/ffmpeg/libavformat/riffenc.d \
./include/ffmpeg/libavformat/rl2.d \
./include/ffmpeg/libavformat/rm.d \
./include/ffmpeg/libavformat/rmdec.d \
./include/ffmpeg/libavformat/rmenc.d \
./include/ffmpeg/libavformat/rmsipr.d \
./include/ffmpeg/libavformat/rpl.d \
./include/ffmpeg/libavformat/rsd.d \
./include/ffmpeg/libavformat/rso.d \
./include/ffmpeg/libavformat/rsodec.d \
./include/ffmpeg/libavformat/rsoenc.d \
./include/ffmpeg/libavformat/rtmpcrypt.d \
./include/ffmpeg/libavformat/rtmpdh.d \
./include/ffmpeg/libavformat/rtmphttp.d \
./include/ffmpeg/libavformat/rtmppkt.d \
./include/ffmpeg/libavformat/rtmpproto.d \
./include/ffmpeg/libavformat/rtp.d \
./include/ffmpeg/libavformat/rtpdec.d \
./include/ffmpeg/libavformat/rtpdec_amr.d \
./include/ffmpeg/libavformat/rtpdec_asf.d \
./include/ffmpeg/libavformat/rtpdec_g726.d \
./include/ffmpeg/libavformat/rtpdec_h263.d \
./include/ffmpeg/libavformat/rtpdec_h263_rfc2190.d \
./include/ffmpeg/libavformat/rtpdec_h264.d \
./include/ffmpeg/libavformat/rtpdec_ilbc.d \
./include/ffmpeg/libavformat/rtpdec_jpeg.d \
./include/ffmpeg/libavformat/rtpdec_latm.d \
./include/ffmpeg/libavformat/rtpdec_mpeg12.d \
./include/ffmpeg/libavformat/rtpdec_mpeg4.d \
./include/ffmpeg/libavformat/rtpdec_mpegts.d \
./include/ffmpeg/libavformat/rtpdec_qcelp.d \
./include/ffmpeg/libavformat/rtpdec_qdm2.d \
./include/ffmpeg/libavformat/rtpdec_qt.d \
./include/ffmpeg/libavformat/rtpdec_svq3.d \
./include/ffmpeg/libavformat/rtpdec_vp8.d \
./include/ffmpeg/libavformat/rtpdec_xiph.d \
./include/ffmpeg/libavformat/rtpenc.d \
./include/ffmpeg/libavformat/rtpenc_aac.d \
./include/ffmpeg/libavformat/rtpenc_amr.d \
./include/ffmpeg/libavformat/rtpenc_chain.d \
./include/ffmpeg/libavformat/rtpenc_h263.d \
./include/ffmpeg/libavformat/rtpenc_h263_rfc2190.d \
./include/ffmpeg/libavformat/rtpenc_h264.d \
./include/ffmpeg/libavformat/rtpenc_jpeg.d \
./include/ffmpeg/libavformat/rtpenc_latm.d \
./include/ffmpeg/libavformat/rtpenc_mpv.d \
./include/ffmpeg/libavformat/rtpenc_vp8.d \
./include/ffmpeg/libavformat/rtpenc_xiph.d \
./include/ffmpeg/libavformat/rtpproto.d \
./include/ffmpeg/libavformat/rtsp.d \
./include/ffmpeg/libavformat/rtspdec.d \
./include/ffmpeg/libavformat/rtspenc.d \
./include/ffmpeg/libavformat/samidec.d \
./include/ffmpeg/libavformat/sapdec.d \
./include/ffmpeg/libavformat/sapenc.d \
./include/ffmpeg/libavformat/sauce.d \
./include/ffmpeg/libavformat/sbgdec.d \
./include/ffmpeg/libavformat/sctp.d \
./include/ffmpeg/libavformat/sdp.d \
./include/ffmpeg/libavformat/sdr2.d \
./include/ffmpeg/libavformat/seek-test.d \
./include/ffmpeg/libavformat/seek.d \
./include/ffmpeg/libavformat/segafilm.d \
./include/ffmpeg/libavformat/segment.d \
./include/ffmpeg/libavformat/sierravmd.d \
./include/ffmpeg/libavformat/siff.d \
./include/ffmpeg/libavformat/smacker.d \
./include/ffmpeg/libavformat/smjpeg.d \
./include/ffmpeg/libavformat/smjpegdec.d \
./include/ffmpeg/libavformat/smjpegenc.d \
./include/ffmpeg/libavformat/smoothstreamingenc.d \
./include/ffmpeg/libavformat/smush.d \
./include/ffmpeg/libavformat/sol.d \
./include/ffmpeg/libavformat/soxdec.d \
./include/ffmpeg/libavformat/soxenc.d \
./include/ffmpeg/libavformat/spdif.d \
./include/ffmpeg/libavformat/spdifdec.d \
./include/ffmpeg/libavformat/spdifenc.d \
./include/ffmpeg/libavformat/srtdec.d \
./include/ffmpeg/libavformat/srtenc.d \
./include/ffmpeg/libavformat/srtp.d \
./include/ffmpeg/libavformat/srtpproto.d \
./include/ffmpeg/libavformat/subfile.d \
./include/ffmpeg/libavformat/subtitles.d \
./include/ffmpeg/libavformat/subviewer1dec.d \
./include/ffmpeg/libavformat/subviewerdec.d \
./include/ffmpeg/libavformat/swf.d \
./include/ffmpeg/libavformat/swfdec.d \
./include/ffmpeg/libavformat/swfenc.d \
./include/ffmpeg/libavformat/takdec.d \
./include/ffmpeg/libavformat/tcp.d \
./include/ffmpeg/libavformat/tedcaptionsdec.d \
./include/ffmpeg/libavformat/tee.d \
./include/ffmpeg/libavformat/thp.d \
./include/ffmpeg/libavformat/tiertexseq.d \
./include/ffmpeg/libavformat/tls.d \
./include/ffmpeg/libavformat/tmv.d \
./include/ffmpeg/libavformat/tta.d \
./include/ffmpeg/libavformat/tty.d \
./include/ffmpeg/libavformat/txd.d \
./include/ffmpeg/libavformat/udp.d \
./include/ffmpeg/libavformat/uncodedframecrcenc.d \
./include/ffmpeg/libavformat/unix.d \
./include/ffmpeg/libavformat/url-test.d \
./include/ffmpeg/libavformat/url.d \
./include/ffmpeg/libavformat/urldecode.d \
./include/ffmpeg/libavformat/utils.d \
./include/ffmpeg/libavformat/vc1test.d \
./include/ffmpeg/libavformat/vc1testenc.d \
./include/ffmpeg/libavformat/vivo.d \
./include/ffmpeg/libavformat/voc.d \
./include/ffmpeg/libavformat/vocdec.d \
./include/ffmpeg/libavformat/vocenc.d \
./include/ffmpeg/libavformat/vorbiscomment.d \
./include/ffmpeg/libavformat/vplayerdec.d \
./include/ffmpeg/libavformat/vqf.d \
./include/ffmpeg/libavformat/w64.d \
./include/ffmpeg/libavformat/wavdec.d \
./include/ffmpeg/libavformat/wavenc.d \
./include/ffmpeg/libavformat/wc3movie.d \
./include/ffmpeg/libavformat/webvttdec.d \
./include/ffmpeg/libavformat/webvttenc.d \
./include/ffmpeg/libavformat/westwood_aud.d \
./include/ffmpeg/libavformat/westwood_vqa.d \
./include/ffmpeg/libavformat/wtv_common.d \
./include/ffmpeg/libavformat/wtvdec.d \
./include/ffmpeg/libavformat/wtvenc.d \
./include/ffmpeg/libavformat/wv.d \
./include/ffmpeg/libavformat/wvdec.d \
./include/ffmpeg/libavformat/wvenc.d \
./include/ffmpeg/libavformat/xa.d \
./include/ffmpeg/libavformat/xmv.d \
./include/ffmpeg/libavformat/xwma.d \
./include/ffmpeg/libavformat/yop.d \
./include/ffmpeg/libavformat/yuv4mpegdec.d \
./include/ffmpeg/libavformat/yuv4mpegenc.d 


# Each subdirectory must supply rules for building sources it contributes
include/ffmpeg/libavformat/%.o: ../include/ffmpeg/libavformat/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Compiler'
	gcc -I./include -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


