################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../include/ffmpeg/libavcodec/libstagefright.cpp \
../include/ffmpeg/libavcodec/libutvideodec.cpp \
../include/ffmpeg/libavcodec/libutvideoenc.cpp 

C_SRCS += \
../include/ffmpeg/libavcodec/012v.c \
../include/ffmpeg/libavcodec/4xm.c \
../include/ffmpeg/libavcodec/8bps.c \
../include/ffmpeg/libavcodec/8svx.c \
../include/ffmpeg/libavcodec/a64multienc.c \
../include/ffmpeg/libavcodec/aac_ac3_parser.c \
../include/ffmpeg/libavcodec/aac_adtstoasc_bsf.c \
../include/ffmpeg/libavcodec/aac_parser.c \
../include/ffmpeg/libavcodec/aac_tablegen.c \
../include/ffmpeg/libavcodec/aacadtsdec.c \
../include/ffmpeg/libavcodec/aaccoder.c \
../include/ffmpeg/libavcodec/aacdec.c \
../include/ffmpeg/libavcodec/aacenc.c \
../include/ffmpeg/libavcodec/aacps.c \
../include/ffmpeg/libavcodec/aacps_tablegen.c \
../include/ffmpeg/libavcodec/aacpsdata.c \
../include/ffmpeg/libavcodec/aacpsdsp.c \
../include/ffmpeg/libavcodec/aacpsy.c \
../include/ffmpeg/libavcodec/aacsbr.c \
../include/ffmpeg/libavcodec/aactab.c \
../include/ffmpeg/libavcodec/aandcttab.c \
../include/ffmpeg/libavcodec/aasc.c \
../include/ffmpeg/libavcodec/ac3.c \
../include/ffmpeg/libavcodec/ac3_parser.c \
../include/ffmpeg/libavcodec/ac3dec.c \
../include/ffmpeg/libavcodec/ac3dec_data.c \
../include/ffmpeg/libavcodec/ac3dec_fixed.c \
../include/ffmpeg/libavcodec/ac3dec_float.c \
../include/ffmpeg/libavcodec/ac3dsp.c \
../include/ffmpeg/libavcodec/ac3enc.c \
../include/ffmpeg/libavcodec/ac3enc_fixed.c \
../include/ffmpeg/libavcodec/ac3enc_float.c \
../include/ffmpeg/libavcodec/ac3enc_opts_template.c \
../include/ffmpeg/libavcodec/ac3enc_template.c \
../include/ffmpeg/libavcodec/ac3tab.c \
../include/ffmpeg/libavcodec/acelp_filters.c \
../include/ffmpeg/libavcodec/acelp_pitch_delay.c \
../include/ffmpeg/libavcodec/acelp_vectors.c \
../include/ffmpeg/libavcodec/adpcm.c \
../include/ffmpeg/libavcodec/adpcm_data.c \
../include/ffmpeg/libavcodec/adpcmenc.c \
../include/ffmpeg/libavcodec/adx.c \
../include/ffmpeg/libavcodec/adx_parser.c \
../include/ffmpeg/libavcodec/adxdec.c \
../include/ffmpeg/libavcodec/adxenc.c \
../include/ffmpeg/libavcodec/aic.c \
../include/ffmpeg/libavcodec/alac.c \
../include/ffmpeg/libavcodec/alac_data.c \
../include/ffmpeg/libavcodec/alacenc.c \
../include/ffmpeg/libavcodec/aliaspixdec.c \
../include/ffmpeg/libavcodec/aliaspixenc.c \
../include/ffmpeg/libavcodec/allcodecs.c \
../include/ffmpeg/libavcodec/alsdec.c \
../include/ffmpeg/libavcodec/amrnbdec.c \
../include/ffmpeg/libavcodec/amrwbdec.c \
../include/ffmpeg/libavcodec/anm.c \
../include/ffmpeg/libavcodec/ansi.c \
../include/ffmpeg/libavcodec/apedec.c \
../include/ffmpeg/libavcodec/ass.c \
../include/ffmpeg/libavcodec/ass_split.c \
../include/ffmpeg/libavcodec/assdec.c \
../include/ffmpeg/libavcodec/assenc.c \
../include/ffmpeg/libavcodec/asv.c \
../include/ffmpeg/libavcodec/asvdec.c \
../include/ffmpeg/libavcodec/asvenc.c \
../include/ffmpeg/libavcodec/atrac.c \
../include/ffmpeg/libavcodec/atrac1.c \
../include/ffmpeg/libavcodec/atrac3.c \
../include/ffmpeg/libavcodec/atrac3plus.c \
../include/ffmpeg/libavcodec/atrac3plusdec.c \
../include/ffmpeg/libavcodec/atrac3plusdsp.c \
../include/ffmpeg/libavcodec/audio_frame_queue.c \
../include/ffmpeg/libavcodec/audioconvert.c \
../include/ffmpeg/libavcodec/audiodsp.c \
../include/ffmpeg/libavcodec/aura.c \
../include/ffmpeg/libavcodec/avfft.c \
../include/ffmpeg/libavcodec/avpacket.c \
../include/ffmpeg/libavcodec/avpicture.c \
../include/ffmpeg/libavcodec/avrndec.c \
../include/ffmpeg/libavcodec/avs.c \
../include/ffmpeg/libavcodec/avuidec.c \
../include/ffmpeg/libavcodec/avuienc.c \
../include/ffmpeg/libavcodec/bethsoftvideo.c \
../include/ffmpeg/libavcodec/bfi.c \
../include/ffmpeg/libavcodec/bgmc.c \
../include/ffmpeg/libavcodec/bink.c \
../include/ffmpeg/libavcodec/binkaudio.c \
../include/ffmpeg/libavcodec/binkdsp.c \
../include/ffmpeg/libavcodec/bintext.c \
../include/ffmpeg/libavcodec/bit_depth_template.c \
../include/ffmpeg/libavcodec/bitstream.c \
../include/ffmpeg/libavcodec/bitstream_filter.c \
../include/ffmpeg/libavcodec/blockdsp.c \
../include/ffmpeg/libavcodec/bmp.c \
../include/ffmpeg/libavcodec/bmp_parser.c \
../include/ffmpeg/libavcodec/bmpenc.c \
../include/ffmpeg/libavcodec/bmvaudio.c \
../include/ffmpeg/libavcodec/bmvvideo.c \
../include/ffmpeg/libavcodec/brenderpix.c \
../include/ffmpeg/libavcodec/bswapdsp.c \
../include/ffmpeg/libavcodec/c93.c \
../include/ffmpeg/libavcodec/cabac.c \
../include/ffmpeg/libavcodec/cavs.c \
../include/ffmpeg/libavcodec/cavs_parser.c \
../include/ffmpeg/libavcodec/cavsdata.c \
../include/ffmpeg/libavcodec/cavsdec.c \
../include/ffmpeg/libavcodec/cavsdsp.c \
../include/ffmpeg/libavcodec/cbrt_tablegen.c \
../include/ffmpeg/libavcodec/cdgraphics.c \
../include/ffmpeg/libavcodec/cdxl.c \
../include/ffmpeg/libavcodec/celp_filters.c \
../include/ffmpeg/libavcodec/celp_math.c \
../include/ffmpeg/libavcodec/cga_data.c \
../include/ffmpeg/libavcodec/chomp_bsf.c \
../include/ffmpeg/libavcodec/cinepak.c \
../include/ffmpeg/libavcodec/cinepakenc.c \
../include/ffmpeg/libavcodec/cljrdec.c \
../include/ffmpeg/libavcodec/cljrenc.c \
../include/ffmpeg/libavcodec/cllc.c \
../include/ffmpeg/libavcodec/cngdec.c \
../include/ffmpeg/libavcodec/cngenc.c \
../include/ffmpeg/libavcodec/codec_desc.c \
../include/ffmpeg/libavcodec/cook.c \
../include/ffmpeg/libavcodec/cook_parser.c \
../include/ffmpeg/libavcodec/cos_tablegen.c \
../include/ffmpeg/libavcodec/cpia.c \
../include/ffmpeg/libavcodec/crystalhd.c \
../include/ffmpeg/libavcodec/cscd.c \
../include/ffmpeg/libavcodec/cyuv.c \
../include/ffmpeg/libavcodec/dca.c \
../include/ffmpeg/libavcodec/dca_parser.c \
../include/ffmpeg/libavcodec/dcadec.c \
../include/ffmpeg/libavcodec/dcadsp.c \
../include/ffmpeg/libavcodec/dcaenc.c \
../include/ffmpeg/libavcodec/dct-test.c \
../include/ffmpeg/libavcodec/dct.c \
../include/ffmpeg/libavcodec/dct32_fixed.c \
../include/ffmpeg/libavcodec/dct32_float.c \
../include/ffmpeg/libavcodec/dct32_template.c \
../include/ffmpeg/libavcodec/dctref.c \
../include/ffmpeg/libavcodec/dfa.c \
../include/ffmpeg/libavcodec/dirac.c \
../include/ffmpeg/libavcodec/dirac_arith.c \
../include/ffmpeg/libavcodec/dirac_dwt.c \
../include/ffmpeg/libavcodec/dirac_parser.c \
../include/ffmpeg/libavcodec/diracdec.c \
../include/ffmpeg/libavcodec/diracdsp.c \
../include/ffmpeg/libavcodec/dnxhd_parser.c \
../include/ffmpeg/libavcodec/dnxhddata.c \
../include/ffmpeg/libavcodec/dnxhddec.c \
../include/ffmpeg/libavcodec/dnxhdenc.c \
../include/ffmpeg/libavcodec/dpcm.c \
../include/ffmpeg/libavcodec/dpx.c \
../include/ffmpeg/libavcodec/dpx_parser.c \
../include/ffmpeg/libavcodec/dpxenc.c \
../include/ffmpeg/libavcodec/dsd_tablegen.c \
../include/ffmpeg/libavcodec/dsddec.c \
../include/ffmpeg/libavcodec/dsicinaudio.c \
../include/ffmpeg/libavcodec/dsicinvideo.c \
../include/ffmpeg/libavcodec/dsputil.c \
../include/ffmpeg/libavcodec/dump_extradata_bsf.c \
../include/ffmpeg/libavcodec/dv.c \
../include/ffmpeg/libavcodec/dv_profile.c \
../include/ffmpeg/libavcodec/dv_tablegen.c \
../include/ffmpeg/libavcodec/dvbsub.c \
../include/ffmpeg/libavcodec/dvbsub_parser.c \
../include/ffmpeg/libavcodec/dvbsubdec.c \
../include/ffmpeg/libavcodec/dvd_nav_parser.c \
../include/ffmpeg/libavcodec/dvdata.c \
../include/ffmpeg/libavcodec/dvdec.c \
../include/ffmpeg/libavcodec/dvdsub_parser.c \
../include/ffmpeg/libavcodec/dvdsubdec.c \
../include/ffmpeg/libavcodec/dvdsubenc.c \
../include/ffmpeg/libavcodec/dvenc.c \
../include/ffmpeg/libavcodec/dxa.c \
../include/ffmpeg/libavcodec/dxtory.c \
../include/ffmpeg/libavcodec/dxva2.c \
../include/ffmpeg/libavcodec/dxva2_h264.c \
../include/ffmpeg/libavcodec/dxva2_mpeg2.c \
../include/ffmpeg/libavcodec/dxva2_vc1.c \
../include/ffmpeg/libavcodec/eac3_data.c \
../include/ffmpeg/libavcodec/eac3dec.c \
../include/ffmpeg/libavcodec/eac3enc.c \
../include/ffmpeg/libavcodec/eacmv.c \
../include/ffmpeg/libavcodec/eaidct.c \
../include/ffmpeg/libavcodec/eamad.c \
../include/ffmpeg/libavcodec/eatgq.c \
../include/ffmpeg/libavcodec/eatgv.c \
../include/ffmpeg/libavcodec/eatqi.c \
../include/ffmpeg/libavcodec/elbg.c \
../include/ffmpeg/libavcodec/error_resilience.c \
../include/ffmpeg/libavcodec/escape124.c \
../include/ffmpeg/libavcodec/escape130.c \
../include/ffmpeg/libavcodec/evrcdec.c \
../include/ffmpeg/libavcodec/exif.c \
../include/ffmpeg/libavcodec/exr.c \
../include/ffmpeg/libavcodec/faandct.c \
../include/ffmpeg/libavcodec/faanidct.c \
../include/ffmpeg/libavcodec/faxcompr.c \
../include/ffmpeg/libavcodec/fdctdsp.c \
../include/ffmpeg/libavcodec/fft-fixed-test.c \
../include/ffmpeg/libavcodec/fft-fixed32-test.c \
../include/ffmpeg/libavcodec/fft-test.c \
../include/ffmpeg/libavcodec/fft_fixed.c \
../include/ffmpeg/libavcodec/fft_fixed_32.c \
../include/ffmpeg/libavcodec/fft_float.c \
../include/ffmpeg/libavcodec/fft_init_table.c \
../include/ffmpeg/libavcodec/fft_template.c \
../include/ffmpeg/libavcodec/ffv1.c \
../include/ffmpeg/libavcodec/ffv1dec.c \
../include/ffmpeg/libavcodec/ffv1enc.c \
../include/ffmpeg/libavcodec/ffwavesynth.c \
../include/ffmpeg/libavcodec/fic.c \
../include/ffmpeg/libavcodec/file_open.c \
../include/ffmpeg/libavcodec/flac.c \
../include/ffmpeg/libavcodec/flac_parser.c \
../include/ffmpeg/libavcodec/flacdata.c \
../include/ffmpeg/libavcodec/flacdec.c \
../include/ffmpeg/libavcodec/flacdsp.c \
../include/ffmpeg/libavcodec/flacdsp_lpc_template.c \
../include/ffmpeg/libavcodec/flacdsp_template.c \
../include/ffmpeg/libavcodec/flacenc.c \
../include/ffmpeg/libavcodec/flashsv.c \
../include/ffmpeg/libavcodec/flashsv2enc.c \
../include/ffmpeg/libavcodec/flashsvenc.c \
../include/ffmpeg/libavcodec/flicvideo.c \
../include/ffmpeg/libavcodec/flvdec.c \
../include/ffmpeg/libavcodec/flvenc.c \
../include/ffmpeg/libavcodec/fmtconvert.c \
../include/ffmpeg/libavcodec/frame_thread_encoder.c \
../include/ffmpeg/libavcodec/fraps.c \
../include/ffmpeg/libavcodec/frwu.c \
../include/ffmpeg/libavcodec/g2meet.c \
../include/ffmpeg/libavcodec/g722.c \
../include/ffmpeg/libavcodec/g722dec.c \
../include/ffmpeg/libavcodec/g722enc.c \
../include/ffmpeg/libavcodec/g723_1.c \
../include/ffmpeg/libavcodec/g726.c \
../include/ffmpeg/libavcodec/g729dec.c \
../include/ffmpeg/libavcodec/g729postfilter.c \
../include/ffmpeg/libavcodec/gif.c \
../include/ffmpeg/libavcodec/gifdec.c \
../include/ffmpeg/libavcodec/golomb-test.c \
../include/ffmpeg/libavcodec/golomb.c \
../include/ffmpeg/libavcodec/gsm_parser.c \
../include/ffmpeg/libavcodec/gsmdec.c \
../include/ffmpeg/libavcodec/gsmdec_data.c \
../include/ffmpeg/libavcodec/gsmdec_template.c \
../include/ffmpeg/libavcodec/h261.c \
../include/ffmpeg/libavcodec/h261_parser.c \
../include/ffmpeg/libavcodec/h261data.c \
../include/ffmpeg/libavcodec/h261dec.c \
../include/ffmpeg/libavcodec/h261enc.c \
../include/ffmpeg/libavcodec/h263.c \
../include/ffmpeg/libavcodec/h263_parser.c \
../include/ffmpeg/libavcodec/h263dec.c \
../include/ffmpeg/libavcodec/h263dsp.c \
../include/ffmpeg/libavcodec/h264.c \
../include/ffmpeg/libavcodec/h264_cabac.c \
../include/ffmpeg/libavcodec/h264_cavlc.c \
../include/ffmpeg/libavcodec/h264_direct.c \
../include/ffmpeg/libavcodec/h264_loopfilter.c \
../include/ffmpeg/libavcodec/h264_mb.c \
../include/ffmpeg/libavcodec/h264_mb_template.c \
../include/ffmpeg/libavcodec/h264_mc_template.c \
../include/ffmpeg/libavcodec/h264_mp4toannexb_bsf.c \
../include/ffmpeg/libavcodec/h264_parser.c \
../include/ffmpeg/libavcodec/h264_picture.c \
../include/ffmpeg/libavcodec/h264_ps.c \
../include/ffmpeg/libavcodec/h264_refs.c \
../include/ffmpeg/libavcodec/h264_sei.c \
../include/ffmpeg/libavcodec/h264_slice.c \
../include/ffmpeg/libavcodec/h264addpx_template.c \
../include/ffmpeg/libavcodec/h264chroma.c \
../include/ffmpeg/libavcodec/h264chroma_template.c \
../include/ffmpeg/libavcodec/h264dsp.c \
../include/ffmpeg/libavcodec/h264dsp_template.c \
../include/ffmpeg/libavcodec/h264idct.c \
../include/ffmpeg/libavcodec/h264idct_template.c \
../include/ffmpeg/libavcodec/h264pred.c \
../include/ffmpeg/libavcodec/h264pred_template.c \
../include/ffmpeg/libavcodec/h264qpel.c \
../include/ffmpeg/libavcodec/h264qpel_template.c \
../include/ffmpeg/libavcodec/hevc.c \
../include/ffmpeg/libavcodec/hevc_cabac.c \
../include/ffmpeg/libavcodec/hevc_filter.c \
../include/ffmpeg/libavcodec/hevc_mvs.c \
../include/ffmpeg/libavcodec/hevc_parser.c \
../include/ffmpeg/libavcodec/hevc_ps.c \
../include/ffmpeg/libavcodec/hevc_refs.c \
../include/ffmpeg/libavcodec/hevc_sei.c \
../include/ffmpeg/libavcodec/hevcdsp.c \
../include/ffmpeg/libavcodec/hevcdsp_template.c \
../include/ffmpeg/libavcodec/hevcpred.c \
../include/ffmpeg/libavcodec/hevcpred_template.c \
../include/ffmpeg/libavcodec/hnm4video.c \
../include/ffmpeg/libavcodec/hpel_template.c \
../include/ffmpeg/libavcodec/hpeldsp.c \
../include/ffmpeg/libavcodec/huffman.c \
../include/ffmpeg/libavcodec/huffyuv.c \
../include/ffmpeg/libavcodec/huffyuvdec.c \
../include/ffmpeg/libavcodec/huffyuvdsp.c \
../include/ffmpeg/libavcodec/huffyuvenc.c \
../include/ffmpeg/libavcodec/huffyuvencdsp.c \
../include/ffmpeg/libavcodec/idcinvideo.c \
../include/ffmpeg/libavcodec/idctdsp.c \
../include/ffmpeg/libavcodec/iff.c \
../include/ffmpeg/libavcodec/iirfilter.c \
../include/ffmpeg/libavcodec/imc.c \
../include/ffmpeg/libavcodec/imgconvert.c \
../include/ffmpeg/libavcodec/imx_dump_header_bsf.c \
../include/ffmpeg/libavcodec/indeo2.c \
../include/ffmpeg/libavcodec/indeo3.c \
../include/ffmpeg/libavcodec/indeo4.c \
../include/ffmpeg/libavcodec/indeo5.c \
../include/ffmpeg/libavcodec/intelh263dec.c \
../include/ffmpeg/libavcodec/interplayvideo.c \
../include/ffmpeg/libavcodec/intrax8.c \
../include/ffmpeg/libavcodec/intrax8dsp.c \
../include/ffmpeg/libavcodec/ituh263dec.c \
../include/ffmpeg/libavcodec/ituh263enc.c \
../include/ffmpeg/libavcodec/ivi_common.c \
../include/ffmpeg/libavcodec/ivi_dsp.c \
../include/ffmpeg/libavcodec/j2kenc.c \
../include/ffmpeg/libavcodec/jacosubdec.c \
../include/ffmpeg/libavcodec/jfdctfst.c \
../include/ffmpeg/libavcodec/jfdctint.c \
../include/ffmpeg/libavcodec/jfdctint_template.c \
../include/ffmpeg/libavcodec/jpeg2000.c \
../include/ffmpeg/libavcodec/jpeg2000dec.c \
../include/ffmpeg/libavcodec/jpeg2000dwt.c \
../include/ffmpeg/libavcodec/jpegls.c \
../include/ffmpeg/libavcodec/jpeglsdec.c \
../include/ffmpeg/libavcodec/jpeglsenc.c \
../include/ffmpeg/libavcodec/jrevdct.c \
../include/ffmpeg/libavcodec/jvdec.c \
../include/ffmpeg/libavcodec/kbdwin.c \
../include/ffmpeg/libavcodec/kgv1dec.c \
../include/ffmpeg/libavcodec/kmvc.c \
../include/ffmpeg/libavcodec/lagarith.c \
../include/ffmpeg/libavcodec/lagarithrac.c \
../include/ffmpeg/libavcodec/latm_parser.c \
../include/ffmpeg/libavcodec/lcldec.c \
../include/ffmpeg/libavcodec/lclenc.c \
../include/ffmpeg/libavcodec/libaacplus.c \
../include/ffmpeg/libavcodec/libcelt_dec.c \
../include/ffmpeg/libavcodec/libfaac.c \
../include/ffmpeg/libavcodec/libfdk-aacdec.c \
../include/ffmpeg/libavcodec/libfdk-aacenc.c \
../include/ffmpeg/libavcodec/libgsm.c \
../include/ffmpeg/libavcodec/libilbc.c \
../include/ffmpeg/libavcodec/libmp3lame.c \
../include/ffmpeg/libavcodec/libopencore-amr.c \
../include/ffmpeg/libavcodec/libopenjpegdec.c \
../include/ffmpeg/libavcodec/libopenjpegenc.c \
../include/ffmpeg/libavcodec/libopus.c \
../include/ffmpeg/libavcodec/libopusdec.c \
../include/ffmpeg/libavcodec/libopusenc.c \
../include/ffmpeg/libavcodec/libschroedinger.c \
../include/ffmpeg/libavcodec/libschroedingerdec.c \
../include/ffmpeg/libavcodec/libschroedingerenc.c \
../include/ffmpeg/libavcodec/libshine.c \
../include/ffmpeg/libavcodec/libspeexdec.c \
../include/ffmpeg/libavcodec/libspeexenc.c \
../include/ffmpeg/libavcodec/libtheoraenc.c \
../include/ffmpeg/libavcodec/libtwolame.c \
../include/ffmpeg/libavcodec/libvo-aacenc.c \
../include/ffmpeg/libavcodec/libvo-amrwbenc.c \
../include/ffmpeg/libavcodec/libvorbisdec.c \
../include/ffmpeg/libavcodec/libvorbisenc.c \
../include/ffmpeg/libavcodec/libvpx.c \
../include/ffmpeg/libavcodec/libvpxdec.c \
../include/ffmpeg/libavcodec/libvpxenc.c \
../include/ffmpeg/libavcodec/libwavpackenc.c \
../include/ffmpeg/libavcodec/libwebpenc.c \
../include/ffmpeg/libavcodec/libx264.c \
../include/ffmpeg/libavcodec/libx265.c \
../include/ffmpeg/libavcodec/libxavs.c \
../include/ffmpeg/libavcodec/libxvid.c \
../include/ffmpeg/libavcodec/libxvid_rc.c \
../include/ffmpeg/libavcodec/libzvbi-teletextdec.c \
../include/ffmpeg/libavcodec/ljpegenc.c \
../include/ffmpeg/libavcodec/loco.c \
../include/ffmpeg/libavcodec/log2_tab.c \
../include/ffmpeg/libavcodec/lossless_audiodsp.c \
../include/ffmpeg/libavcodec/lossless_videodsp.c \
../include/ffmpeg/libavcodec/lpc.c \
../include/ffmpeg/libavcodec/lsp.c \
../include/ffmpeg/libavcodec/lzw.c \
../include/ffmpeg/libavcodec/lzwenc.c \
../include/ffmpeg/libavcodec/mace.c \
../include/ffmpeg/libavcodec/mathtables.c \
../include/ffmpeg/libavcodec/mdct_fixed.c \
../include/ffmpeg/libavcodec/mdct_fixed_32.c \
../include/ffmpeg/libavcodec/mdct_float.c \
../include/ffmpeg/libavcodec/mdct_template.c \
../include/ffmpeg/libavcodec/mdec.c \
../include/ffmpeg/libavcodec/metasound.c \
../include/ffmpeg/libavcodec/metasound_data.c \
../include/ffmpeg/libavcodec/microdvddec.c \
../include/ffmpeg/libavcodec/mimic.c \
../include/ffmpeg/libavcodec/mjpeg.c \
../include/ffmpeg/libavcodec/mjpeg2jpeg_bsf.c \
../include/ffmpeg/libavcodec/mjpeg_parser.c \
../include/ffmpeg/libavcodec/mjpega_dump_header_bsf.c \
../include/ffmpeg/libavcodec/mjpegbdec.c \
../include/ffmpeg/libavcodec/mjpegdec.c \
../include/ffmpeg/libavcodec/mjpegenc.c \
../include/ffmpeg/libavcodec/mjpegenc_common.c \
../include/ffmpeg/libavcodec/mlp.c \
../include/ffmpeg/libavcodec/mlp_parser.c \
../include/ffmpeg/libavcodec/mlpdec.c \
../include/ffmpeg/libavcodec/mlpdsp.c \
../include/ffmpeg/libavcodec/mmvideo.c \
../include/ffmpeg/libavcodec/motion-test.c \
../include/ffmpeg/libavcodec/motion_est.c \
../include/ffmpeg/libavcodec/motion_est_template.c \
../include/ffmpeg/libavcodec/motionpixels.c \
../include/ffmpeg/libavcodec/motionpixels_tablegen.c \
../include/ffmpeg/libavcodec/movsub_bsf.c \
../include/ffmpeg/libavcodec/movtextdec.c \
../include/ffmpeg/libavcodec/movtextenc.c \
../include/ffmpeg/libavcodec/mp3_header_decompress_bsf.c \
../include/ffmpeg/libavcodec/mpc.c \
../include/ffmpeg/libavcodec/mpc7.c \
../include/ffmpeg/libavcodec/mpc8.c \
../include/ffmpeg/libavcodec/mpeg12.c \
../include/ffmpeg/libavcodec/mpeg12data.c \
../include/ffmpeg/libavcodec/mpeg12dec.c \
../include/ffmpeg/libavcodec/mpeg12enc.c \
../include/ffmpeg/libavcodec/mpeg4audio.c \
../include/ffmpeg/libavcodec/mpeg4video.c \
../include/ffmpeg/libavcodec/mpeg4video_parser.c \
../include/ffmpeg/libavcodec/mpeg4videodec.c \
../include/ffmpeg/libavcodec/mpeg4videoenc.c \
../include/ffmpeg/libavcodec/mpeg_er.c \
../include/ffmpeg/libavcodec/mpegaudio.c \
../include/ffmpeg/libavcodec/mpegaudio_parser.c \
../include/ffmpeg/libavcodec/mpegaudio_tablegen.c \
../include/ffmpeg/libavcodec/mpegaudiodata.c \
../include/ffmpeg/libavcodec/mpegaudiodec_fixed.c \
../include/ffmpeg/libavcodec/mpegaudiodec_float.c \
../include/ffmpeg/libavcodec/mpegaudiodec_template.c \
../include/ffmpeg/libavcodec/mpegaudiodecheader.c \
../include/ffmpeg/libavcodec/mpegaudiodsp.c \
../include/ffmpeg/libavcodec/mpegaudiodsp_data.c \
../include/ffmpeg/libavcodec/mpegaudiodsp_fixed.c \
../include/ffmpeg/libavcodec/mpegaudiodsp_float.c \
../include/ffmpeg/libavcodec/mpegaudiodsp_template.c \
../include/ffmpeg/libavcodec/mpegaudioenc_fixed.c \
../include/ffmpeg/libavcodec/mpegaudioenc_float.c \
../include/ffmpeg/libavcodec/mpegaudioenc_template.c \
../include/ffmpeg/libavcodec/mpegutils.c \
../include/ffmpeg/libavcodec/mpegvideo.c \
../include/ffmpeg/libavcodec/mpegvideo_enc.c \
../include/ffmpeg/libavcodec/mpegvideo_motion.c \
../include/ffmpeg/libavcodec/mpegvideo_parser.c \
../include/ffmpeg/libavcodec/mpegvideo_xvmc.c \
../include/ffmpeg/libavcodec/mpegvideodsp.c \
../include/ffmpeg/libavcodec/mpegvideoencdsp.c \
../include/ffmpeg/libavcodec/mpl2dec.c \
../include/ffmpeg/libavcodec/mqc.c \
../include/ffmpeg/libavcodec/mqcdec.c \
../include/ffmpeg/libavcodec/mqcenc.c \
../include/ffmpeg/libavcodec/msgsmdec.c \
../include/ffmpeg/libavcodec/msmpeg4.c \
../include/ffmpeg/libavcodec/msmpeg4data.c \
../include/ffmpeg/libavcodec/msmpeg4dec.c \
../include/ffmpeg/libavcodec/msmpeg4enc.c \
../include/ffmpeg/libavcodec/msrle.c \
../include/ffmpeg/libavcodec/msrledec.c \
../include/ffmpeg/libavcodec/mss1.c \
../include/ffmpeg/libavcodec/mss12.c \
../include/ffmpeg/libavcodec/mss2.c \
../include/ffmpeg/libavcodec/mss2dsp.c \
../include/ffmpeg/libavcodec/mss3.c \
../include/ffmpeg/libavcodec/mss34dsp.c \
../include/ffmpeg/libavcodec/mss4.c \
../include/ffmpeg/libavcodec/msvideo1.c \
../include/ffmpeg/libavcodec/msvideo1enc.c \
../include/ffmpeg/libavcodec/mvcdec.c \
../include/ffmpeg/libavcodec/mxpegdec.c \
../include/ffmpeg/libavcodec/nellymoser.c \
../include/ffmpeg/libavcodec/nellymoserdec.c \
../include/ffmpeg/libavcodec/nellymoserenc.c \
../include/ffmpeg/libavcodec/noise_bsf.c \
../include/ffmpeg/libavcodec/nuv.c \
../include/ffmpeg/libavcodec/on2avc.c \
../include/ffmpeg/libavcodec/on2avcdata.c \
../include/ffmpeg/libavcodec/options.c \
../include/ffmpeg/libavcodec/opus.c \
../include/ffmpeg/libavcodec/opus_celt.c \
../include/ffmpeg/libavcodec/opus_imdct.c \
../include/ffmpeg/libavcodec/opus_parser.c \
../include/ffmpeg/libavcodec/opus_silk.c \
../include/ffmpeg/libavcodec/opusdec.c \
../include/ffmpeg/libavcodec/pafaudio.c \
../include/ffmpeg/libavcodec/pafvideo.c \
../include/ffmpeg/libavcodec/pamenc.c \
../include/ffmpeg/libavcodec/parser.c \
../include/ffmpeg/libavcodec/pcm-bluray.c \
../include/ffmpeg/libavcodec/pcm-dvd.c \
../include/ffmpeg/libavcodec/pcm.c \
../include/ffmpeg/libavcodec/pcm_tablegen.c \
../include/ffmpeg/libavcodec/pcx.c \
../include/ffmpeg/libavcodec/pcxenc.c \
../include/ffmpeg/libavcodec/pel_template.c \
../include/ffmpeg/libavcodec/pgssubdec.c \
../include/ffmpeg/libavcodec/pictordec.c \
../include/ffmpeg/libavcodec/pixblockdsp.c \
../include/ffmpeg/libavcodec/pixblockdsp_template.c \
../include/ffmpeg/libavcodec/png.c \
../include/ffmpeg/libavcodec/png_parser.c \
../include/ffmpeg/libavcodec/pngdec.c \
../include/ffmpeg/libavcodec/pngdsp.c \
../include/ffmpeg/libavcodec/pngenc.c \
../include/ffmpeg/libavcodec/pnm.c \
../include/ffmpeg/libavcodec/pnm_parser.c \
../include/ffmpeg/libavcodec/pnmdec.c \
../include/ffmpeg/libavcodec/pnmenc.c \
../include/ffmpeg/libavcodec/proresdata.c \
../include/ffmpeg/libavcodec/proresdec2.c \
../include/ffmpeg/libavcodec/proresdec_lgpl.c \
../include/ffmpeg/libavcodec/proresdsp.c \
../include/ffmpeg/libavcodec/proresenc_anatoliy.c \
../include/ffmpeg/libavcodec/proresenc_kostya.c \
../include/ffmpeg/libavcodec/psymodel.c \
../include/ffmpeg/libavcodec/pthread.c \
../include/ffmpeg/libavcodec/pthread_frame.c \
../include/ffmpeg/libavcodec/pthread_slice.c \
../include/ffmpeg/libavcodec/ptx.c \
../include/ffmpeg/libavcodec/qcelpdec.c \
../include/ffmpeg/libavcodec/qdm2.c \
../include/ffmpeg/libavcodec/qdm2_tablegen.c \
../include/ffmpeg/libavcodec/qdrw.c \
../include/ffmpeg/libavcodec/qpeg.c \
../include/ffmpeg/libavcodec/qpel_template.c \
../include/ffmpeg/libavcodec/qpeldsp.c \
../include/ffmpeg/libavcodec/qtrle.c \
../include/ffmpeg/libavcodec/qtrleenc.c \
../include/ffmpeg/libavcodec/r210dec.c \
../include/ffmpeg/libavcodec/r210enc.c \
../include/ffmpeg/libavcodec/ra144.c \
../include/ffmpeg/libavcodec/ra144dec.c \
../include/ffmpeg/libavcodec/ra144enc.c \
../include/ffmpeg/libavcodec/ra288.c \
../include/ffmpeg/libavcodec/ralf.c \
../include/ffmpeg/libavcodec/rangecoder.c \
../include/ffmpeg/libavcodec/ratecontrol.c \
../include/ffmpeg/libavcodec/raw.c \
../include/ffmpeg/libavcodec/rawdec.c \
../include/ffmpeg/libavcodec/rawenc.c \
../include/ffmpeg/libavcodec/rdft.c \
../include/ffmpeg/libavcodec/realtextdec.c \
../include/ffmpeg/libavcodec/remove_extradata_bsf.c \
../include/ffmpeg/libavcodec/resample.c \
../include/ffmpeg/libavcodec/resample2.c \
../include/ffmpeg/libavcodec/rl2.c \
../include/ffmpeg/libavcodec/rle.c \
../include/ffmpeg/libavcodec/roqaudioenc.c \
../include/ffmpeg/libavcodec/roqvideo.c \
../include/ffmpeg/libavcodec/roqvideodec.c \
../include/ffmpeg/libavcodec/roqvideoenc.c \
../include/ffmpeg/libavcodec/rpza.c \
../include/ffmpeg/libavcodec/rtjpeg.c \
../include/ffmpeg/libavcodec/rv10.c \
../include/ffmpeg/libavcodec/rv10enc.c \
../include/ffmpeg/libavcodec/rv20enc.c \
../include/ffmpeg/libavcodec/rv30.c \
../include/ffmpeg/libavcodec/rv30dsp.c \
../include/ffmpeg/libavcodec/rv34.c \
../include/ffmpeg/libavcodec/rv34_parser.c \
../include/ffmpeg/libavcodec/rv34dsp.c \
../include/ffmpeg/libavcodec/rv40.c \
../include/ffmpeg/libavcodec/rv40dsp.c \
../include/ffmpeg/libavcodec/s302m.c \
../include/ffmpeg/libavcodec/s302menc.c \
../include/ffmpeg/libavcodec/s3tc.c \
../include/ffmpeg/libavcodec/samidec.c \
../include/ffmpeg/libavcodec/sanm.c \
../include/ffmpeg/libavcodec/sbrdsp.c \
../include/ffmpeg/libavcodec/sgidec.c \
../include/ffmpeg/libavcodec/sgienc.c \
../include/ffmpeg/libavcodec/sgirledec.c \
../include/ffmpeg/libavcodec/shorten.c \
../include/ffmpeg/libavcodec/simple_idct.c \
../include/ffmpeg/libavcodec/simple_idct_template.c \
../include/ffmpeg/libavcodec/sinewin.c \
../include/ffmpeg/libavcodec/sinewin_tablegen.c \
../include/ffmpeg/libavcodec/sipr.c \
../include/ffmpeg/libavcodec/sipr16k.c \
../include/ffmpeg/libavcodec/smacker.c \
../include/ffmpeg/libavcodec/smc.c \
../include/ffmpeg/libavcodec/smvjpegdec.c \
../include/ffmpeg/libavcodec/snow.c \
../include/ffmpeg/libavcodec/snow_dwt.c \
../include/ffmpeg/libavcodec/snowdec.c \
../include/ffmpeg/libavcodec/snowenc.c \
../include/ffmpeg/libavcodec/sonic.c \
../include/ffmpeg/libavcodec/sp5xdec.c \
../include/ffmpeg/libavcodec/srtdec.c \
../include/ffmpeg/libavcodec/srtenc.c \
../include/ffmpeg/libavcodec/startcode.c \
../include/ffmpeg/libavcodec/subviewerdec.c \
../include/ffmpeg/libavcodec/sunrast.c \
../include/ffmpeg/libavcodec/sunrastenc.c \
../include/ffmpeg/libavcodec/svq1.c \
../include/ffmpeg/libavcodec/svq13.c \
../include/ffmpeg/libavcodec/svq1dec.c \
../include/ffmpeg/libavcodec/svq1enc.c \
../include/ffmpeg/libavcodec/svq3.c \
../include/ffmpeg/libavcodec/synth_filter.c \
../include/ffmpeg/libavcodec/tak.c \
../include/ffmpeg/libavcodec/tak_parser.c \
../include/ffmpeg/libavcodec/takdec.c \
../include/ffmpeg/libavcodec/targa.c \
../include/ffmpeg/libavcodec/targa_y216dec.c \
../include/ffmpeg/libavcodec/targaenc.c \
../include/ffmpeg/libavcodec/textdec.c \
../include/ffmpeg/libavcodec/tiertexseqv.c \
../include/ffmpeg/libavcodec/tiff.c \
../include/ffmpeg/libavcodec/tiff_common.c \
../include/ffmpeg/libavcodec/tiff_data.c \
../include/ffmpeg/libavcodec/tiffenc.c \
../include/ffmpeg/libavcodec/tmv.c \
../include/ffmpeg/libavcodec/tpeldsp.c \
../include/ffmpeg/libavcodec/truemotion1.c \
../include/ffmpeg/libavcodec/truemotion2.c \
../include/ffmpeg/libavcodec/truespeech.c \
../include/ffmpeg/libavcodec/tscc.c \
../include/ffmpeg/libavcodec/tscc2.c \
../include/ffmpeg/libavcodec/tta.c \
../include/ffmpeg/libavcodec/ttadata.c \
../include/ffmpeg/libavcodec/ttadsp.c \
../include/ffmpeg/libavcodec/ttaenc.c \
../include/ffmpeg/libavcodec/twinvq.c \
../include/ffmpeg/libavcodec/twinvqdec.c \
../include/ffmpeg/libavcodec/txd.c \
../include/ffmpeg/libavcodec/ulti.c \
../include/ffmpeg/libavcodec/utils.c \
../include/ffmpeg/libavcodec/utvideo.c \
../include/ffmpeg/libavcodec/utvideodec.c \
../include/ffmpeg/libavcodec/utvideoenc.c \
../include/ffmpeg/libavcodec/v210dec.c \
../include/ffmpeg/libavcodec/v210enc.c \
../include/ffmpeg/libavcodec/v210x.c \
../include/ffmpeg/libavcodec/v308dec.c \
../include/ffmpeg/libavcodec/v308enc.c \
../include/ffmpeg/libavcodec/v408dec.c \
../include/ffmpeg/libavcodec/v408enc.c \
../include/ffmpeg/libavcodec/v410dec.c \
../include/ffmpeg/libavcodec/v410enc.c \
../include/ffmpeg/libavcodec/vaapi.c \
../include/ffmpeg/libavcodec/vaapi_h264.c \
../include/ffmpeg/libavcodec/vaapi_mpeg.c \
../include/ffmpeg/libavcodec/vaapi_mpeg2.c \
../include/ffmpeg/libavcodec/vaapi_mpeg4.c \
../include/ffmpeg/libavcodec/vaapi_vc1.c \
../include/ffmpeg/libavcodec/vb.c \
../include/ffmpeg/libavcodec/vble.c \
../include/ffmpeg/libavcodec/vc1.c \
../include/ffmpeg/libavcodec/vc1_parser.c \
../include/ffmpeg/libavcodec/vc1data.c \
../include/ffmpeg/libavcodec/vc1dec.c \
../include/ffmpeg/libavcodec/vc1dsp.c \
../include/ffmpeg/libavcodec/vcr1.c \
../include/ffmpeg/libavcodec/vda.c \
../include/ffmpeg/libavcodec/vda_h264.c \
../include/ffmpeg/libavcodec/vda_h264_dec.c \
../include/ffmpeg/libavcodec/vdpau.c \
../include/ffmpeg/libavcodec/vdpau_h264.c \
../include/ffmpeg/libavcodec/vdpau_mpeg12.c \
../include/ffmpeg/libavcodec/vdpau_mpeg4.c \
../include/ffmpeg/libavcodec/vdpau_vc1.c \
../include/ffmpeg/libavcodec/videodsp.c \
../include/ffmpeg/libavcodec/videodsp_template.c \
../include/ffmpeg/libavcodec/vima.c \
../include/ffmpeg/libavcodec/vmdaudio.c \
../include/ffmpeg/libavcodec/vmdvideo.c \
../include/ffmpeg/libavcodec/vmnc.c \
../include/ffmpeg/libavcodec/vorbis.c \
../include/ffmpeg/libavcodec/vorbis_data.c \
../include/ffmpeg/libavcodec/vorbis_parser.c \
../include/ffmpeg/libavcodec/vorbisdec.c \
../include/ffmpeg/libavcodec/vorbisdsp.c \
../include/ffmpeg/libavcodec/vorbisenc.c \
../include/ffmpeg/libavcodec/vp3.c \
../include/ffmpeg/libavcodec/vp3_parser.c \
../include/ffmpeg/libavcodec/vp3dsp.c \
../include/ffmpeg/libavcodec/vp5.c \
../include/ffmpeg/libavcodec/vp56.c \
../include/ffmpeg/libavcodec/vp56data.c \
../include/ffmpeg/libavcodec/vp56dsp.c \
../include/ffmpeg/libavcodec/vp56rac.c \
../include/ffmpeg/libavcodec/vp6.c \
../include/ffmpeg/libavcodec/vp6dsp.c \
../include/ffmpeg/libavcodec/vp8.c \
../include/ffmpeg/libavcodec/vp8_parser.c \
../include/ffmpeg/libavcodec/vp8dsp.c \
../include/ffmpeg/libavcodec/vp9.c \
../include/ffmpeg/libavcodec/vp9_parser.c \
../include/ffmpeg/libavcodec/vp9dsp.c \
../include/ffmpeg/libavcodec/vqavideo.c \
../include/ffmpeg/libavcodec/wavpack.c \
../include/ffmpeg/libavcodec/wavpackenc.c \
../include/ffmpeg/libavcodec/webp.c \
../include/ffmpeg/libavcodec/webvttdec.c \
../include/ffmpeg/libavcodec/webvttenc.c \
../include/ffmpeg/libavcodec/wma.c \
../include/ffmpeg/libavcodec/wma_common.c \
../include/ffmpeg/libavcodec/wmadec.c \
../include/ffmpeg/libavcodec/wmaenc.c \
../include/ffmpeg/libavcodec/wmalosslessdec.c \
../include/ffmpeg/libavcodec/wmaprodec.c \
../include/ffmpeg/libavcodec/wmavoice.c \
../include/ffmpeg/libavcodec/wmv2.c \
../include/ffmpeg/libavcodec/wmv2dec.c \
../include/ffmpeg/libavcodec/wmv2dsp.c \
../include/ffmpeg/libavcodec/wmv2enc.c \
../include/ffmpeg/libavcodec/wnv1.c \
../include/ffmpeg/libavcodec/ws-snd1.c \
../include/ffmpeg/libavcodec/xan.c \
../include/ffmpeg/libavcodec/xbmdec.c \
../include/ffmpeg/libavcodec/xbmenc.c \
../include/ffmpeg/libavcodec/xface.c \
../include/ffmpeg/libavcodec/xfacedec.c \
../include/ffmpeg/libavcodec/xfaceenc.c \
../include/ffmpeg/libavcodec/xiph.c \
../include/ffmpeg/libavcodec/xl.c \
../include/ffmpeg/libavcodec/xsubdec.c \
../include/ffmpeg/libavcodec/xsubenc.c \
../include/ffmpeg/libavcodec/xwddec.c \
../include/ffmpeg/libavcodec/xwdenc.c \
../include/ffmpeg/libavcodec/xxan.c \
../include/ffmpeg/libavcodec/y41pdec.c \
../include/ffmpeg/libavcodec/y41penc.c \
../include/ffmpeg/libavcodec/yop.c \
../include/ffmpeg/libavcodec/yuv4dec.c \
../include/ffmpeg/libavcodec/yuv4enc.c \
../include/ffmpeg/libavcodec/zerocodec.c \
../include/ffmpeg/libavcodec/zmbv.c \
../include/ffmpeg/libavcodec/zmbvenc.c 

OBJS += \
./include/ffmpeg/libavcodec/012v.o \
./include/ffmpeg/libavcodec/4xm.o \
./include/ffmpeg/libavcodec/8bps.o \
./include/ffmpeg/libavcodec/8svx.o \
./include/ffmpeg/libavcodec/a64multienc.o \
./include/ffmpeg/libavcodec/aac_ac3_parser.o \
./include/ffmpeg/libavcodec/aac_adtstoasc_bsf.o \
./include/ffmpeg/libavcodec/aac_parser.o \
./include/ffmpeg/libavcodec/aac_tablegen.o \
./include/ffmpeg/libavcodec/aacadtsdec.o \
./include/ffmpeg/libavcodec/aaccoder.o \
./include/ffmpeg/libavcodec/aacdec.o \
./include/ffmpeg/libavcodec/aacenc.o \
./include/ffmpeg/libavcodec/aacps.o \
./include/ffmpeg/libavcodec/aacps_tablegen.o \
./include/ffmpeg/libavcodec/aacpsdata.o \
./include/ffmpeg/libavcodec/aacpsdsp.o \
./include/ffmpeg/libavcodec/aacpsy.o \
./include/ffmpeg/libavcodec/aacsbr.o \
./include/ffmpeg/libavcodec/aactab.o \
./include/ffmpeg/libavcodec/aandcttab.o \
./include/ffmpeg/libavcodec/aasc.o \
./include/ffmpeg/libavcodec/ac3.o \
./include/ffmpeg/libavcodec/ac3_parser.o \
./include/ffmpeg/libavcodec/ac3dec.o \
./include/ffmpeg/libavcodec/ac3dec_data.o \
./include/ffmpeg/libavcodec/ac3dec_fixed.o \
./include/ffmpeg/libavcodec/ac3dec_float.o \
./include/ffmpeg/libavcodec/ac3dsp.o \
./include/ffmpeg/libavcodec/ac3enc.o \
./include/ffmpeg/libavcodec/ac3enc_fixed.o \
./include/ffmpeg/libavcodec/ac3enc_float.o \
./include/ffmpeg/libavcodec/ac3enc_opts_template.o \
./include/ffmpeg/libavcodec/ac3enc_template.o \
./include/ffmpeg/libavcodec/ac3tab.o \
./include/ffmpeg/libavcodec/acelp_filters.o \
./include/ffmpeg/libavcodec/acelp_pitch_delay.o \
./include/ffmpeg/libavcodec/acelp_vectors.o \
./include/ffmpeg/libavcodec/adpcm.o \
./include/ffmpeg/libavcodec/adpcm_data.o \
./include/ffmpeg/libavcodec/adpcmenc.o \
./include/ffmpeg/libavcodec/adx.o \
./include/ffmpeg/libavcodec/adx_parser.o \
./include/ffmpeg/libavcodec/adxdec.o \
./include/ffmpeg/libavcodec/adxenc.o \
./include/ffmpeg/libavcodec/aic.o \
./include/ffmpeg/libavcodec/alac.o \
./include/ffmpeg/libavcodec/alac_data.o \
./include/ffmpeg/libavcodec/alacenc.o \
./include/ffmpeg/libavcodec/aliaspixdec.o \
./include/ffmpeg/libavcodec/aliaspixenc.o \
./include/ffmpeg/libavcodec/allcodecs.o \
./include/ffmpeg/libavcodec/alsdec.o \
./include/ffmpeg/libavcodec/amrnbdec.o \
./include/ffmpeg/libavcodec/amrwbdec.o \
./include/ffmpeg/libavcodec/anm.o \
./include/ffmpeg/libavcodec/ansi.o \
./include/ffmpeg/libavcodec/apedec.o \
./include/ffmpeg/libavcodec/ass.o \
./include/ffmpeg/libavcodec/ass_split.o \
./include/ffmpeg/libavcodec/assdec.o \
./include/ffmpeg/libavcodec/assenc.o \
./include/ffmpeg/libavcodec/asv.o \
./include/ffmpeg/libavcodec/asvdec.o \
./include/ffmpeg/libavcodec/asvenc.o \
./include/ffmpeg/libavcodec/atrac.o \
./include/ffmpeg/libavcodec/atrac1.o \
./include/ffmpeg/libavcodec/atrac3.o \
./include/ffmpeg/libavcodec/atrac3plus.o \
./include/ffmpeg/libavcodec/atrac3plusdec.o \
./include/ffmpeg/libavcodec/atrac3plusdsp.o \
./include/ffmpeg/libavcodec/audio_frame_queue.o \
./include/ffmpeg/libavcodec/audioconvert.o \
./include/ffmpeg/libavcodec/audiodsp.o \
./include/ffmpeg/libavcodec/aura.o \
./include/ffmpeg/libavcodec/avfft.o \
./include/ffmpeg/libavcodec/avpacket.o \
./include/ffmpeg/libavcodec/avpicture.o \
./include/ffmpeg/libavcodec/avrndec.o \
./include/ffmpeg/libavcodec/avs.o \
./include/ffmpeg/libavcodec/avuidec.o \
./include/ffmpeg/libavcodec/avuienc.o \
./include/ffmpeg/libavcodec/bethsoftvideo.o \
./include/ffmpeg/libavcodec/bfi.o \
./include/ffmpeg/libavcodec/bgmc.o \
./include/ffmpeg/libavcodec/bink.o \
./include/ffmpeg/libavcodec/binkaudio.o \
./include/ffmpeg/libavcodec/binkdsp.o \
./include/ffmpeg/libavcodec/bintext.o \
./include/ffmpeg/libavcodec/bit_depth_template.o \
./include/ffmpeg/libavcodec/bitstream.o \
./include/ffmpeg/libavcodec/bitstream_filter.o \
./include/ffmpeg/libavcodec/blockdsp.o \
./include/ffmpeg/libavcodec/bmp.o \
./include/ffmpeg/libavcodec/bmp_parser.o \
./include/ffmpeg/libavcodec/bmpenc.o \
./include/ffmpeg/libavcodec/bmvaudio.o \
./include/ffmpeg/libavcodec/bmvvideo.o \
./include/ffmpeg/libavcodec/brenderpix.o \
./include/ffmpeg/libavcodec/bswapdsp.o \
./include/ffmpeg/libavcodec/c93.o \
./include/ffmpeg/libavcodec/cabac.o \
./include/ffmpeg/libavcodec/cavs.o \
./include/ffmpeg/libavcodec/cavs_parser.o \
./include/ffmpeg/libavcodec/cavsdata.o \
./include/ffmpeg/libavcodec/cavsdec.o \
./include/ffmpeg/libavcodec/cavsdsp.o \
./include/ffmpeg/libavcodec/cbrt_tablegen.o \
./include/ffmpeg/libavcodec/cdgraphics.o \
./include/ffmpeg/libavcodec/cdxl.o \
./include/ffmpeg/libavcodec/celp_filters.o \
./include/ffmpeg/libavcodec/celp_math.o \
./include/ffmpeg/libavcodec/cga_data.o \
./include/ffmpeg/libavcodec/chomp_bsf.o \
./include/ffmpeg/libavcodec/cinepak.o \
./include/ffmpeg/libavcodec/cinepakenc.o \
./include/ffmpeg/libavcodec/cljrdec.o \
./include/ffmpeg/libavcodec/cljrenc.o \
./include/ffmpeg/libavcodec/cllc.o \
./include/ffmpeg/libavcodec/cngdec.o \
./include/ffmpeg/libavcodec/cngenc.o \
./include/ffmpeg/libavcodec/codec_desc.o \
./include/ffmpeg/libavcodec/cook.o \
./include/ffmpeg/libavcodec/cook_parser.o \
./include/ffmpeg/libavcodec/cos_tablegen.o \
./include/ffmpeg/libavcodec/cpia.o \
./include/ffmpeg/libavcodec/crystalhd.o \
./include/ffmpeg/libavcodec/cscd.o \
./include/ffmpeg/libavcodec/cyuv.o \
./include/ffmpeg/libavcodec/dca.o \
./include/ffmpeg/libavcodec/dca_parser.o \
./include/ffmpeg/libavcodec/dcadec.o \
./include/ffmpeg/libavcodec/dcadsp.o \
./include/ffmpeg/libavcodec/dcaenc.o \
./include/ffmpeg/libavcodec/dct-test.o \
./include/ffmpeg/libavcodec/dct.o \
./include/ffmpeg/libavcodec/dct32_fixed.o \
./include/ffmpeg/libavcodec/dct32_float.o \
./include/ffmpeg/libavcodec/dct32_template.o \
./include/ffmpeg/libavcodec/dctref.o \
./include/ffmpeg/libavcodec/dfa.o \
./include/ffmpeg/libavcodec/dirac.o \
./include/ffmpeg/libavcodec/dirac_arith.o \
./include/ffmpeg/libavcodec/dirac_dwt.o \
./include/ffmpeg/libavcodec/dirac_parser.o \
./include/ffmpeg/libavcodec/diracdec.o \
./include/ffmpeg/libavcodec/diracdsp.o \
./include/ffmpeg/libavcodec/dnxhd_parser.o \
./include/ffmpeg/libavcodec/dnxhddata.o \
./include/ffmpeg/libavcodec/dnxhddec.o \
./include/ffmpeg/libavcodec/dnxhdenc.o \
./include/ffmpeg/libavcodec/dpcm.o \
./include/ffmpeg/libavcodec/dpx.o \
./include/ffmpeg/libavcodec/dpx_parser.o \
./include/ffmpeg/libavcodec/dpxenc.o \
./include/ffmpeg/libavcodec/dsd_tablegen.o \
./include/ffmpeg/libavcodec/dsddec.o \
./include/ffmpeg/libavcodec/dsicinaudio.o \
./include/ffmpeg/libavcodec/dsicinvideo.o \
./include/ffmpeg/libavcodec/dsputil.o \
./include/ffmpeg/libavcodec/dump_extradata_bsf.o \
./include/ffmpeg/libavcodec/dv.o \
./include/ffmpeg/libavcodec/dv_profile.o \
./include/ffmpeg/libavcodec/dv_tablegen.o \
./include/ffmpeg/libavcodec/dvbsub.o \
./include/ffmpeg/libavcodec/dvbsub_parser.o \
./include/ffmpeg/libavcodec/dvbsubdec.o \
./include/ffmpeg/libavcodec/dvd_nav_parser.o \
./include/ffmpeg/libavcodec/dvdata.o \
./include/ffmpeg/libavcodec/dvdec.o \
./include/ffmpeg/libavcodec/dvdsub_parser.o \
./include/ffmpeg/libavcodec/dvdsubdec.o \
./include/ffmpeg/libavcodec/dvdsubenc.o \
./include/ffmpeg/libavcodec/dvenc.o \
./include/ffmpeg/libavcodec/dxa.o \
./include/ffmpeg/libavcodec/dxtory.o \
./include/ffmpeg/libavcodec/dxva2.o \
./include/ffmpeg/libavcodec/dxva2_h264.o \
./include/ffmpeg/libavcodec/dxva2_mpeg2.o \
./include/ffmpeg/libavcodec/dxva2_vc1.o \
./include/ffmpeg/libavcodec/eac3_data.o \
./include/ffmpeg/libavcodec/eac3dec.o \
./include/ffmpeg/libavcodec/eac3enc.o \
./include/ffmpeg/libavcodec/eacmv.o \
./include/ffmpeg/libavcodec/eaidct.o \
./include/ffmpeg/libavcodec/eamad.o \
./include/ffmpeg/libavcodec/eatgq.o \
./include/ffmpeg/libavcodec/eatgv.o \
./include/ffmpeg/libavcodec/eatqi.o \
./include/ffmpeg/libavcodec/elbg.o \
./include/ffmpeg/libavcodec/error_resilience.o \
./include/ffmpeg/libavcodec/escape124.o \
./include/ffmpeg/libavcodec/escape130.o \
./include/ffmpeg/libavcodec/evrcdec.o \
./include/ffmpeg/libavcodec/exif.o \
./include/ffmpeg/libavcodec/exr.o \
./include/ffmpeg/libavcodec/faandct.o \
./include/ffmpeg/libavcodec/faanidct.o \
./include/ffmpeg/libavcodec/faxcompr.o \
./include/ffmpeg/libavcodec/fdctdsp.o \
./include/ffmpeg/libavcodec/fft-fixed-test.o \
./include/ffmpeg/libavcodec/fft-fixed32-test.o \
./include/ffmpeg/libavcodec/fft-test.o \
./include/ffmpeg/libavcodec/fft_fixed.o \
./include/ffmpeg/libavcodec/fft_fixed_32.o \
./include/ffmpeg/libavcodec/fft_float.o \
./include/ffmpeg/libavcodec/fft_init_table.o \
./include/ffmpeg/libavcodec/fft_template.o \
./include/ffmpeg/libavcodec/ffv1.o \
./include/ffmpeg/libavcodec/ffv1dec.o \
./include/ffmpeg/libavcodec/ffv1enc.o \
./include/ffmpeg/libavcodec/ffwavesynth.o \
./include/ffmpeg/libavcodec/fic.o \
./include/ffmpeg/libavcodec/file_open.o \
./include/ffmpeg/libavcodec/flac.o \
./include/ffmpeg/libavcodec/flac_parser.o \
./include/ffmpeg/libavcodec/flacdata.o \
./include/ffmpeg/libavcodec/flacdec.o \
./include/ffmpeg/libavcodec/flacdsp.o \
./include/ffmpeg/libavcodec/flacdsp_lpc_template.o \
./include/ffmpeg/libavcodec/flacdsp_template.o \
./include/ffmpeg/libavcodec/flacenc.o \
./include/ffmpeg/libavcodec/flashsv.o \
./include/ffmpeg/libavcodec/flashsv2enc.o \
./include/ffmpeg/libavcodec/flashsvenc.o \
./include/ffmpeg/libavcodec/flicvideo.o \
./include/ffmpeg/libavcodec/flvdec.o \
./include/ffmpeg/libavcodec/flvenc.o \
./include/ffmpeg/libavcodec/fmtconvert.o \
./include/ffmpeg/libavcodec/frame_thread_encoder.o \
./include/ffmpeg/libavcodec/fraps.o \
./include/ffmpeg/libavcodec/frwu.o \
./include/ffmpeg/libavcodec/g2meet.o \
./include/ffmpeg/libavcodec/g722.o \
./include/ffmpeg/libavcodec/g722dec.o \
./include/ffmpeg/libavcodec/g722enc.o \
./include/ffmpeg/libavcodec/g723_1.o \
./include/ffmpeg/libavcodec/g726.o \
./include/ffmpeg/libavcodec/g729dec.o \
./include/ffmpeg/libavcodec/g729postfilter.o \
./include/ffmpeg/libavcodec/gif.o \
./include/ffmpeg/libavcodec/gifdec.o \
./include/ffmpeg/libavcodec/golomb-test.o \
./include/ffmpeg/libavcodec/golomb.o \
./include/ffmpeg/libavcodec/gsm_parser.o \
./include/ffmpeg/libavcodec/gsmdec.o \
./include/ffmpeg/libavcodec/gsmdec_data.o \
./include/ffmpeg/libavcodec/gsmdec_template.o \
./include/ffmpeg/libavcodec/h261.o \
./include/ffmpeg/libavcodec/h261_parser.o \
./include/ffmpeg/libavcodec/h261data.o \
./include/ffmpeg/libavcodec/h261dec.o \
./include/ffmpeg/libavcodec/h261enc.o \
./include/ffmpeg/libavcodec/h263.o \
./include/ffmpeg/libavcodec/h263_parser.o \
./include/ffmpeg/libavcodec/h263dec.o \
./include/ffmpeg/libavcodec/h263dsp.o \
./include/ffmpeg/libavcodec/h264.o \
./include/ffmpeg/libavcodec/h264_cabac.o \
./include/ffmpeg/libavcodec/h264_cavlc.o \
./include/ffmpeg/libavcodec/h264_direct.o \
./include/ffmpeg/libavcodec/h264_loopfilter.o \
./include/ffmpeg/libavcodec/h264_mb.o \
./include/ffmpeg/libavcodec/h264_mb_template.o \
./include/ffmpeg/libavcodec/h264_mc_template.o \
./include/ffmpeg/libavcodec/h264_mp4toannexb_bsf.o \
./include/ffmpeg/libavcodec/h264_parser.o \
./include/ffmpeg/libavcodec/h264_picture.o \
./include/ffmpeg/libavcodec/h264_ps.o \
./include/ffmpeg/libavcodec/h264_refs.o \
./include/ffmpeg/libavcodec/h264_sei.o \
./include/ffmpeg/libavcodec/h264_slice.o \
./include/ffmpeg/libavcodec/h264addpx_template.o \
./include/ffmpeg/libavcodec/h264chroma.o \
./include/ffmpeg/libavcodec/h264chroma_template.o \
./include/ffmpeg/libavcodec/h264dsp.o \
./include/ffmpeg/libavcodec/h264dsp_template.o \
./include/ffmpeg/libavcodec/h264idct.o \
./include/ffmpeg/libavcodec/h264idct_template.o \
./include/ffmpeg/libavcodec/h264pred.o \
./include/ffmpeg/libavcodec/h264pred_template.o \
./include/ffmpeg/libavcodec/h264qpel.o \
./include/ffmpeg/libavcodec/h264qpel_template.o \
./include/ffmpeg/libavcodec/hevc.o \
./include/ffmpeg/libavcodec/hevc_cabac.o \
./include/ffmpeg/libavcodec/hevc_filter.o \
./include/ffmpeg/libavcodec/hevc_mvs.o \
./include/ffmpeg/libavcodec/hevc_parser.o \
./include/ffmpeg/libavcodec/hevc_ps.o \
./include/ffmpeg/libavcodec/hevc_refs.o \
./include/ffmpeg/libavcodec/hevc_sei.o \
./include/ffmpeg/libavcodec/hevcdsp.o \
./include/ffmpeg/libavcodec/hevcdsp_template.o \
./include/ffmpeg/libavcodec/hevcpred.o \
./include/ffmpeg/libavcodec/hevcpred_template.o \
./include/ffmpeg/libavcodec/hnm4video.o \
./include/ffmpeg/libavcodec/hpel_template.o \
./include/ffmpeg/libavcodec/hpeldsp.o \
./include/ffmpeg/libavcodec/huffman.o \
./include/ffmpeg/libavcodec/huffyuv.o \
./include/ffmpeg/libavcodec/huffyuvdec.o \
./include/ffmpeg/libavcodec/huffyuvdsp.o \
./include/ffmpeg/libavcodec/huffyuvenc.o \
./include/ffmpeg/libavcodec/huffyuvencdsp.o \
./include/ffmpeg/libavcodec/idcinvideo.o \
./include/ffmpeg/libavcodec/idctdsp.o \
./include/ffmpeg/libavcodec/iff.o \
./include/ffmpeg/libavcodec/iirfilter.o \
./include/ffmpeg/libavcodec/imc.o \
./include/ffmpeg/libavcodec/imgconvert.o \
./include/ffmpeg/libavcodec/imx_dump_header_bsf.o \
./include/ffmpeg/libavcodec/indeo2.o \
./include/ffmpeg/libavcodec/indeo3.o \
./include/ffmpeg/libavcodec/indeo4.o \
./include/ffmpeg/libavcodec/indeo5.o \
./include/ffmpeg/libavcodec/intelh263dec.o \
./include/ffmpeg/libavcodec/interplayvideo.o \
./include/ffmpeg/libavcodec/intrax8.o \
./include/ffmpeg/libavcodec/intrax8dsp.o \
./include/ffmpeg/libavcodec/ituh263dec.o \
./include/ffmpeg/libavcodec/ituh263enc.o \
./include/ffmpeg/libavcodec/ivi_common.o \
./include/ffmpeg/libavcodec/ivi_dsp.o \
./include/ffmpeg/libavcodec/j2kenc.o \
./include/ffmpeg/libavcodec/jacosubdec.o \
./include/ffmpeg/libavcodec/jfdctfst.o \
./include/ffmpeg/libavcodec/jfdctint.o \
./include/ffmpeg/libavcodec/jfdctint_template.o \
./include/ffmpeg/libavcodec/jpeg2000.o \
./include/ffmpeg/libavcodec/jpeg2000dec.o \
./include/ffmpeg/libavcodec/jpeg2000dwt.o \
./include/ffmpeg/libavcodec/jpegls.o \
./include/ffmpeg/libavcodec/jpeglsdec.o \
./include/ffmpeg/libavcodec/jpeglsenc.o \
./include/ffmpeg/libavcodec/jrevdct.o \
./include/ffmpeg/libavcodec/jvdec.o \
./include/ffmpeg/libavcodec/kbdwin.o \
./include/ffmpeg/libavcodec/kgv1dec.o \
./include/ffmpeg/libavcodec/kmvc.o \
./include/ffmpeg/libavcodec/lagarith.o \
./include/ffmpeg/libavcodec/lagarithrac.o \
./include/ffmpeg/libavcodec/latm_parser.o \
./include/ffmpeg/libavcodec/lcldec.o \
./include/ffmpeg/libavcodec/lclenc.o \
./include/ffmpeg/libavcodec/libaacplus.o \
./include/ffmpeg/libavcodec/libcelt_dec.o \
./include/ffmpeg/libavcodec/libfaac.o \
./include/ffmpeg/libavcodec/libfdk-aacdec.o \
./include/ffmpeg/libavcodec/libfdk-aacenc.o \
./include/ffmpeg/libavcodec/libgsm.o \
./include/ffmpeg/libavcodec/libilbc.o \
./include/ffmpeg/libavcodec/libmp3lame.o \
./include/ffmpeg/libavcodec/libopencore-amr.o \
./include/ffmpeg/libavcodec/libopenjpegdec.o \
./include/ffmpeg/libavcodec/libopenjpegenc.o \
./include/ffmpeg/libavcodec/libopus.o \
./include/ffmpeg/libavcodec/libopusdec.o \
./include/ffmpeg/libavcodec/libopusenc.o \
./include/ffmpeg/libavcodec/libschroedinger.o \
./include/ffmpeg/libavcodec/libschroedingerdec.o \
./include/ffmpeg/libavcodec/libschroedingerenc.o \
./include/ffmpeg/libavcodec/libshine.o \
./include/ffmpeg/libavcodec/libspeexdec.o \
./include/ffmpeg/libavcodec/libspeexenc.o \
./include/ffmpeg/libavcodec/libstagefright.o \
./include/ffmpeg/libavcodec/libtheoraenc.o \
./include/ffmpeg/libavcodec/libtwolame.o \
./include/ffmpeg/libavcodec/libutvideodec.o \
./include/ffmpeg/libavcodec/libutvideoenc.o \
./include/ffmpeg/libavcodec/libvo-aacenc.o \
./include/ffmpeg/libavcodec/libvo-amrwbenc.o \
./include/ffmpeg/libavcodec/libvorbisdec.o \
./include/ffmpeg/libavcodec/libvorbisenc.o \
./include/ffmpeg/libavcodec/libvpx.o \
./include/ffmpeg/libavcodec/libvpxdec.o \
./include/ffmpeg/libavcodec/libvpxenc.o \
./include/ffmpeg/libavcodec/libwavpackenc.o \
./include/ffmpeg/libavcodec/libwebpenc.o \
./include/ffmpeg/libavcodec/libx264.o \
./include/ffmpeg/libavcodec/libx265.o \
./include/ffmpeg/libavcodec/libxavs.o \
./include/ffmpeg/libavcodec/libxvid.o \
./include/ffmpeg/libavcodec/libxvid_rc.o \
./include/ffmpeg/libavcodec/libzvbi-teletextdec.o \
./include/ffmpeg/libavcodec/ljpegenc.o \
./include/ffmpeg/libavcodec/loco.o \
./include/ffmpeg/libavcodec/log2_tab.o \
./include/ffmpeg/libavcodec/lossless_audiodsp.o \
./include/ffmpeg/libavcodec/lossless_videodsp.o \
./include/ffmpeg/libavcodec/lpc.o \
./include/ffmpeg/libavcodec/lsp.o \
./include/ffmpeg/libavcodec/lzw.o \
./include/ffmpeg/libavcodec/lzwenc.o \
./include/ffmpeg/libavcodec/mace.o \
./include/ffmpeg/libavcodec/mathtables.o \
./include/ffmpeg/libavcodec/mdct_fixed.o \
./include/ffmpeg/libavcodec/mdct_fixed_32.o \
./include/ffmpeg/libavcodec/mdct_float.o \
./include/ffmpeg/libavcodec/mdct_template.o \
./include/ffmpeg/libavcodec/mdec.o \
./include/ffmpeg/libavcodec/metasound.o \
./include/ffmpeg/libavcodec/metasound_data.o \
./include/ffmpeg/libavcodec/microdvddec.o \
./include/ffmpeg/libavcodec/mimic.o \
./include/ffmpeg/libavcodec/mjpeg.o \
./include/ffmpeg/libavcodec/mjpeg2jpeg_bsf.o \
./include/ffmpeg/libavcodec/mjpeg_parser.o \
./include/ffmpeg/libavcodec/mjpega_dump_header_bsf.o \
./include/ffmpeg/libavcodec/mjpegbdec.o \
./include/ffmpeg/libavcodec/mjpegdec.o \
./include/ffmpeg/libavcodec/mjpegenc.o \
./include/ffmpeg/libavcodec/mjpegenc_common.o \
./include/ffmpeg/libavcodec/mlp.o \
./include/ffmpeg/libavcodec/mlp_parser.o \
./include/ffmpeg/libavcodec/mlpdec.o \
./include/ffmpeg/libavcodec/mlpdsp.o \
./include/ffmpeg/libavcodec/mmvideo.o \
./include/ffmpeg/libavcodec/motion-test.o \
./include/ffmpeg/libavcodec/motion_est.o \
./include/ffmpeg/libavcodec/motion_est_template.o \
./include/ffmpeg/libavcodec/motionpixels.o \
./include/ffmpeg/libavcodec/motionpixels_tablegen.o \
./include/ffmpeg/libavcodec/movsub_bsf.o \
./include/ffmpeg/libavcodec/movtextdec.o \
./include/ffmpeg/libavcodec/movtextenc.o \
./include/ffmpeg/libavcodec/mp3_header_decompress_bsf.o \
./include/ffmpeg/libavcodec/mpc.o \
./include/ffmpeg/libavcodec/mpc7.o \
./include/ffmpeg/libavcodec/mpc8.o \
./include/ffmpeg/libavcodec/mpeg12.o \
./include/ffmpeg/libavcodec/mpeg12data.o \
./include/ffmpeg/libavcodec/mpeg12dec.o \
./include/ffmpeg/libavcodec/mpeg12enc.o \
./include/ffmpeg/libavcodec/mpeg4audio.o \
./include/ffmpeg/libavcodec/mpeg4video.o \
./include/ffmpeg/libavcodec/mpeg4video_parser.o \
./include/ffmpeg/libavcodec/mpeg4videodec.o \
./include/ffmpeg/libavcodec/mpeg4videoenc.o \
./include/ffmpeg/libavcodec/mpeg_er.o \
./include/ffmpeg/libavcodec/mpegaudio.o \
./include/ffmpeg/libavcodec/mpegaudio_parser.o \
./include/ffmpeg/libavcodec/mpegaudio_tablegen.o \
./include/ffmpeg/libavcodec/mpegaudiodata.o \
./include/ffmpeg/libavcodec/mpegaudiodec_fixed.o \
./include/ffmpeg/libavcodec/mpegaudiodec_float.o \
./include/ffmpeg/libavcodec/mpegaudiodec_template.o \
./include/ffmpeg/libavcodec/mpegaudiodecheader.o \
./include/ffmpeg/libavcodec/mpegaudiodsp.o \
./include/ffmpeg/libavcodec/mpegaudiodsp_data.o \
./include/ffmpeg/libavcodec/mpegaudiodsp_fixed.o \
./include/ffmpeg/libavcodec/mpegaudiodsp_float.o \
./include/ffmpeg/libavcodec/mpegaudiodsp_template.o \
./include/ffmpeg/libavcodec/mpegaudioenc_fixed.o \
./include/ffmpeg/libavcodec/mpegaudioenc_float.o \
./include/ffmpeg/libavcodec/mpegaudioenc_template.o \
./include/ffmpeg/libavcodec/mpegutils.o \
./include/ffmpeg/libavcodec/mpegvideo.o \
./include/ffmpeg/libavcodec/mpegvideo_enc.o \
./include/ffmpeg/libavcodec/mpegvideo_motion.o \
./include/ffmpeg/libavcodec/mpegvideo_parser.o \
./include/ffmpeg/libavcodec/mpegvideo_xvmc.o \
./include/ffmpeg/libavcodec/mpegvideodsp.o \
./include/ffmpeg/libavcodec/mpegvideoencdsp.o \
./include/ffmpeg/libavcodec/mpl2dec.o \
./include/ffmpeg/libavcodec/mqc.o \
./include/ffmpeg/libavcodec/mqcdec.o \
./include/ffmpeg/libavcodec/mqcenc.o \
./include/ffmpeg/libavcodec/msgsmdec.o \
./include/ffmpeg/libavcodec/msmpeg4.o \
./include/ffmpeg/libavcodec/msmpeg4data.o \
./include/ffmpeg/libavcodec/msmpeg4dec.o \
./include/ffmpeg/libavcodec/msmpeg4enc.o \
./include/ffmpeg/libavcodec/msrle.o \
./include/ffmpeg/libavcodec/msrledec.o \
./include/ffmpeg/libavcodec/mss1.o \
./include/ffmpeg/libavcodec/mss12.o \
./include/ffmpeg/libavcodec/mss2.o \
./include/ffmpeg/libavcodec/mss2dsp.o \
./include/ffmpeg/libavcodec/mss3.o \
./include/ffmpeg/libavcodec/mss34dsp.o \
./include/ffmpeg/libavcodec/mss4.o \
./include/ffmpeg/libavcodec/msvideo1.o \
./include/ffmpeg/libavcodec/msvideo1enc.o \
./include/ffmpeg/libavcodec/mvcdec.o \
./include/ffmpeg/libavcodec/mxpegdec.o \
./include/ffmpeg/libavcodec/nellymoser.o \
./include/ffmpeg/libavcodec/nellymoserdec.o \
./include/ffmpeg/libavcodec/nellymoserenc.o \
./include/ffmpeg/libavcodec/noise_bsf.o \
./include/ffmpeg/libavcodec/nuv.o \
./include/ffmpeg/libavcodec/on2avc.o \
./include/ffmpeg/libavcodec/on2avcdata.o \
./include/ffmpeg/libavcodec/options.o \
./include/ffmpeg/libavcodec/opus.o \
./include/ffmpeg/libavcodec/opus_celt.o \
./include/ffmpeg/libavcodec/opus_imdct.o \
./include/ffmpeg/libavcodec/opus_parser.o \
./include/ffmpeg/libavcodec/opus_silk.o \
./include/ffmpeg/libavcodec/opusdec.o \
./include/ffmpeg/libavcodec/pafaudio.o \
./include/ffmpeg/libavcodec/pafvideo.o \
./include/ffmpeg/libavcodec/pamenc.o \
./include/ffmpeg/libavcodec/parser.o \
./include/ffmpeg/libavcodec/pcm-bluray.o \
./include/ffmpeg/libavcodec/pcm-dvd.o \
./include/ffmpeg/libavcodec/pcm.o \
./include/ffmpeg/libavcodec/pcm_tablegen.o \
./include/ffmpeg/libavcodec/pcx.o \
./include/ffmpeg/libavcodec/pcxenc.o \
./include/ffmpeg/libavcodec/pel_template.o \
./include/ffmpeg/libavcodec/pgssubdec.o \
./include/ffmpeg/libavcodec/pictordec.o \
./include/ffmpeg/libavcodec/pixblockdsp.o \
./include/ffmpeg/libavcodec/pixblockdsp_template.o \
./include/ffmpeg/libavcodec/png.o \
./include/ffmpeg/libavcodec/png_parser.o \
./include/ffmpeg/libavcodec/pngdec.o \
./include/ffmpeg/libavcodec/pngdsp.o \
./include/ffmpeg/libavcodec/pngenc.o \
./include/ffmpeg/libavcodec/pnm.o \
./include/ffmpeg/libavcodec/pnm_parser.o \
./include/ffmpeg/libavcodec/pnmdec.o \
./include/ffmpeg/libavcodec/pnmenc.o \
./include/ffmpeg/libavcodec/proresdata.o \
./include/ffmpeg/libavcodec/proresdec2.o \
./include/ffmpeg/libavcodec/proresdec_lgpl.o \
./include/ffmpeg/libavcodec/proresdsp.o \
./include/ffmpeg/libavcodec/proresenc_anatoliy.o \
./include/ffmpeg/libavcodec/proresenc_kostya.o \
./include/ffmpeg/libavcodec/psymodel.o \
./include/ffmpeg/libavcodec/pthread.o \
./include/ffmpeg/libavcodec/pthread_frame.o \
./include/ffmpeg/libavcodec/pthread_slice.o \
./include/ffmpeg/libavcodec/ptx.o \
./include/ffmpeg/libavcodec/qcelpdec.o \
./include/ffmpeg/libavcodec/qdm2.o \
./include/ffmpeg/libavcodec/qdm2_tablegen.o \
./include/ffmpeg/libavcodec/qdrw.o \
./include/ffmpeg/libavcodec/qpeg.o \
./include/ffmpeg/libavcodec/qpel_template.o \
./include/ffmpeg/libavcodec/qpeldsp.o \
./include/ffmpeg/libavcodec/qtrle.o \
./include/ffmpeg/libavcodec/qtrleenc.o \
./include/ffmpeg/libavcodec/r210dec.o \
./include/ffmpeg/libavcodec/r210enc.o \
./include/ffmpeg/libavcodec/ra144.o \
./include/ffmpeg/libavcodec/ra144dec.o \
./include/ffmpeg/libavcodec/ra144enc.o \
./include/ffmpeg/libavcodec/ra288.o \
./include/ffmpeg/libavcodec/ralf.o \
./include/ffmpeg/libavcodec/rangecoder.o \
./include/ffmpeg/libavcodec/ratecontrol.o \
./include/ffmpeg/libavcodec/raw.o \
./include/ffmpeg/libavcodec/rawdec.o \
./include/ffmpeg/libavcodec/rawenc.o \
./include/ffmpeg/libavcodec/rdft.o \
./include/ffmpeg/libavcodec/realtextdec.o \
./include/ffmpeg/libavcodec/remove_extradata_bsf.o \
./include/ffmpeg/libavcodec/resample.o \
./include/ffmpeg/libavcodec/resample2.o \
./include/ffmpeg/libavcodec/rl2.o \
./include/ffmpeg/libavcodec/rle.o \
./include/ffmpeg/libavcodec/roqaudioenc.o \
./include/ffmpeg/libavcodec/roqvideo.o \
./include/ffmpeg/libavcodec/roqvideodec.o \
./include/ffmpeg/libavcodec/roqvideoenc.o \
./include/ffmpeg/libavcodec/rpza.o \
./include/ffmpeg/libavcodec/rtjpeg.o \
./include/ffmpeg/libavcodec/rv10.o \
./include/ffmpeg/libavcodec/rv10enc.o \
./include/ffmpeg/libavcodec/rv20enc.o \
./include/ffmpeg/libavcodec/rv30.o \
./include/ffmpeg/libavcodec/rv30dsp.o \
./include/ffmpeg/libavcodec/rv34.o \
./include/ffmpeg/libavcodec/rv34_parser.o \
./include/ffmpeg/libavcodec/rv34dsp.o \
./include/ffmpeg/libavcodec/rv40.o \
./include/ffmpeg/libavcodec/rv40dsp.o \
./include/ffmpeg/libavcodec/s302m.o \
./include/ffmpeg/libavcodec/s302menc.o \
./include/ffmpeg/libavcodec/s3tc.o \
./include/ffmpeg/libavcodec/samidec.o \
./include/ffmpeg/libavcodec/sanm.o \
./include/ffmpeg/libavcodec/sbrdsp.o \
./include/ffmpeg/libavcodec/sgidec.o \
./include/ffmpeg/libavcodec/sgienc.o \
./include/ffmpeg/libavcodec/sgirledec.o \
./include/ffmpeg/libavcodec/shorten.o \
./include/ffmpeg/libavcodec/simple_idct.o \
./include/ffmpeg/libavcodec/simple_idct_template.o \
./include/ffmpeg/libavcodec/sinewin.o \
./include/ffmpeg/libavcodec/sinewin_tablegen.o \
./include/ffmpeg/libavcodec/sipr.o \
./include/ffmpeg/libavcodec/sipr16k.o \
./include/ffmpeg/libavcodec/smacker.o \
./include/ffmpeg/libavcodec/smc.o \
./include/ffmpeg/libavcodec/smvjpegdec.o \
./include/ffmpeg/libavcodec/snow.o \
./include/ffmpeg/libavcodec/snow_dwt.o \
./include/ffmpeg/libavcodec/snowdec.o \
./include/ffmpeg/libavcodec/snowenc.o \
./include/ffmpeg/libavcodec/sonic.o \
./include/ffmpeg/libavcodec/sp5xdec.o \
./include/ffmpeg/libavcodec/srtdec.o \
./include/ffmpeg/libavcodec/srtenc.o \
./include/ffmpeg/libavcodec/startcode.o \
./include/ffmpeg/libavcodec/subviewerdec.o \
./include/ffmpeg/libavcodec/sunrast.o \
./include/ffmpeg/libavcodec/sunrastenc.o \
./include/ffmpeg/libavcodec/svq1.o \
./include/ffmpeg/libavcodec/svq13.o \
./include/ffmpeg/libavcodec/svq1dec.o \
./include/ffmpeg/libavcodec/svq1enc.o \
./include/ffmpeg/libavcodec/svq3.o \
./include/ffmpeg/libavcodec/synth_filter.o \
./include/ffmpeg/libavcodec/tak.o \
./include/ffmpeg/libavcodec/tak_parser.o \
./include/ffmpeg/libavcodec/takdec.o \
./include/ffmpeg/libavcodec/targa.o \
./include/ffmpeg/libavcodec/targa_y216dec.o \
./include/ffmpeg/libavcodec/targaenc.o \
./include/ffmpeg/libavcodec/textdec.o \
./include/ffmpeg/libavcodec/tiertexseqv.o \
./include/ffmpeg/libavcodec/tiff.o \
./include/ffmpeg/libavcodec/tiff_common.o \
./include/ffmpeg/libavcodec/tiff_data.o \
./include/ffmpeg/libavcodec/tiffenc.o \
./include/ffmpeg/libavcodec/tmv.o \
./include/ffmpeg/libavcodec/tpeldsp.o \
./include/ffmpeg/libavcodec/truemotion1.o \
./include/ffmpeg/libavcodec/truemotion2.o \
./include/ffmpeg/libavcodec/truespeech.o \
./include/ffmpeg/libavcodec/tscc.o \
./include/ffmpeg/libavcodec/tscc2.o \
./include/ffmpeg/libavcodec/tta.o \
./include/ffmpeg/libavcodec/ttadata.o \
./include/ffmpeg/libavcodec/ttadsp.o \
./include/ffmpeg/libavcodec/ttaenc.o \
./include/ffmpeg/libavcodec/twinvq.o \
./include/ffmpeg/libavcodec/twinvqdec.o \
./include/ffmpeg/libavcodec/txd.o \
./include/ffmpeg/libavcodec/ulti.o \
./include/ffmpeg/libavcodec/utils.o \
./include/ffmpeg/libavcodec/utvideo.o \
./include/ffmpeg/libavcodec/utvideodec.o \
./include/ffmpeg/libavcodec/utvideoenc.o \
./include/ffmpeg/libavcodec/v210dec.o \
./include/ffmpeg/libavcodec/v210enc.o \
./include/ffmpeg/libavcodec/v210x.o \
./include/ffmpeg/libavcodec/v308dec.o \
./include/ffmpeg/libavcodec/v308enc.o \
./include/ffmpeg/libavcodec/v408dec.o \
./include/ffmpeg/libavcodec/v408enc.o \
./include/ffmpeg/libavcodec/v410dec.o \
./include/ffmpeg/libavcodec/v410enc.o \
./include/ffmpeg/libavcodec/vaapi.o \
./include/ffmpeg/libavcodec/vaapi_h264.o \
./include/ffmpeg/libavcodec/vaapi_mpeg.o \
./include/ffmpeg/libavcodec/vaapi_mpeg2.o \
./include/ffmpeg/libavcodec/vaapi_mpeg4.o \
./include/ffmpeg/libavcodec/vaapi_vc1.o \
./include/ffmpeg/libavcodec/vb.o \
./include/ffmpeg/libavcodec/vble.o \
./include/ffmpeg/libavcodec/vc1.o \
./include/ffmpeg/libavcodec/vc1_parser.o \
./include/ffmpeg/libavcodec/vc1data.o \
./include/ffmpeg/libavcodec/vc1dec.o \
./include/ffmpeg/libavcodec/vc1dsp.o \
./include/ffmpeg/libavcodec/vcr1.o \
./include/ffmpeg/libavcodec/vda.o \
./include/ffmpeg/libavcodec/vda_h264.o \
./include/ffmpeg/libavcodec/vda_h264_dec.o \
./include/ffmpeg/libavcodec/vdpau.o \
./include/ffmpeg/libavcodec/vdpau_h264.o \
./include/ffmpeg/libavcodec/vdpau_mpeg12.o \
./include/ffmpeg/libavcodec/vdpau_mpeg4.o \
./include/ffmpeg/libavcodec/vdpau_vc1.o \
./include/ffmpeg/libavcodec/videodsp.o \
./include/ffmpeg/libavcodec/videodsp_template.o \
./include/ffmpeg/libavcodec/vima.o \
./include/ffmpeg/libavcodec/vmdaudio.o \
./include/ffmpeg/libavcodec/vmdvideo.o \
./include/ffmpeg/libavcodec/vmnc.o \
./include/ffmpeg/libavcodec/vorbis.o \
./include/ffmpeg/libavcodec/vorbis_data.o \
./include/ffmpeg/libavcodec/vorbis_parser.o \
./include/ffmpeg/libavcodec/vorbisdec.o \
./include/ffmpeg/libavcodec/vorbisdsp.o \
./include/ffmpeg/libavcodec/vorbisenc.o \
./include/ffmpeg/libavcodec/vp3.o \
./include/ffmpeg/libavcodec/vp3_parser.o \
./include/ffmpeg/libavcodec/vp3dsp.o \
./include/ffmpeg/libavcodec/vp5.o \
./include/ffmpeg/libavcodec/vp56.o \
./include/ffmpeg/libavcodec/vp56data.o \
./include/ffmpeg/libavcodec/vp56dsp.o \
./include/ffmpeg/libavcodec/vp56rac.o \
./include/ffmpeg/libavcodec/vp6.o \
./include/ffmpeg/libavcodec/vp6dsp.o \
./include/ffmpeg/libavcodec/vp8.o \
./include/ffmpeg/libavcodec/vp8_parser.o \
./include/ffmpeg/libavcodec/vp8dsp.o \
./include/ffmpeg/libavcodec/vp9.o \
./include/ffmpeg/libavcodec/vp9_parser.o \
./include/ffmpeg/libavcodec/vp9dsp.o \
./include/ffmpeg/libavcodec/vqavideo.o \
./include/ffmpeg/libavcodec/wavpack.o \
./include/ffmpeg/libavcodec/wavpackenc.o \
./include/ffmpeg/libavcodec/webp.o \
./include/ffmpeg/libavcodec/webvttdec.o \
./include/ffmpeg/libavcodec/webvttenc.o \
./include/ffmpeg/libavcodec/wma.o \
./include/ffmpeg/libavcodec/wma_common.o \
./include/ffmpeg/libavcodec/wmadec.o \
./include/ffmpeg/libavcodec/wmaenc.o \
./include/ffmpeg/libavcodec/wmalosslessdec.o \
./include/ffmpeg/libavcodec/wmaprodec.o \
./include/ffmpeg/libavcodec/wmavoice.o \
./include/ffmpeg/libavcodec/wmv2.o \
./include/ffmpeg/libavcodec/wmv2dec.o \
./include/ffmpeg/libavcodec/wmv2dsp.o \
./include/ffmpeg/libavcodec/wmv2enc.o \
./include/ffmpeg/libavcodec/wnv1.o \
./include/ffmpeg/libavcodec/ws-snd1.o \
./include/ffmpeg/libavcodec/xan.o \
./include/ffmpeg/libavcodec/xbmdec.o \
./include/ffmpeg/libavcodec/xbmenc.o \
./include/ffmpeg/libavcodec/xface.o \
./include/ffmpeg/libavcodec/xfacedec.o \
./include/ffmpeg/libavcodec/xfaceenc.o \
./include/ffmpeg/libavcodec/xiph.o \
./include/ffmpeg/libavcodec/xl.o \
./include/ffmpeg/libavcodec/xsubdec.o \
./include/ffmpeg/libavcodec/xsubenc.o \
./include/ffmpeg/libavcodec/xwddec.o \
./include/ffmpeg/libavcodec/xwdenc.o \
./include/ffmpeg/libavcodec/xxan.o \
./include/ffmpeg/libavcodec/y41pdec.o \
./include/ffmpeg/libavcodec/y41penc.o \
./include/ffmpeg/libavcodec/yop.o \
./include/ffmpeg/libavcodec/yuv4dec.o \
./include/ffmpeg/libavcodec/yuv4enc.o \
./include/ffmpeg/libavcodec/zerocodec.o \
./include/ffmpeg/libavcodec/zmbv.o \
./include/ffmpeg/libavcodec/zmbvenc.o 

C_DEPS += \
./include/ffmpeg/libavcodec/012v.d \
./include/ffmpeg/libavcodec/4xm.d \
./include/ffmpeg/libavcodec/8bps.d \
./include/ffmpeg/libavcodec/8svx.d \
./include/ffmpeg/libavcodec/a64multienc.d \
./include/ffmpeg/libavcodec/aac_ac3_parser.d \
./include/ffmpeg/libavcodec/aac_adtstoasc_bsf.d \
./include/ffmpeg/libavcodec/aac_parser.d \
./include/ffmpeg/libavcodec/aac_tablegen.d \
./include/ffmpeg/libavcodec/aacadtsdec.d \
./include/ffmpeg/libavcodec/aaccoder.d \
./include/ffmpeg/libavcodec/aacdec.d \
./include/ffmpeg/libavcodec/aacenc.d \
./include/ffmpeg/libavcodec/aacps.d \
./include/ffmpeg/libavcodec/aacps_tablegen.d \
./include/ffmpeg/libavcodec/aacpsdata.d \
./include/ffmpeg/libavcodec/aacpsdsp.d \
./include/ffmpeg/libavcodec/aacpsy.d \
./include/ffmpeg/libavcodec/aacsbr.d \
./include/ffmpeg/libavcodec/aactab.d \
./include/ffmpeg/libavcodec/aandcttab.d \
./include/ffmpeg/libavcodec/aasc.d \
./include/ffmpeg/libavcodec/ac3.d \
./include/ffmpeg/libavcodec/ac3_parser.d \
./include/ffmpeg/libavcodec/ac3dec.d \
./include/ffmpeg/libavcodec/ac3dec_data.d \
./include/ffmpeg/libavcodec/ac3dec_fixed.d \
./include/ffmpeg/libavcodec/ac3dec_float.d \
./include/ffmpeg/libavcodec/ac3dsp.d \
./include/ffmpeg/libavcodec/ac3enc.d \
./include/ffmpeg/libavcodec/ac3enc_fixed.d \
./include/ffmpeg/libavcodec/ac3enc_float.d \
./include/ffmpeg/libavcodec/ac3enc_opts_template.d \
./include/ffmpeg/libavcodec/ac3enc_template.d \
./include/ffmpeg/libavcodec/ac3tab.d \
./include/ffmpeg/libavcodec/acelp_filters.d \
./include/ffmpeg/libavcodec/acelp_pitch_delay.d \
./include/ffmpeg/libavcodec/acelp_vectors.d \
./include/ffmpeg/libavcodec/adpcm.d \
./include/ffmpeg/libavcodec/adpcm_data.d \
./include/ffmpeg/libavcodec/adpcmenc.d \
./include/ffmpeg/libavcodec/adx.d \
./include/ffmpeg/libavcodec/adx_parser.d \
./include/ffmpeg/libavcodec/adxdec.d \
./include/ffmpeg/libavcodec/adxenc.d \
./include/ffmpeg/libavcodec/aic.d \
./include/ffmpeg/libavcodec/alac.d \
./include/ffmpeg/libavcodec/alac_data.d \
./include/ffmpeg/libavcodec/alacenc.d \
./include/ffmpeg/libavcodec/aliaspixdec.d \
./include/ffmpeg/libavcodec/aliaspixenc.d \
./include/ffmpeg/libavcodec/allcodecs.d \
./include/ffmpeg/libavcodec/alsdec.d \
./include/ffmpeg/libavcodec/amrnbdec.d \
./include/ffmpeg/libavcodec/amrwbdec.d \
./include/ffmpeg/libavcodec/anm.d \
./include/ffmpeg/libavcodec/ansi.d \
./include/ffmpeg/libavcodec/apedec.d \
./include/ffmpeg/libavcodec/ass.d \
./include/ffmpeg/libavcodec/ass_split.d \
./include/ffmpeg/libavcodec/assdec.d \
./include/ffmpeg/libavcodec/assenc.d \
./include/ffmpeg/libavcodec/asv.d \
./include/ffmpeg/libavcodec/asvdec.d \
./include/ffmpeg/libavcodec/asvenc.d \
./include/ffmpeg/libavcodec/atrac.d \
./include/ffmpeg/libavcodec/atrac1.d \
./include/ffmpeg/libavcodec/atrac3.d \
./include/ffmpeg/libavcodec/atrac3plus.d \
./include/ffmpeg/libavcodec/atrac3plusdec.d \
./include/ffmpeg/libavcodec/atrac3plusdsp.d \
./include/ffmpeg/libavcodec/audio_frame_queue.d \
./include/ffmpeg/libavcodec/audioconvert.d \
./include/ffmpeg/libavcodec/audiodsp.d \
./include/ffmpeg/libavcodec/aura.d \
./include/ffmpeg/libavcodec/avfft.d \
./include/ffmpeg/libavcodec/avpacket.d \
./include/ffmpeg/libavcodec/avpicture.d \
./include/ffmpeg/libavcodec/avrndec.d \
./include/ffmpeg/libavcodec/avs.d \
./include/ffmpeg/libavcodec/avuidec.d \
./include/ffmpeg/libavcodec/avuienc.d \
./include/ffmpeg/libavcodec/bethsoftvideo.d \
./include/ffmpeg/libavcodec/bfi.d \
./include/ffmpeg/libavcodec/bgmc.d \
./include/ffmpeg/libavcodec/bink.d \
./include/ffmpeg/libavcodec/binkaudio.d \
./include/ffmpeg/libavcodec/binkdsp.d \
./include/ffmpeg/libavcodec/bintext.d \
./include/ffmpeg/libavcodec/bit_depth_template.d \
./include/ffmpeg/libavcodec/bitstream.d \
./include/ffmpeg/libavcodec/bitstream_filter.d \
./include/ffmpeg/libavcodec/blockdsp.d \
./include/ffmpeg/libavcodec/bmp.d \
./include/ffmpeg/libavcodec/bmp_parser.d \
./include/ffmpeg/libavcodec/bmpenc.d \
./include/ffmpeg/libavcodec/bmvaudio.d \
./include/ffmpeg/libavcodec/bmvvideo.d \
./include/ffmpeg/libavcodec/brenderpix.d \
./include/ffmpeg/libavcodec/bswapdsp.d \
./include/ffmpeg/libavcodec/c93.d \
./include/ffmpeg/libavcodec/cabac.d \
./include/ffmpeg/libavcodec/cavs.d \
./include/ffmpeg/libavcodec/cavs_parser.d \
./include/ffmpeg/libavcodec/cavsdata.d \
./include/ffmpeg/libavcodec/cavsdec.d \
./include/ffmpeg/libavcodec/cavsdsp.d \
./include/ffmpeg/libavcodec/cbrt_tablegen.d \
./include/ffmpeg/libavcodec/cdgraphics.d \
./include/ffmpeg/libavcodec/cdxl.d \
./include/ffmpeg/libavcodec/celp_filters.d \
./include/ffmpeg/libavcodec/celp_math.d \
./include/ffmpeg/libavcodec/cga_data.d \
./include/ffmpeg/libavcodec/chomp_bsf.d \
./include/ffmpeg/libavcodec/cinepak.d \
./include/ffmpeg/libavcodec/cinepakenc.d \
./include/ffmpeg/libavcodec/cljrdec.d \
./include/ffmpeg/libavcodec/cljrenc.d \
./include/ffmpeg/libavcodec/cllc.d \
./include/ffmpeg/libavcodec/cngdec.d \
./include/ffmpeg/libavcodec/cngenc.d \
./include/ffmpeg/libavcodec/codec_desc.d \
./include/ffmpeg/libavcodec/cook.d \
./include/ffmpeg/libavcodec/cook_parser.d \
./include/ffmpeg/libavcodec/cos_tablegen.d \
./include/ffmpeg/libavcodec/cpia.d \
./include/ffmpeg/libavcodec/crystalhd.d \
./include/ffmpeg/libavcodec/cscd.d \
./include/ffmpeg/libavcodec/cyuv.d \
./include/ffmpeg/libavcodec/dca.d \
./include/ffmpeg/libavcodec/dca_parser.d \
./include/ffmpeg/libavcodec/dcadec.d \
./include/ffmpeg/libavcodec/dcadsp.d \
./include/ffmpeg/libavcodec/dcaenc.d \
./include/ffmpeg/libavcodec/dct-test.d \
./include/ffmpeg/libavcodec/dct.d \
./include/ffmpeg/libavcodec/dct32_fixed.d \
./include/ffmpeg/libavcodec/dct32_float.d \
./include/ffmpeg/libavcodec/dct32_template.d \
./include/ffmpeg/libavcodec/dctref.d \
./include/ffmpeg/libavcodec/dfa.d \
./include/ffmpeg/libavcodec/dirac.d \
./include/ffmpeg/libavcodec/dirac_arith.d \
./include/ffmpeg/libavcodec/dirac_dwt.d \
./include/ffmpeg/libavcodec/dirac_parser.d \
./include/ffmpeg/libavcodec/diracdec.d \
./include/ffmpeg/libavcodec/diracdsp.d \
./include/ffmpeg/libavcodec/dnxhd_parser.d \
./include/ffmpeg/libavcodec/dnxhddata.d \
./include/ffmpeg/libavcodec/dnxhddec.d \
./include/ffmpeg/libavcodec/dnxhdenc.d \
./include/ffmpeg/libavcodec/dpcm.d \
./include/ffmpeg/libavcodec/dpx.d \
./include/ffmpeg/libavcodec/dpx_parser.d \
./include/ffmpeg/libavcodec/dpxenc.d \
./include/ffmpeg/libavcodec/dsd_tablegen.d \
./include/ffmpeg/libavcodec/dsddec.d \
./include/ffmpeg/libavcodec/dsicinaudio.d \
./include/ffmpeg/libavcodec/dsicinvideo.d \
./include/ffmpeg/libavcodec/dsputil.d \
./include/ffmpeg/libavcodec/dump_extradata_bsf.d \
./include/ffmpeg/libavcodec/dv.d \
./include/ffmpeg/libavcodec/dv_profile.d \
./include/ffmpeg/libavcodec/dv_tablegen.d \
./include/ffmpeg/libavcodec/dvbsub.d \
./include/ffmpeg/libavcodec/dvbsub_parser.d \
./include/ffmpeg/libavcodec/dvbsubdec.d \
./include/ffmpeg/libavcodec/dvd_nav_parser.d \
./include/ffmpeg/libavcodec/dvdata.d \
./include/ffmpeg/libavcodec/dvdec.d \
./include/ffmpeg/libavcodec/dvdsub_parser.d \
./include/ffmpeg/libavcodec/dvdsubdec.d \
./include/ffmpeg/libavcodec/dvdsubenc.d \
./include/ffmpeg/libavcodec/dvenc.d \
./include/ffmpeg/libavcodec/dxa.d \
./include/ffmpeg/libavcodec/dxtory.d \
./include/ffmpeg/libavcodec/dxva2.d \
./include/ffmpeg/libavcodec/dxva2_h264.d \
./include/ffmpeg/libavcodec/dxva2_mpeg2.d \
./include/ffmpeg/libavcodec/dxva2_vc1.d \
./include/ffmpeg/libavcodec/eac3_data.d \
./include/ffmpeg/libavcodec/eac3dec.d \
./include/ffmpeg/libavcodec/eac3enc.d \
./include/ffmpeg/libavcodec/eacmv.d \
./include/ffmpeg/libavcodec/eaidct.d \
./include/ffmpeg/libavcodec/eamad.d \
./include/ffmpeg/libavcodec/eatgq.d \
./include/ffmpeg/libavcodec/eatgv.d \
./include/ffmpeg/libavcodec/eatqi.d \
./include/ffmpeg/libavcodec/elbg.d \
./include/ffmpeg/libavcodec/error_resilience.d \
./include/ffmpeg/libavcodec/escape124.d \
./include/ffmpeg/libavcodec/escape130.d \
./include/ffmpeg/libavcodec/evrcdec.d \
./include/ffmpeg/libavcodec/exif.d \
./include/ffmpeg/libavcodec/exr.d \
./include/ffmpeg/libavcodec/faandct.d \
./include/ffmpeg/libavcodec/faanidct.d \
./include/ffmpeg/libavcodec/faxcompr.d \
./include/ffmpeg/libavcodec/fdctdsp.d \
./include/ffmpeg/libavcodec/fft-fixed-test.d \
./include/ffmpeg/libavcodec/fft-fixed32-test.d \
./include/ffmpeg/libavcodec/fft-test.d \
./include/ffmpeg/libavcodec/fft_fixed.d \
./include/ffmpeg/libavcodec/fft_fixed_32.d \
./include/ffmpeg/libavcodec/fft_float.d \
./include/ffmpeg/libavcodec/fft_init_table.d \
./include/ffmpeg/libavcodec/fft_template.d \
./include/ffmpeg/libavcodec/ffv1.d \
./include/ffmpeg/libavcodec/ffv1dec.d \
./include/ffmpeg/libavcodec/ffv1enc.d \
./include/ffmpeg/libavcodec/ffwavesynth.d \
./include/ffmpeg/libavcodec/fic.d \
./include/ffmpeg/libavcodec/file_open.d \
./include/ffmpeg/libavcodec/flac.d \
./include/ffmpeg/libavcodec/flac_parser.d \
./include/ffmpeg/libavcodec/flacdata.d \
./include/ffmpeg/libavcodec/flacdec.d \
./include/ffmpeg/libavcodec/flacdsp.d \
./include/ffmpeg/libavcodec/flacdsp_lpc_template.d \
./include/ffmpeg/libavcodec/flacdsp_template.d \
./include/ffmpeg/libavcodec/flacenc.d \
./include/ffmpeg/libavcodec/flashsv.d \
./include/ffmpeg/libavcodec/flashsv2enc.d \
./include/ffmpeg/libavcodec/flashsvenc.d \
./include/ffmpeg/libavcodec/flicvideo.d \
./include/ffmpeg/libavcodec/flvdec.d \
./include/ffmpeg/libavcodec/flvenc.d \
./include/ffmpeg/libavcodec/fmtconvert.d \
./include/ffmpeg/libavcodec/frame_thread_encoder.d \
./include/ffmpeg/libavcodec/fraps.d \
./include/ffmpeg/libavcodec/frwu.d \
./include/ffmpeg/libavcodec/g2meet.d \
./include/ffmpeg/libavcodec/g722.d \
./include/ffmpeg/libavcodec/g722dec.d \
./include/ffmpeg/libavcodec/g722enc.d \
./include/ffmpeg/libavcodec/g723_1.d \
./include/ffmpeg/libavcodec/g726.d \
./include/ffmpeg/libavcodec/g729dec.d \
./include/ffmpeg/libavcodec/g729postfilter.d \
./include/ffmpeg/libavcodec/gif.d \
./include/ffmpeg/libavcodec/gifdec.d \
./include/ffmpeg/libavcodec/golomb-test.d \
./include/ffmpeg/libavcodec/golomb.d \
./include/ffmpeg/libavcodec/gsm_parser.d \
./include/ffmpeg/libavcodec/gsmdec.d \
./include/ffmpeg/libavcodec/gsmdec_data.d \
./include/ffmpeg/libavcodec/gsmdec_template.d \
./include/ffmpeg/libavcodec/h261.d \
./include/ffmpeg/libavcodec/h261_parser.d \
./include/ffmpeg/libavcodec/h261data.d \
./include/ffmpeg/libavcodec/h261dec.d \
./include/ffmpeg/libavcodec/h261enc.d \
./include/ffmpeg/libavcodec/h263.d \
./include/ffmpeg/libavcodec/h263_parser.d \
./include/ffmpeg/libavcodec/h263dec.d \
./include/ffmpeg/libavcodec/h263dsp.d \
./include/ffmpeg/libavcodec/h264.d \
./include/ffmpeg/libavcodec/h264_cabac.d \
./include/ffmpeg/libavcodec/h264_cavlc.d \
./include/ffmpeg/libavcodec/h264_direct.d \
./include/ffmpeg/libavcodec/h264_loopfilter.d \
./include/ffmpeg/libavcodec/h264_mb.d \
./include/ffmpeg/libavcodec/h264_mb_template.d \
./include/ffmpeg/libavcodec/h264_mc_template.d \
./include/ffmpeg/libavcodec/h264_mp4toannexb_bsf.d \
./include/ffmpeg/libavcodec/h264_parser.d \
./include/ffmpeg/libavcodec/h264_picture.d \
./include/ffmpeg/libavcodec/h264_ps.d \
./include/ffmpeg/libavcodec/h264_refs.d \
./include/ffmpeg/libavcodec/h264_sei.d \
./include/ffmpeg/libavcodec/h264_slice.d \
./include/ffmpeg/libavcodec/h264addpx_template.d \
./include/ffmpeg/libavcodec/h264chroma.d \
./include/ffmpeg/libavcodec/h264chroma_template.d \
./include/ffmpeg/libavcodec/h264dsp.d \
./include/ffmpeg/libavcodec/h264dsp_template.d \
./include/ffmpeg/libavcodec/h264idct.d \
./include/ffmpeg/libavcodec/h264idct_template.d \
./include/ffmpeg/libavcodec/h264pred.d \
./include/ffmpeg/libavcodec/h264pred_template.d \
./include/ffmpeg/libavcodec/h264qpel.d \
./include/ffmpeg/libavcodec/h264qpel_template.d \
./include/ffmpeg/libavcodec/hevc.d \
./include/ffmpeg/libavcodec/hevc_cabac.d \
./include/ffmpeg/libavcodec/hevc_filter.d \
./include/ffmpeg/libavcodec/hevc_mvs.d \
./include/ffmpeg/libavcodec/hevc_parser.d \
./include/ffmpeg/libavcodec/hevc_ps.d \
./include/ffmpeg/libavcodec/hevc_refs.d \
./include/ffmpeg/libavcodec/hevc_sei.d \
./include/ffmpeg/libavcodec/hevcdsp.d \
./include/ffmpeg/libavcodec/hevcdsp_template.d \
./include/ffmpeg/libavcodec/hevcpred.d \
./include/ffmpeg/libavcodec/hevcpred_template.d \
./include/ffmpeg/libavcodec/hnm4video.d \
./include/ffmpeg/libavcodec/hpel_template.d \
./include/ffmpeg/libavcodec/hpeldsp.d \
./include/ffmpeg/libavcodec/huffman.d \
./include/ffmpeg/libavcodec/huffyuv.d \
./include/ffmpeg/libavcodec/huffyuvdec.d \
./include/ffmpeg/libavcodec/huffyuvdsp.d \
./include/ffmpeg/libavcodec/huffyuvenc.d \
./include/ffmpeg/libavcodec/huffyuvencdsp.d \
./include/ffmpeg/libavcodec/idcinvideo.d \
./include/ffmpeg/libavcodec/idctdsp.d \
./include/ffmpeg/libavcodec/iff.d \
./include/ffmpeg/libavcodec/iirfilter.d \
./include/ffmpeg/libavcodec/imc.d \
./include/ffmpeg/libavcodec/imgconvert.d \
./include/ffmpeg/libavcodec/imx_dump_header_bsf.d \
./include/ffmpeg/libavcodec/indeo2.d \
./include/ffmpeg/libavcodec/indeo3.d \
./include/ffmpeg/libavcodec/indeo4.d \
./include/ffmpeg/libavcodec/indeo5.d \
./include/ffmpeg/libavcodec/intelh263dec.d \
./include/ffmpeg/libavcodec/interplayvideo.d \
./include/ffmpeg/libavcodec/intrax8.d \
./include/ffmpeg/libavcodec/intrax8dsp.d \
./include/ffmpeg/libavcodec/ituh263dec.d \
./include/ffmpeg/libavcodec/ituh263enc.d \
./include/ffmpeg/libavcodec/ivi_common.d \
./include/ffmpeg/libavcodec/ivi_dsp.d \
./include/ffmpeg/libavcodec/j2kenc.d \
./include/ffmpeg/libavcodec/jacosubdec.d \
./include/ffmpeg/libavcodec/jfdctfst.d \
./include/ffmpeg/libavcodec/jfdctint.d \
./include/ffmpeg/libavcodec/jfdctint_template.d \
./include/ffmpeg/libavcodec/jpeg2000.d \
./include/ffmpeg/libavcodec/jpeg2000dec.d \
./include/ffmpeg/libavcodec/jpeg2000dwt.d \
./include/ffmpeg/libavcodec/jpegls.d \
./include/ffmpeg/libavcodec/jpeglsdec.d \
./include/ffmpeg/libavcodec/jpeglsenc.d \
./include/ffmpeg/libavcodec/jrevdct.d \
./include/ffmpeg/libavcodec/jvdec.d \
./include/ffmpeg/libavcodec/kbdwin.d \
./include/ffmpeg/libavcodec/kgv1dec.d \
./include/ffmpeg/libavcodec/kmvc.d \
./include/ffmpeg/libavcodec/lagarith.d \
./include/ffmpeg/libavcodec/lagarithrac.d \
./include/ffmpeg/libavcodec/latm_parser.d \
./include/ffmpeg/libavcodec/lcldec.d \
./include/ffmpeg/libavcodec/lclenc.d \
./include/ffmpeg/libavcodec/libaacplus.d \
./include/ffmpeg/libavcodec/libcelt_dec.d \
./include/ffmpeg/libavcodec/libfaac.d \
./include/ffmpeg/libavcodec/libfdk-aacdec.d \
./include/ffmpeg/libavcodec/libfdk-aacenc.d \
./include/ffmpeg/libavcodec/libgsm.d \
./include/ffmpeg/libavcodec/libilbc.d \
./include/ffmpeg/libavcodec/libmp3lame.d \
./include/ffmpeg/libavcodec/libopencore-amr.d \
./include/ffmpeg/libavcodec/libopenjpegdec.d \
./include/ffmpeg/libavcodec/libopenjpegenc.d \
./include/ffmpeg/libavcodec/libopus.d \
./include/ffmpeg/libavcodec/libopusdec.d \
./include/ffmpeg/libavcodec/libopusenc.d \
./include/ffmpeg/libavcodec/libschroedinger.d \
./include/ffmpeg/libavcodec/libschroedingerdec.d \
./include/ffmpeg/libavcodec/libschroedingerenc.d \
./include/ffmpeg/libavcodec/libshine.d \
./include/ffmpeg/libavcodec/libspeexdec.d \
./include/ffmpeg/libavcodec/libspeexenc.d \
./include/ffmpeg/libavcodec/libtheoraenc.d \
./include/ffmpeg/libavcodec/libtwolame.d \
./include/ffmpeg/libavcodec/libvo-aacenc.d \
./include/ffmpeg/libavcodec/libvo-amrwbenc.d \
./include/ffmpeg/libavcodec/libvorbisdec.d \
./include/ffmpeg/libavcodec/libvorbisenc.d \
./include/ffmpeg/libavcodec/libvpx.d \
./include/ffmpeg/libavcodec/libvpxdec.d \
./include/ffmpeg/libavcodec/libvpxenc.d \
./include/ffmpeg/libavcodec/libwavpackenc.d \
./include/ffmpeg/libavcodec/libwebpenc.d \
./include/ffmpeg/libavcodec/libx264.d \
./include/ffmpeg/libavcodec/libx265.d \
./include/ffmpeg/libavcodec/libxavs.d \
./include/ffmpeg/libavcodec/libxvid.d \
./include/ffmpeg/libavcodec/libxvid_rc.d \
./include/ffmpeg/libavcodec/libzvbi-teletextdec.d \
./include/ffmpeg/libavcodec/ljpegenc.d \
./include/ffmpeg/libavcodec/loco.d \
./include/ffmpeg/libavcodec/log2_tab.d \
./include/ffmpeg/libavcodec/lossless_audiodsp.d \
./include/ffmpeg/libavcodec/lossless_videodsp.d \
./include/ffmpeg/libavcodec/lpc.d \
./include/ffmpeg/libavcodec/lsp.d \
./include/ffmpeg/libavcodec/lzw.d \
./include/ffmpeg/libavcodec/lzwenc.d \
./include/ffmpeg/libavcodec/mace.d \
./include/ffmpeg/libavcodec/mathtables.d \
./include/ffmpeg/libavcodec/mdct_fixed.d \
./include/ffmpeg/libavcodec/mdct_fixed_32.d \
./include/ffmpeg/libavcodec/mdct_float.d \
./include/ffmpeg/libavcodec/mdct_template.d \
./include/ffmpeg/libavcodec/mdec.d \
./include/ffmpeg/libavcodec/metasound.d \
./include/ffmpeg/libavcodec/metasound_data.d \
./include/ffmpeg/libavcodec/microdvddec.d \
./include/ffmpeg/libavcodec/mimic.d \
./include/ffmpeg/libavcodec/mjpeg.d \
./include/ffmpeg/libavcodec/mjpeg2jpeg_bsf.d \
./include/ffmpeg/libavcodec/mjpeg_parser.d \
./include/ffmpeg/libavcodec/mjpega_dump_header_bsf.d \
./include/ffmpeg/libavcodec/mjpegbdec.d \
./include/ffmpeg/libavcodec/mjpegdec.d \
./include/ffmpeg/libavcodec/mjpegenc.d \
./include/ffmpeg/libavcodec/mjpegenc_common.d \
./include/ffmpeg/libavcodec/mlp.d \
./include/ffmpeg/libavcodec/mlp_parser.d \
./include/ffmpeg/libavcodec/mlpdec.d \
./include/ffmpeg/libavcodec/mlpdsp.d \
./include/ffmpeg/libavcodec/mmvideo.d \
./include/ffmpeg/libavcodec/motion-test.d \
./include/ffmpeg/libavcodec/motion_est.d \
./include/ffmpeg/libavcodec/motion_est_template.d \
./include/ffmpeg/libavcodec/motionpixels.d \
./include/ffmpeg/libavcodec/motionpixels_tablegen.d \
./include/ffmpeg/libavcodec/movsub_bsf.d \
./include/ffmpeg/libavcodec/movtextdec.d \
./include/ffmpeg/libavcodec/movtextenc.d \
./include/ffmpeg/libavcodec/mp3_header_decompress_bsf.d \
./include/ffmpeg/libavcodec/mpc.d \
./include/ffmpeg/libavcodec/mpc7.d \
./include/ffmpeg/libavcodec/mpc8.d \
./include/ffmpeg/libavcodec/mpeg12.d \
./include/ffmpeg/libavcodec/mpeg12data.d \
./include/ffmpeg/libavcodec/mpeg12dec.d \
./include/ffmpeg/libavcodec/mpeg12enc.d \
./include/ffmpeg/libavcodec/mpeg4audio.d \
./include/ffmpeg/libavcodec/mpeg4video.d \
./include/ffmpeg/libavcodec/mpeg4video_parser.d \
./include/ffmpeg/libavcodec/mpeg4videodec.d \
./include/ffmpeg/libavcodec/mpeg4videoenc.d \
./include/ffmpeg/libavcodec/mpeg_er.d \
./include/ffmpeg/libavcodec/mpegaudio.d \
./include/ffmpeg/libavcodec/mpegaudio_parser.d \
./include/ffmpeg/libavcodec/mpegaudio_tablegen.d \
./include/ffmpeg/libavcodec/mpegaudiodata.d \
./include/ffmpeg/libavcodec/mpegaudiodec_fixed.d \
./include/ffmpeg/libavcodec/mpegaudiodec_float.d \
./include/ffmpeg/libavcodec/mpegaudiodec_template.d \
./include/ffmpeg/libavcodec/mpegaudiodecheader.d \
./include/ffmpeg/libavcodec/mpegaudiodsp.d \
./include/ffmpeg/libavcodec/mpegaudiodsp_data.d \
./include/ffmpeg/libavcodec/mpegaudiodsp_fixed.d \
./include/ffmpeg/libavcodec/mpegaudiodsp_float.d \
./include/ffmpeg/libavcodec/mpegaudiodsp_template.d \
./include/ffmpeg/libavcodec/mpegaudioenc_fixed.d \
./include/ffmpeg/libavcodec/mpegaudioenc_float.d \
./include/ffmpeg/libavcodec/mpegaudioenc_template.d \
./include/ffmpeg/libavcodec/mpegutils.d \
./include/ffmpeg/libavcodec/mpegvideo.d \
./include/ffmpeg/libavcodec/mpegvideo_enc.d \
./include/ffmpeg/libavcodec/mpegvideo_motion.d \
./include/ffmpeg/libavcodec/mpegvideo_parser.d \
./include/ffmpeg/libavcodec/mpegvideo_xvmc.d \
./include/ffmpeg/libavcodec/mpegvideodsp.d \
./include/ffmpeg/libavcodec/mpegvideoencdsp.d \
./include/ffmpeg/libavcodec/mpl2dec.d \
./include/ffmpeg/libavcodec/mqc.d \
./include/ffmpeg/libavcodec/mqcdec.d \
./include/ffmpeg/libavcodec/mqcenc.d \
./include/ffmpeg/libavcodec/msgsmdec.d \
./include/ffmpeg/libavcodec/msmpeg4.d \
./include/ffmpeg/libavcodec/msmpeg4data.d \
./include/ffmpeg/libavcodec/msmpeg4dec.d \
./include/ffmpeg/libavcodec/msmpeg4enc.d \
./include/ffmpeg/libavcodec/msrle.d \
./include/ffmpeg/libavcodec/msrledec.d \
./include/ffmpeg/libavcodec/mss1.d \
./include/ffmpeg/libavcodec/mss12.d \
./include/ffmpeg/libavcodec/mss2.d \
./include/ffmpeg/libavcodec/mss2dsp.d \
./include/ffmpeg/libavcodec/mss3.d \
./include/ffmpeg/libavcodec/mss34dsp.d \
./include/ffmpeg/libavcodec/mss4.d \
./include/ffmpeg/libavcodec/msvideo1.d \
./include/ffmpeg/libavcodec/msvideo1enc.d \
./include/ffmpeg/libavcodec/mvcdec.d \
./include/ffmpeg/libavcodec/mxpegdec.d \
./include/ffmpeg/libavcodec/nellymoser.d \
./include/ffmpeg/libavcodec/nellymoserdec.d \
./include/ffmpeg/libavcodec/nellymoserenc.d \
./include/ffmpeg/libavcodec/noise_bsf.d \
./include/ffmpeg/libavcodec/nuv.d \
./include/ffmpeg/libavcodec/on2avc.d \
./include/ffmpeg/libavcodec/on2avcdata.d \
./include/ffmpeg/libavcodec/options.d \
./include/ffmpeg/libavcodec/opus.d \
./include/ffmpeg/libavcodec/opus_celt.d \
./include/ffmpeg/libavcodec/opus_imdct.d \
./include/ffmpeg/libavcodec/opus_parser.d \
./include/ffmpeg/libavcodec/opus_silk.d \
./include/ffmpeg/libavcodec/opusdec.d \
./include/ffmpeg/libavcodec/pafaudio.d \
./include/ffmpeg/libavcodec/pafvideo.d \
./include/ffmpeg/libavcodec/pamenc.d \
./include/ffmpeg/libavcodec/parser.d \
./include/ffmpeg/libavcodec/pcm-bluray.d \
./include/ffmpeg/libavcodec/pcm-dvd.d \
./include/ffmpeg/libavcodec/pcm.d \
./include/ffmpeg/libavcodec/pcm_tablegen.d \
./include/ffmpeg/libavcodec/pcx.d \
./include/ffmpeg/libavcodec/pcxenc.d \
./include/ffmpeg/libavcodec/pel_template.d \
./include/ffmpeg/libavcodec/pgssubdec.d \
./include/ffmpeg/libavcodec/pictordec.d \
./include/ffmpeg/libavcodec/pixblockdsp.d \
./include/ffmpeg/libavcodec/pixblockdsp_template.d \
./include/ffmpeg/libavcodec/png.d \
./include/ffmpeg/libavcodec/png_parser.d \
./include/ffmpeg/libavcodec/pngdec.d \
./include/ffmpeg/libavcodec/pngdsp.d \
./include/ffmpeg/libavcodec/pngenc.d \
./include/ffmpeg/libavcodec/pnm.d \
./include/ffmpeg/libavcodec/pnm_parser.d \
./include/ffmpeg/libavcodec/pnmdec.d \
./include/ffmpeg/libavcodec/pnmenc.d \
./include/ffmpeg/libavcodec/proresdata.d \
./include/ffmpeg/libavcodec/proresdec2.d \
./include/ffmpeg/libavcodec/proresdec_lgpl.d \
./include/ffmpeg/libavcodec/proresdsp.d \
./include/ffmpeg/libavcodec/proresenc_anatoliy.d \
./include/ffmpeg/libavcodec/proresenc_kostya.d \
./include/ffmpeg/libavcodec/psymodel.d \
./include/ffmpeg/libavcodec/pthread.d \
./include/ffmpeg/libavcodec/pthread_frame.d \
./include/ffmpeg/libavcodec/pthread_slice.d \
./include/ffmpeg/libavcodec/ptx.d \
./include/ffmpeg/libavcodec/qcelpdec.d \
./include/ffmpeg/libavcodec/qdm2.d \
./include/ffmpeg/libavcodec/qdm2_tablegen.d \
./include/ffmpeg/libavcodec/qdrw.d \
./include/ffmpeg/libavcodec/qpeg.d \
./include/ffmpeg/libavcodec/qpel_template.d \
./include/ffmpeg/libavcodec/qpeldsp.d \
./include/ffmpeg/libavcodec/qtrle.d \
./include/ffmpeg/libavcodec/qtrleenc.d \
./include/ffmpeg/libavcodec/r210dec.d \
./include/ffmpeg/libavcodec/r210enc.d \
./include/ffmpeg/libavcodec/ra144.d \
./include/ffmpeg/libavcodec/ra144dec.d \
./include/ffmpeg/libavcodec/ra144enc.d \
./include/ffmpeg/libavcodec/ra288.d \
./include/ffmpeg/libavcodec/ralf.d \
./include/ffmpeg/libavcodec/rangecoder.d \
./include/ffmpeg/libavcodec/ratecontrol.d \
./include/ffmpeg/libavcodec/raw.d \
./include/ffmpeg/libavcodec/rawdec.d \
./include/ffmpeg/libavcodec/rawenc.d \
./include/ffmpeg/libavcodec/rdft.d \
./include/ffmpeg/libavcodec/realtextdec.d \
./include/ffmpeg/libavcodec/remove_extradata_bsf.d \
./include/ffmpeg/libavcodec/resample.d \
./include/ffmpeg/libavcodec/resample2.d \
./include/ffmpeg/libavcodec/rl2.d \
./include/ffmpeg/libavcodec/rle.d \
./include/ffmpeg/libavcodec/roqaudioenc.d \
./include/ffmpeg/libavcodec/roqvideo.d \
./include/ffmpeg/libavcodec/roqvideodec.d \
./include/ffmpeg/libavcodec/roqvideoenc.d \
./include/ffmpeg/libavcodec/rpza.d \
./include/ffmpeg/libavcodec/rtjpeg.d \
./include/ffmpeg/libavcodec/rv10.d \
./include/ffmpeg/libavcodec/rv10enc.d \
./include/ffmpeg/libavcodec/rv20enc.d \
./include/ffmpeg/libavcodec/rv30.d \
./include/ffmpeg/libavcodec/rv30dsp.d \
./include/ffmpeg/libavcodec/rv34.d \
./include/ffmpeg/libavcodec/rv34_parser.d \
./include/ffmpeg/libavcodec/rv34dsp.d \
./include/ffmpeg/libavcodec/rv40.d \
./include/ffmpeg/libavcodec/rv40dsp.d \
./include/ffmpeg/libavcodec/s302m.d \
./include/ffmpeg/libavcodec/s302menc.d \
./include/ffmpeg/libavcodec/s3tc.d \
./include/ffmpeg/libavcodec/samidec.d \
./include/ffmpeg/libavcodec/sanm.d \
./include/ffmpeg/libavcodec/sbrdsp.d \
./include/ffmpeg/libavcodec/sgidec.d \
./include/ffmpeg/libavcodec/sgienc.d \
./include/ffmpeg/libavcodec/sgirledec.d \
./include/ffmpeg/libavcodec/shorten.d \
./include/ffmpeg/libavcodec/simple_idct.d \
./include/ffmpeg/libavcodec/simple_idct_template.d \
./include/ffmpeg/libavcodec/sinewin.d \
./include/ffmpeg/libavcodec/sinewin_tablegen.d \
./include/ffmpeg/libavcodec/sipr.d \
./include/ffmpeg/libavcodec/sipr16k.d \
./include/ffmpeg/libavcodec/smacker.d \
./include/ffmpeg/libavcodec/smc.d \
./include/ffmpeg/libavcodec/smvjpegdec.d \
./include/ffmpeg/libavcodec/snow.d \
./include/ffmpeg/libavcodec/snow_dwt.d \
./include/ffmpeg/libavcodec/snowdec.d \
./include/ffmpeg/libavcodec/snowenc.d \
./include/ffmpeg/libavcodec/sonic.d \
./include/ffmpeg/libavcodec/sp5xdec.d \
./include/ffmpeg/libavcodec/srtdec.d \
./include/ffmpeg/libavcodec/srtenc.d \
./include/ffmpeg/libavcodec/startcode.d \
./include/ffmpeg/libavcodec/subviewerdec.d \
./include/ffmpeg/libavcodec/sunrast.d \
./include/ffmpeg/libavcodec/sunrastenc.d \
./include/ffmpeg/libavcodec/svq1.d \
./include/ffmpeg/libavcodec/svq13.d \
./include/ffmpeg/libavcodec/svq1dec.d \
./include/ffmpeg/libavcodec/svq1enc.d \
./include/ffmpeg/libavcodec/svq3.d \
./include/ffmpeg/libavcodec/synth_filter.d \
./include/ffmpeg/libavcodec/tak.d \
./include/ffmpeg/libavcodec/tak_parser.d \
./include/ffmpeg/libavcodec/takdec.d \
./include/ffmpeg/libavcodec/targa.d \
./include/ffmpeg/libavcodec/targa_y216dec.d \
./include/ffmpeg/libavcodec/targaenc.d \
./include/ffmpeg/libavcodec/textdec.d \
./include/ffmpeg/libavcodec/tiertexseqv.d \
./include/ffmpeg/libavcodec/tiff.d \
./include/ffmpeg/libavcodec/tiff_common.d \
./include/ffmpeg/libavcodec/tiff_data.d \
./include/ffmpeg/libavcodec/tiffenc.d \
./include/ffmpeg/libavcodec/tmv.d \
./include/ffmpeg/libavcodec/tpeldsp.d \
./include/ffmpeg/libavcodec/truemotion1.d \
./include/ffmpeg/libavcodec/truemotion2.d \
./include/ffmpeg/libavcodec/truespeech.d \
./include/ffmpeg/libavcodec/tscc.d \
./include/ffmpeg/libavcodec/tscc2.d \
./include/ffmpeg/libavcodec/tta.d \
./include/ffmpeg/libavcodec/ttadata.d \
./include/ffmpeg/libavcodec/ttadsp.d \
./include/ffmpeg/libavcodec/ttaenc.d \
./include/ffmpeg/libavcodec/twinvq.d \
./include/ffmpeg/libavcodec/twinvqdec.d \
./include/ffmpeg/libavcodec/txd.d \
./include/ffmpeg/libavcodec/ulti.d \
./include/ffmpeg/libavcodec/utils.d \
./include/ffmpeg/libavcodec/utvideo.d \
./include/ffmpeg/libavcodec/utvideodec.d \
./include/ffmpeg/libavcodec/utvideoenc.d \
./include/ffmpeg/libavcodec/v210dec.d \
./include/ffmpeg/libavcodec/v210enc.d \
./include/ffmpeg/libavcodec/v210x.d \
./include/ffmpeg/libavcodec/v308dec.d \
./include/ffmpeg/libavcodec/v308enc.d \
./include/ffmpeg/libavcodec/v408dec.d \
./include/ffmpeg/libavcodec/v408enc.d \
./include/ffmpeg/libavcodec/v410dec.d \
./include/ffmpeg/libavcodec/v410enc.d \
./include/ffmpeg/libavcodec/vaapi.d \
./include/ffmpeg/libavcodec/vaapi_h264.d \
./include/ffmpeg/libavcodec/vaapi_mpeg.d \
./include/ffmpeg/libavcodec/vaapi_mpeg2.d \
./include/ffmpeg/libavcodec/vaapi_mpeg4.d \
./include/ffmpeg/libavcodec/vaapi_vc1.d \
./include/ffmpeg/libavcodec/vb.d \
./include/ffmpeg/libavcodec/vble.d \
./include/ffmpeg/libavcodec/vc1.d \
./include/ffmpeg/libavcodec/vc1_parser.d \
./include/ffmpeg/libavcodec/vc1data.d \
./include/ffmpeg/libavcodec/vc1dec.d \
./include/ffmpeg/libavcodec/vc1dsp.d \
./include/ffmpeg/libavcodec/vcr1.d \
./include/ffmpeg/libavcodec/vda.d \
./include/ffmpeg/libavcodec/vda_h264.d \
./include/ffmpeg/libavcodec/vda_h264_dec.d \
./include/ffmpeg/libavcodec/vdpau.d \
./include/ffmpeg/libavcodec/vdpau_h264.d \
./include/ffmpeg/libavcodec/vdpau_mpeg12.d \
./include/ffmpeg/libavcodec/vdpau_mpeg4.d \
./include/ffmpeg/libavcodec/vdpau_vc1.d \
./include/ffmpeg/libavcodec/videodsp.d \
./include/ffmpeg/libavcodec/videodsp_template.d \
./include/ffmpeg/libavcodec/vima.d \
./include/ffmpeg/libavcodec/vmdaudio.d \
./include/ffmpeg/libavcodec/vmdvideo.d \
./include/ffmpeg/libavcodec/vmnc.d \
./include/ffmpeg/libavcodec/vorbis.d \
./include/ffmpeg/libavcodec/vorbis_data.d \
./include/ffmpeg/libavcodec/vorbis_parser.d \
./include/ffmpeg/libavcodec/vorbisdec.d \
./include/ffmpeg/libavcodec/vorbisdsp.d \
./include/ffmpeg/libavcodec/vorbisenc.d \
./include/ffmpeg/libavcodec/vp3.d \
./include/ffmpeg/libavcodec/vp3_parser.d \
./include/ffmpeg/libavcodec/vp3dsp.d \
./include/ffmpeg/libavcodec/vp5.d \
./include/ffmpeg/libavcodec/vp56.d \
./include/ffmpeg/libavcodec/vp56data.d \
./include/ffmpeg/libavcodec/vp56dsp.d \
./include/ffmpeg/libavcodec/vp56rac.d \
./include/ffmpeg/libavcodec/vp6.d \
./include/ffmpeg/libavcodec/vp6dsp.d \
./include/ffmpeg/libavcodec/vp8.d \
./include/ffmpeg/libavcodec/vp8_parser.d \
./include/ffmpeg/libavcodec/vp8dsp.d \
./include/ffmpeg/libavcodec/vp9.d \
./include/ffmpeg/libavcodec/vp9_parser.d \
./include/ffmpeg/libavcodec/vp9dsp.d \
./include/ffmpeg/libavcodec/vqavideo.d \
./include/ffmpeg/libavcodec/wavpack.d \
./include/ffmpeg/libavcodec/wavpackenc.d \
./include/ffmpeg/libavcodec/webp.d \
./include/ffmpeg/libavcodec/webvttdec.d \
./include/ffmpeg/libavcodec/webvttenc.d \
./include/ffmpeg/libavcodec/wma.d \
./include/ffmpeg/libavcodec/wma_common.d \
./include/ffmpeg/libavcodec/wmadec.d \
./include/ffmpeg/libavcodec/wmaenc.d \
./include/ffmpeg/libavcodec/wmalosslessdec.d \
./include/ffmpeg/libavcodec/wmaprodec.d \
./include/ffmpeg/libavcodec/wmavoice.d \
./include/ffmpeg/libavcodec/wmv2.d \
./include/ffmpeg/libavcodec/wmv2dec.d \
./include/ffmpeg/libavcodec/wmv2dsp.d \
./include/ffmpeg/libavcodec/wmv2enc.d \
./include/ffmpeg/libavcodec/wnv1.d \
./include/ffmpeg/libavcodec/ws-snd1.d \
./include/ffmpeg/libavcodec/xan.d \
./include/ffmpeg/libavcodec/xbmdec.d \
./include/ffmpeg/libavcodec/xbmenc.d \
./include/ffmpeg/libavcodec/xface.d \
./include/ffmpeg/libavcodec/xfacedec.d \
./include/ffmpeg/libavcodec/xfaceenc.d \
./include/ffmpeg/libavcodec/xiph.d \
./include/ffmpeg/libavcodec/xl.d \
./include/ffmpeg/libavcodec/xsubdec.d \
./include/ffmpeg/libavcodec/xsubenc.d \
./include/ffmpeg/libavcodec/xwddec.d \
./include/ffmpeg/libavcodec/xwdenc.d \
./include/ffmpeg/libavcodec/xxan.d \
./include/ffmpeg/libavcodec/y41pdec.d \
./include/ffmpeg/libavcodec/y41penc.d \
./include/ffmpeg/libavcodec/yop.d \
./include/ffmpeg/libavcodec/yuv4dec.d \
./include/ffmpeg/libavcodec/yuv4enc.d \
./include/ffmpeg/libavcodec/zerocodec.d \
./include/ffmpeg/libavcodec/zmbv.d \
./include/ffmpeg/libavcodec/zmbvenc.d 

CPP_DEPS += \
./include/ffmpeg/libavcodec/libstagefright.d \
./include/ffmpeg/libavcodec/libutvideodec.d \
./include/ffmpeg/libavcodec/libutvideoenc.d 


# Each subdirectory must supply rules for building sources it contributes
include/ffmpeg/libavcodec/%.o: ../include/ffmpeg/libavcodec/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Compiler'
	gcc -I./include -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

include/ffmpeg/libavcodec/%.o: ../include/ffmpeg/libavcodec/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: Cross G++ Compiler'
	g++ -I"/home/xyz/workspace/ITS/ITS_2.0_ELC/04.Construction/CCTV/src/CCTV_VOS/include" -I"/home/xyz/workspace/ITS/ITS_2.0_ELC/04.Construction/CCTV/src/CCTV_VOS/include/ffmpeg" -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


