################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../include/ffmpeg/libavcodec/x86/ac3dsp_init.c \
../include/ffmpeg/libavcodec/x86/audiodsp_init.c \
../include/ffmpeg/libavcodec/x86/blockdsp_init.c \
../include/ffmpeg/libavcodec/x86/bswapdsp_init.c \
../include/ffmpeg/libavcodec/x86/cavsdsp.c \
../include/ffmpeg/libavcodec/x86/constants.c \
../include/ffmpeg/libavcodec/x86/dcadsp_init.c \
../include/ffmpeg/libavcodec/x86/dct_init.c \
../include/ffmpeg/libavcodec/x86/dirac_dwt.c \
../include/ffmpeg/libavcodec/x86/diracdsp_mmx.c \
../include/ffmpeg/libavcodec/x86/dnxhdenc_init.c \
../include/ffmpeg/libavcodec/x86/dsputil_init.c \
../include/ffmpeg/libavcodec/x86/dsputilenc_mmx.c \
../include/ffmpeg/libavcodec/x86/fdct.c \
../include/ffmpeg/libavcodec/x86/fdctdsp_init.c \
../include/ffmpeg/libavcodec/x86/fft_init.c \
../include/ffmpeg/libavcodec/x86/flacdsp_init.c \
../include/ffmpeg/libavcodec/x86/fmtconvert_init.c \
../include/ffmpeg/libavcodec/x86/h263dsp_init.c \
../include/ffmpeg/libavcodec/x86/h264_intrapred_init.c \
../include/ffmpeg/libavcodec/x86/h264_qpel.c \
../include/ffmpeg/libavcodec/x86/h264chroma_init.c \
../include/ffmpeg/libavcodec/x86/h264dsp_init.c \
../include/ffmpeg/libavcodec/x86/hevcdsp_init.c \
../include/ffmpeg/libavcodec/x86/hpeldsp_init.c \
../include/ffmpeg/libavcodec/x86/hpeldsp_rnd_template.c \
../include/ffmpeg/libavcodec/x86/huffyuvdsp_init.c \
../include/ffmpeg/libavcodec/x86/huffyuvencdsp_mmx.c \
../include/ffmpeg/libavcodec/x86/idct_mmx_xvid.c \
../include/ffmpeg/libavcodec/x86/idct_sse2_xvid.c \
../include/ffmpeg/libavcodec/x86/idctdsp_init.c \
../include/ffmpeg/libavcodec/x86/idctdsp_mmx.c \
../include/ffmpeg/libavcodec/x86/lossless_audiodsp_init.c \
../include/ffmpeg/libavcodec/x86/lossless_videodsp_init.c \
../include/ffmpeg/libavcodec/x86/lpc.c \
../include/ffmpeg/libavcodec/x86/mlpdsp.c \
../include/ffmpeg/libavcodec/x86/motion_est.c \
../include/ffmpeg/libavcodec/x86/mpegaudiodsp.c \
../include/ffmpeg/libavcodec/x86/mpegvideo.c \
../include/ffmpeg/libavcodec/x86/mpegvideodsp.c \
../include/ffmpeg/libavcodec/x86/mpegvideoenc.c \
../include/ffmpeg/libavcodec/x86/mpegvideoenc_qns_template.c \
../include/ffmpeg/libavcodec/x86/mpegvideoenc_template.c \
../include/ffmpeg/libavcodec/x86/mpegvideoencdsp_init.c \
../include/ffmpeg/libavcodec/x86/pixblockdsp_init.c \
../include/ffmpeg/libavcodec/x86/pngdsp_init.c \
../include/ffmpeg/libavcodec/x86/proresdsp_init.c \
../include/ffmpeg/libavcodec/x86/qpeldsp_init.c \
../include/ffmpeg/libavcodec/x86/rnd_template.c \
../include/ffmpeg/libavcodec/x86/rv34dsp_init.c \
../include/ffmpeg/libavcodec/x86/rv40dsp_init.c \
../include/ffmpeg/libavcodec/x86/sbrdsp_init.c \
../include/ffmpeg/libavcodec/x86/simple_idct.c \
../include/ffmpeg/libavcodec/x86/snowdsp.c \
../include/ffmpeg/libavcodec/x86/svq1enc_init.c \
../include/ffmpeg/libavcodec/x86/ttadsp_init.c \
../include/ffmpeg/libavcodec/x86/v210-init.c \
../include/ffmpeg/libavcodec/x86/vc1dsp_init.c \
../include/ffmpeg/libavcodec/x86/vc1dsp_mmx.c \
../include/ffmpeg/libavcodec/x86/videodsp_init.c \
../include/ffmpeg/libavcodec/x86/vorbisdsp_init.c \
../include/ffmpeg/libavcodec/x86/vp3dsp_init.c \
../include/ffmpeg/libavcodec/x86/vp6dsp_init.c \
../include/ffmpeg/libavcodec/x86/vp8dsp_init.c \
../include/ffmpeg/libavcodec/x86/vp9dsp_init.c \
../include/ffmpeg/libavcodec/x86/w64xmmtest.c 

ASM_SRCS += \
../include/ffmpeg/libavcodec/x86/ac3dsp.asm \
../include/ffmpeg/libavcodec/x86/audiodsp.asm \
../include/ffmpeg/libavcodec/x86/blockdsp.asm \
../include/ffmpeg/libavcodec/x86/bswapdsp.asm \
../include/ffmpeg/libavcodec/x86/dcadsp.asm \
../include/ffmpeg/libavcodec/x86/dct32.asm \
../include/ffmpeg/libavcodec/x86/deinterlace.asm \
../include/ffmpeg/libavcodec/x86/diracdsp_yasm.asm \
../include/ffmpeg/libavcodec/x86/dnxhdenc.asm \
../include/ffmpeg/libavcodec/x86/dsputilenc.asm \
../include/ffmpeg/libavcodec/x86/dwt_yasm.asm \
../include/ffmpeg/libavcodec/x86/fft.asm \
../include/ffmpeg/libavcodec/x86/flacdsp.asm \
../include/ffmpeg/libavcodec/x86/fmtconvert.asm \
../include/ffmpeg/libavcodec/x86/fpel.asm \
../include/ffmpeg/libavcodec/x86/h263_loopfilter.asm \
../include/ffmpeg/libavcodec/x86/h264_chromamc.asm \
../include/ffmpeg/libavcodec/x86/h264_chromamc_10bit.asm \
../include/ffmpeg/libavcodec/x86/h264_deblock.asm \
../include/ffmpeg/libavcodec/x86/h264_deblock_10bit.asm \
../include/ffmpeg/libavcodec/x86/h264_idct.asm \
../include/ffmpeg/libavcodec/x86/h264_idct_10bit.asm \
../include/ffmpeg/libavcodec/x86/h264_intrapred.asm \
../include/ffmpeg/libavcodec/x86/h264_intrapred_10bit.asm \
../include/ffmpeg/libavcodec/x86/h264_qpel_10bit.asm \
../include/ffmpeg/libavcodec/x86/h264_qpel_8bit.asm \
../include/ffmpeg/libavcodec/x86/h264_weight.asm \
../include/ffmpeg/libavcodec/x86/h264_weight_10bit.asm \
../include/ffmpeg/libavcodec/x86/hevc_deblock.asm \
../include/ffmpeg/libavcodec/x86/hevc_idct.asm \
../include/ffmpeg/libavcodec/x86/hevc_mc.asm \
../include/ffmpeg/libavcodec/x86/hpeldsp.asm \
../include/ffmpeg/libavcodec/x86/huffyuvdsp.asm \
../include/ffmpeg/libavcodec/x86/idctdsp.asm \
../include/ffmpeg/libavcodec/x86/imdct36.asm \
../include/ffmpeg/libavcodec/x86/lossless_audiodsp.asm \
../include/ffmpeg/libavcodec/x86/lossless_videodsp.asm \
../include/ffmpeg/libavcodec/x86/mpegvideoencdsp.asm \
../include/ffmpeg/libavcodec/x86/pixblockdsp.asm \
../include/ffmpeg/libavcodec/x86/pngdsp.asm \
../include/ffmpeg/libavcodec/x86/proresdsp.asm \
../include/ffmpeg/libavcodec/x86/qpel.asm \
../include/ffmpeg/libavcodec/x86/qpeldsp.asm \
../include/ffmpeg/libavcodec/x86/rv34dsp.asm \
../include/ffmpeg/libavcodec/x86/rv40dsp.asm \
../include/ffmpeg/libavcodec/x86/sbrdsp.asm \
../include/ffmpeg/libavcodec/x86/svq1enc.asm \
../include/ffmpeg/libavcodec/x86/ttadsp.asm \
../include/ffmpeg/libavcodec/x86/v210.asm \
../include/ffmpeg/libavcodec/x86/vc1dsp.asm \
../include/ffmpeg/libavcodec/x86/videodsp.asm \
../include/ffmpeg/libavcodec/x86/vorbisdsp.asm \
../include/ffmpeg/libavcodec/x86/vp3dsp.asm \
../include/ffmpeg/libavcodec/x86/vp6dsp.asm \
../include/ffmpeg/libavcodec/x86/vp8dsp.asm \
../include/ffmpeg/libavcodec/x86/vp8dsp_loopfilter.asm \
../include/ffmpeg/libavcodec/x86/vp9intrapred.asm \
../include/ffmpeg/libavcodec/x86/vp9itxfm.asm \
../include/ffmpeg/libavcodec/x86/vp9lpf.asm \
../include/ffmpeg/libavcodec/x86/vp9mc.asm 

OBJS += \
./include/ffmpeg/libavcodec/x86/ac3dsp.o \
./include/ffmpeg/libavcodec/x86/ac3dsp_init.o \
./include/ffmpeg/libavcodec/x86/audiodsp.o \
./include/ffmpeg/libavcodec/x86/audiodsp_init.o \
./include/ffmpeg/libavcodec/x86/blockdsp.o \
./include/ffmpeg/libavcodec/x86/blockdsp_init.o \
./include/ffmpeg/libavcodec/x86/bswapdsp.o \
./include/ffmpeg/libavcodec/x86/bswapdsp_init.o \
./include/ffmpeg/libavcodec/x86/cavsdsp.o \
./include/ffmpeg/libavcodec/x86/constants.o \
./include/ffmpeg/libavcodec/x86/dcadsp.o \
./include/ffmpeg/libavcodec/x86/dcadsp_init.o \
./include/ffmpeg/libavcodec/x86/dct32.o \
./include/ffmpeg/libavcodec/x86/dct_init.o \
./include/ffmpeg/libavcodec/x86/deinterlace.o \
./include/ffmpeg/libavcodec/x86/dirac_dwt.o \
./include/ffmpeg/libavcodec/x86/diracdsp_mmx.o \
./include/ffmpeg/libavcodec/x86/diracdsp_yasm.o \
./include/ffmpeg/libavcodec/x86/dnxhdenc.o \
./include/ffmpeg/libavcodec/x86/dnxhdenc_init.o \
./include/ffmpeg/libavcodec/x86/dsputil_init.o \
./include/ffmpeg/libavcodec/x86/dsputilenc.o \
./include/ffmpeg/libavcodec/x86/dsputilenc_mmx.o \
./include/ffmpeg/libavcodec/x86/dwt_yasm.o \
./include/ffmpeg/libavcodec/x86/fdct.o \
./include/ffmpeg/libavcodec/x86/fdctdsp_init.o \
./include/ffmpeg/libavcodec/x86/fft.o \
./include/ffmpeg/libavcodec/x86/fft_init.o \
./include/ffmpeg/libavcodec/x86/flacdsp.o \
./include/ffmpeg/libavcodec/x86/flacdsp_init.o \
./include/ffmpeg/libavcodec/x86/fmtconvert.o \
./include/ffmpeg/libavcodec/x86/fmtconvert_init.o \
./include/ffmpeg/libavcodec/x86/fpel.o \
./include/ffmpeg/libavcodec/x86/h263_loopfilter.o \
./include/ffmpeg/libavcodec/x86/h263dsp_init.o \
./include/ffmpeg/libavcodec/x86/h264_chromamc.o \
./include/ffmpeg/libavcodec/x86/h264_chromamc_10bit.o \
./include/ffmpeg/libavcodec/x86/h264_deblock.o \
./include/ffmpeg/libavcodec/x86/h264_deblock_10bit.o \
./include/ffmpeg/libavcodec/x86/h264_idct.o \
./include/ffmpeg/libavcodec/x86/h264_idct_10bit.o \
./include/ffmpeg/libavcodec/x86/h264_intrapred.o \
./include/ffmpeg/libavcodec/x86/h264_intrapred_10bit.o \
./include/ffmpeg/libavcodec/x86/h264_intrapred_init.o \
./include/ffmpeg/libavcodec/x86/h264_qpel.o \
./include/ffmpeg/libavcodec/x86/h264_qpel_10bit.o \
./include/ffmpeg/libavcodec/x86/h264_qpel_8bit.o \
./include/ffmpeg/libavcodec/x86/h264_weight.o \
./include/ffmpeg/libavcodec/x86/h264_weight_10bit.o \
./include/ffmpeg/libavcodec/x86/h264chroma_init.o \
./include/ffmpeg/libavcodec/x86/h264dsp_init.o \
./include/ffmpeg/libavcodec/x86/hevc_deblock.o \
./include/ffmpeg/libavcodec/x86/hevc_idct.o \
./include/ffmpeg/libavcodec/x86/hevc_mc.o \
./include/ffmpeg/libavcodec/x86/hevcdsp_init.o \
./include/ffmpeg/libavcodec/x86/hpeldsp.o \
./include/ffmpeg/libavcodec/x86/hpeldsp_init.o \
./include/ffmpeg/libavcodec/x86/hpeldsp_rnd_template.o \
./include/ffmpeg/libavcodec/x86/huffyuvdsp.o \
./include/ffmpeg/libavcodec/x86/huffyuvdsp_init.o \
./include/ffmpeg/libavcodec/x86/huffyuvencdsp_mmx.o \
./include/ffmpeg/libavcodec/x86/idct_mmx_xvid.o \
./include/ffmpeg/libavcodec/x86/idct_sse2_xvid.o \
./include/ffmpeg/libavcodec/x86/idctdsp.o \
./include/ffmpeg/libavcodec/x86/idctdsp_init.o \
./include/ffmpeg/libavcodec/x86/idctdsp_mmx.o \
./include/ffmpeg/libavcodec/x86/imdct36.o \
./include/ffmpeg/libavcodec/x86/lossless_audiodsp.o \
./include/ffmpeg/libavcodec/x86/lossless_audiodsp_init.o \
./include/ffmpeg/libavcodec/x86/lossless_videodsp.o \
./include/ffmpeg/libavcodec/x86/lossless_videodsp_init.o \
./include/ffmpeg/libavcodec/x86/lpc.o \
./include/ffmpeg/libavcodec/x86/mlpdsp.o \
./include/ffmpeg/libavcodec/x86/motion_est.o \
./include/ffmpeg/libavcodec/x86/mpegaudiodsp.o \
./include/ffmpeg/libavcodec/x86/mpegvideo.o \
./include/ffmpeg/libavcodec/x86/mpegvideodsp.o \
./include/ffmpeg/libavcodec/x86/mpegvideoenc.o \
./include/ffmpeg/libavcodec/x86/mpegvideoenc_qns_template.o \
./include/ffmpeg/libavcodec/x86/mpegvideoenc_template.o \
./include/ffmpeg/libavcodec/x86/mpegvideoencdsp.o \
./include/ffmpeg/libavcodec/x86/mpegvideoencdsp_init.o \
./include/ffmpeg/libavcodec/x86/pixblockdsp.o \
./include/ffmpeg/libavcodec/x86/pixblockdsp_init.o \
./include/ffmpeg/libavcodec/x86/pngdsp.o \
./include/ffmpeg/libavcodec/x86/pngdsp_init.o \
./include/ffmpeg/libavcodec/x86/proresdsp.o \
./include/ffmpeg/libavcodec/x86/proresdsp_init.o \
./include/ffmpeg/libavcodec/x86/qpel.o \
./include/ffmpeg/libavcodec/x86/qpeldsp.o \
./include/ffmpeg/libavcodec/x86/qpeldsp_init.o \
./include/ffmpeg/libavcodec/x86/rnd_template.o \
./include/ffmpeg/libavcodec/x86/rv34dsp.o \
./include/ffmpeg/libavcodec/x86/rv34dsp_init.o \
./include/ffmpeg/libavcodec/x86/rv40dsp.o \
./include/ffmpeg/libavcodec/x86/rv40dsp_init.o \
./include/ffmpeg/libavcodec/x86/sbrdsp.o \
./include/ffmpeg/libavcodec/x86/sbrdsp_init.o \
./include/ffmpeg/libavcodec/x86/simple_idct.o \
./include/ffmpeg/libavcodec/x86/snowdsp.o \
./include/ffmpeg/libavcodec/x86/svq1enc.o \
./include/ffmpeg/libavcodec/x86/svq1enc_init.o \
./include/ffmpeg/libavcodec/x86/ttadsp.o \
./include/ffmpeg/libavcodec/x86/ttadsp_init.o \
./include/ffmpeg/libavcodec/x86/v210-init.o \
./include/ffmpeg/libavcodec/x86/v210.o \
./include/ffmpeg/libavcodec/x86/vc1dsp.o \
./include/ffmpeg/libavcodec/x86/vc1dsp_init.o \
./include/ffmpeg/libavcodec/x86/vc1dsp_mmx.o \
./include/ffmpeg/libavcodec/x86/videodsp.o \
./include/ffmpeg/libavcodec/x86/videodsp_init.o \
./include/ffmpeg/libavcodec/x86/vorbisdsp.o \
./include/ffmpeg/libavcodec/x86/vorbisdsp_init.o \
./include/ffmpeg/libavcodec/x86/vp3dsp.o \
./include/ffmpeg/libavcodec/x86/vp3dsp_init.o \
./include/ffmpeg/libavcodec/x86/vp6dsp.o \
./include/ffmpeg/libavcodec/x86/vp6dsp_init.o \
./include/ffmpeg/libavcodec/x86/vp8dsp.o \
./include/ffmpeg/libavcodec/x86/vp8dsp_init.o \
./include/ffmpeg/libavcodec/x86/vp8dsp_loopfilter.o \
./include/ffmpeg/libavcodec/x86/vp9dsp_init.o \
./include/ffmpeg/libavcodec/x86/vp9intrapred.o \
./include/ffmpeg/libavcodec/x86/vp9itxfm.o \
./include/ffmpeg/libavcodec/x86/vp9lpf.o \
./include/ffmpeg/libavcodec/x86/vp9mc.o \
./include/ffmpeg/libavcodec/x86/w64xmmtest.o 

C_DEPS += \
./include/ffmpeg/libavcodec/x86/ac3dsp_init.d \
./include/ffmpeg/libavcodec/x86/audiodsp_init.d \
./include/ffmpeg/libavcodec/x86/blockdsp_init.d \
./include/ffmpeg/libavcodec/x86/bswapdsp_init.d \
./include/ffmpeg/libavcodec/x86/cavsdsp.d \
./include/ffmpeg/libavcodec/x86/constants.d \
./include/ffmpeg/libavcodec/x86/dcadsp_init.d \
./include/ffmpeg/libavcodec/x86/dct_init.d \
./include/ffmpeg/libavcodec/x86/dirac_dwt.d \
./include/ffmpeg/libavcodec/x86/diracdsp_mmx.d \
./include/ffmpeg/libavcodec/x86/dnxhdenc_init.d \
./include/ffmpeg/libavcodec/x86/dsputil_init.d \
./include/ffmpeg/libavcodec/x86/dsputilenc_mmx.d \
./include/ffmpeg/libavcodec/x86/fdct.d \
./include/ffmpeg/libavcodec/x86/fdctdsp_init.d \
./include/ffmpeg/libavcodec/x86/fft_init.d \
./include/ffmpeg/libavcodec/x86/flacdsp_init.d \
./include/ffmpeg/libavcodec/x86/fmtconvert_init.d \
./include/ffmpeg/libavcodec/x86/h263dsp_init.d \
./include/ffmpeg/libavcodec/x86/h264_intrapred_init.d \
./include/ffmpeg/libavcodec/x86/h264_qpel.d \
./include/ffmpeg/libavcodec/x86/h264chroma_init.d \
./include/ffmpeg/libavcodec/x86/h264dsp_init.d \
./include/ffmpeg/libavcodec/x86/hevcdsp_init.d \
./include/ffmpeg/libavcodec/x86/hpeldsp_init.d \
./include/ffmpeg/libavcodec/x86/hpeldsp_rnd_template.d \
./include/ffmpeg/libavcodec/x86/huffyuvdsp_init.d \
./include/ffmpeg/libavcodec/x86/huffyuvencdsp_mmx.d \
./include/ffmpeg/libavcodec/x86/idct_mmx_xvid.d \
./include/ffmpeg/libavcodec/x86/idct_sse2_xvid.d \
./include/ffmpeg/libavcodec/x86/idctdsp_init.d \
./include/ffmpeg/libavcodec/x86/idctdsp_mmx.d \
./include/ffmpeg/libavcodec/x86/lossless_audiodsp_init.d \
./include/ffmpeg/libavcodec/x86/lossless_videodsp_init.d \
./include/ffmpeg/libavcodec/x86/lpc.d \
./include/ffmpeg/libavcodec/x86/mlpdsp.d \
./include/ffmpeg/libavcodec/x86/motion_est.d \
./include/ffmpeg/libavcodec/x86/mpegaudiodsp.d \
./include/ffmpeg/libavcodec/x86/mpegvideo.d \
./include/ffmpeg/libavcodec/x86/mpegvideodsp.d \
./include/ffmpeg/libavcodec/x86/mpegvideoenc.d \
./include/ffmpeg/libavcodec/x86/mpegvideoenc_qns_template.d \
./include/ffmpeg/libavcodec/x86/mpegvideoenc_template.d \
./include/ffmpeg/libavcodec/x86/mpegvideoencdsp_init.d \
./include/ffmpeg/libavcodec/x86/pixblockdsp_init.d \
./include/ffmpeg/libavcodec/x86/pngdsp_init.d \
./include/ffmpeg/libavcodec/x86/proresdsp_init.d \
./include/ffmpeg/libavcodec/x86/qpeldsp_init.d \
./include/ffmpeg/libavcodec/x86/rnd_template.d \
./include/ffmpeg/libavcodec/x86/rv34dsp_init.d \
./include/ffmpeg/libavcodec/x86/rv40dsp_init.d \
./include/ffmpeg/libavcodec/x86/sbrdsp_init.d \
./include/ffmpeg/libavcodec/x86/simple_idct.d \
./include/ffmpeg/libavcodec/x86/snowdsp.d \
./include/ffmpeg/libavcodec/x86/svq1enc_init.d \
./include/ffmpeg/libavcodec/x86/ttadsp_init.d \
./include/ffmpeg/libavcodec/x86/v210-init.d \
./include/ffmpeg/libavcodec/x86/vc1dsp_init.d \
./include/ffmpeg/libavcodec/x86/vc1dsp_mmx.d \
./include/ffmpeg/libavcodec/x86/videodsp_init.d \
./include/ffmpeg/libavcodec/x86/vorbisdsp_init.d \
./include/ffmpeg/libavcodec/x86/vp3dsp_init.d \
./include/ffmpeg/libavcodec/x86/vp6dsp_init.d \
./include/ffmpeg/libavcodec/x86/vp8dsp_init.d \
./include/ffmpeg/libavcodec/x86/vp9dsp_init.d \
./include/ffmpeg/libavcodec/x86/w64xmmtest.d 


# Each subdirectory must supply rules for building sources it contributes
include/ffmpeg/libavcodec/x86/%.o: ../include/ffmpeg/libavcodec/x86/%.asm
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Assembler'
	as  -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

include/ffmpeg/libavcodec/x86/%.o: ../include/ffmpeg/libavcodec/x86/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Compiler'
	gcc -I./include -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


