################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../include/ffmpeg/libavfilter/aeval.c \
../include/ffmpeg/libavfilter/af_aconvert.c \
../include/ffmpeg/libavfilter/af_adelay.c \
../include/ffmpeg/libavfilter/af_aecho.c \
../include/ffmpeg/libavfilter/af_afade.c \
../include/ffmpeg/libavfilter/af_aformat.c \
../include/ffmpeg/libavfilter/af_amerge.c \
../include/ffmpeg/libavfilter/af_amix.c \
../include/ffmpeg/libavfilter/af_anull.c \
../include/ffmpeg/libavfilter/af_apad.c \
../include/ffmpeg/libavfilter/af_aphaser.c \
../include/ffmpeg/libavfilter/af_aresample.c \
../include/ffmpeg/libavfilter/af_asetnsamples.c \
../include/ffmpeg/libavfilter/af_asetrate.c \
../include/ffmpeg/libavfilter/af_ashowinfo.c \
../include/ffmpeg/libavfilter/af_astats.c \
../include/ffmpeg/libavfilter/af_astreamsync.c \
../include/ffmpeg/libavfilter/af_asyncts.c \
../include/ffmpeg/libavfilter/af_atempo.c \
../include/ffmpeg/libavfilter/af_biquads.c \
../include/ffmpeg/libavfilter/af_bs2b.c \
../include/ffmpeg/libavfilter/af_channelmap.c \
../include/ffmpeg/libavfilter/af_channelsplit.c \
../include/ffmpeg/libavfilter/af_compand.c \
../include/ffmpeg/libavfilter/af_earwax.c \
../include/ffmpeg/libavfilter/af_flanger.c \
../include/ffmpeg/libavfilter/af_join.c \
../include/ffmpeg/libavfilter/af_ladspa.c \
../include/ffmpeg/libavfilter/af_pan.c \
../include/ffmpeg/libavfilter/af_replaygain.c \
../include/ffmpeg/libavfilter/af_resample.c \
../include/ffmpeg/libavfilter/af_silencedetect.c \
../include/ffmpeg/libavfilter/af_volume.c \
../include/ffmpeg/libavfilter/af_volumedetect.c \
../include/ffmpeg/libavfilter/allfilters.c \
../include/ffmpeg/libavfilter/asink_anullsink.c \
../include/ffmpeg/libavfilter/asrc_anullsrc.c \
../include/ffmpeg/libavfilter/asrc_flite.c \
../include/ffmpeg/libavfilter/asrc_sine.c \
../include/ffmpeg/libavfilter/audio.c \
../include/ffmpeg/libavfilter/avcodec.c \
../include/ffmpeg/libavfilter/avf_avectorscope.c \
../include/ffmpeg/libavfilter/avf_concat.c \
../include/ffmpeg/libavfilter/avf_showcqt.c \
../include/ffmpeg/libavfilter/avf_showspectrum.c \
../include/ffmpeg/libavfilter/avf_showwaves.c \
../include/ffmpeg/libavfilter/avfilter.c \
../include/ffmpeg/libavfilter/avfiltergraph.c \
../include/ffmpeg/libavfilter/bbox.c \
../include/ffmpeg/libavfilter/buffer.c \
../include/ffmpeg/libavfilter/buffersink.c \
../include/ffmpeg/libavfilter/buffersrc.c \
../include/ffmpeg/libavfilter/deshake_opencl.c \
../include/ffmpeg/libavfilter/drawutils.c \
../include/ffmpeg/libavfilter/dualinput.c \
../include/ffmpeg/libavfilter/f_ebur128.c \
../include/ffmpeg/libavfilter/f_interleave.c \
../include/ffmpeg/libavfilter/f_perms.c \
../include/ffmpeg/libavfilter/f_select.c \
../include/ffmpeg/libavfilter/f_sendcmd.c \
../include/ffmpeg/libavfilter/f_zmq.c \
../include/ffmpeg/libavfilter/fifo.c \
../include/ffmpeg/libavfilter/filtfmts.c \
../include/ffmpeg/libavfilter/formats.c \
../include/ffmpeg/libavfilter/framesync.c \
../include/ffmpeg/libavfilter/generate_wave_table.c \
../include/ffmpeg/libavfilter/graphdump.c \
../include/ffmpeg/libavfilter/graphparser.c \
../include/ffmpeg/libavfilter/lavfutils.c \
../include/ffmpeg/libavfilter/lswsutils.c \
../include/ffmpeg/libavfilter/opencl_allkernels.c \
../include/ffmpeg/libavfilter/pthread.c \
../include/ffmpeg/libavfilter/setpts.c \
../include/ffmpeg/libavfilter/settb.c \
../include/ffmpeg/libavfilter/split.c \
../include/ffmpeg/libavfilter/src_movie.c \
../include/ffmpeg/libavfilter/transform.c \
../include/ffmpeg/libavfilter/trim.c \
../include/ffmpeg/libavfilter/unsharp_opencl.c \
../include/ffmpeg/libavfilter/vf_alphamerge.c \
../include/ffmpeg/libavfilter/vf_aspect.c \
../include/ffmpeg/libavfilter/vf_bbox.c \
../include/ffmpeg/libavfilter/vf_blackdetect.c \
../include/ffmpeg/libavfilter/vf_blackframe.c \
../include/ffmpeg/libavfilter/vf_blend.c \
../include/ffmpeg/libavfilter/vf_boxblur.c \
../include/ffmpeg/libavfilter/vf_colorbalance.c \
../include/ffmpeg/libavfilter/vf_colorchannelmixer.c \
../include/ffmpeg/libavfilter/vf_colormatrix.c \
../include/ffmpeg/libavfilter/vf_copy.c \
../include/ffmpeg/libavfilter/vf_crop.c \
../include/ffmpeg/libavfilter/vf_cropdetect.c \
../include/ffmpeg/libavfilter/vf_curves.c \
../include/ffmpeg/libavfilter/vf_dctdnoiz.c \
../include/ffmpeg/libavfilter/vf_decimate.c \
../include/ffmpeg/libavfilter/vf_dejudder.c \
../include/ffmpeg/libavfilter/vf_delogo.c \
../include/ffmpeg/libavfilter/vf_deshake.c \
../include/ffmpeg/libavfilter/vf_drawbox.c \
../include/ffmpeg/libavfilter/vf_drawtext.c \
../include/ffmpeg/libavfilter/vf_edgedetect.c \
../include/ffmpeg/libavfilter/vf_elbg.c \
../include/ffmpeg/libavfilter/vf_extractplanes.c \
../include/ffmpeg/libavfilter/vf_fade.c \
../include/ffmpeg/libavfilter/vf_field.c \
../include/ffmpeg/libavfilter/vf_fieldmatch.c \
../include/ffmpeg/libavfilter/vf_fieldorder.c \
../include/ffmpeg/libavfilter/vf_format.c \
../include/ffmpeg/libavfilter/vf_fps.c \
../include/ffmpeg/libavfilter/vf_framepack.c \
../include/ffmpeg/libavfilter/vf_framestep.c \
../include/ffmpeg/libavfilter/vf_frei0r.c \
../include/ffmpeg/libavfilter/vf_geq.c \
../include/ffmpeg/libavfilter/vf_gradfun.c \
../include/ffmpeg/libavfilter/vf_hflip.c \
../include/ffmpeg/libavfilter/vf_histeq.c \
../include/ffmpeg/libavfilter/vf_histogram.c \
../include/ffmpeg/libavfilter/vf_hqdn3d.c \
../include/ffmpeg/libavfilter/vf_hqx.c \
../include/ffmpeg/libavfilter/vf_hue.c \
../include/ffmpeg/libavfilter/vf_idet.c \
../include/ffmpeg/libavfilter/vf_il.c \
../include/ffmpeg/libavfilter/vf_interlace.c \
../include/ffmpeg/libavfilter/vf_kerndeint.c \
../include/ffmpeg/libavfilter/vf_libopencv.c \
../include/ffmpeg/libavfilter/vf_lut.c \
../include/ffmpeg/libavfilter/vf_lut3d.c \
../include/ffmpeg/libavfilter/vf_mcdeint.c \
../include/ffmpeg/libavfilter/vf_mergeplanes.c \
../include/ffmpeg/libavfilter/vf_mp.c \
../include/ffmpeg/libavfilter/vf_mpdecimate.c \
../include/ffmpeg/libavfilter/vf_noise.c \
../include/ffmpeg/libavfilter/vf_null.c \
../include/ffmpeg/libavfilter/vf_overlay.c \
../include/ffmpeg/libavfilter/vf_owdenoise.c \
../include/ffmpeg/libavfilter/vf_pad.c \
../include/ffmpeg/libavfilter/vf_perspective.c \
../include/ffmpeg/libavfilter/vf_phase.c \
../include/ffmpeg/libavfilter/vf_pixdesctest.c \
../include/ffmpeg/libavfilter/vf_pp.c \
../include/ffmpeg/libavfilter/vf_psnr.c \
../include/ffmpeg/libavfilter/vf_pullup.c \
../include/ffmpeg/libavfilter/vf_removelogo.c \
../include/ffmpeg/libavfilter/vf_rotate.c \
../include/ffmpeg/libavfilter/vf_sab.c \
../include/ffmpeg/libavfilter/vf_scale.c \
../include/ffmpeg/libavfilter/vf_separatefields.c \
../include/ffmpeg/libavfilter/vf_setfield.c \
../include/ffmpeg/libavfilter/vf_showinfo.c \
../include/ffmpeg/libavfilter/vf_shuffleplanes.c \
../include/ffmpeg/libavfilter/vf_signalstats.c \
../include/ffmpeg/libavfilter/vf_smartblur.c \
../include/ffmpeg/libavfilter/vf_spp.c \
../include/ffmpeg/libavfilter/vf_stereo3d.c \
../include/ffmpeg/libavfilter/vf_subtitles.c \
../include/ffmpeg/libavfilter/vf_super2xsai.c \
../include/ffmpeg/libavfilter/vf_swapuv.c \
../include/ffmpeg/libavfilter/vf_telecine.c \
../include/ffmpeg/libavfilter/vf_thumbnail.c \
../include/ffmpeg/libavfilter/vf_tile.c \
../include/ffmpeg/libavfilter/vf_tinterlace.c \
../include/ffmpeg/libavfilter/vf_transpose.c \
../include/ffmpeg/libavfilter/vf_unsharp.c \
../include/ffmpeg/libavfilter/vf_vflip.c \
../include/ffmpeg/libavfilter/vf_vidstabdetect.c \
../include/ffmpeg/libavfilter/vf_vidstabtransform.c \
../include/ffmpeg/libavfilter/vf_vignette.c \
../include/ffmpeg/libavfilter/vf_w3fdif.c \
../include/ffmpeg/libavfilter/vf_yadif.c \
../include/ffmpeg/libavfilter/vf_zoompan.c \
../include/ffmpeg/libavfilter/video.c \
../include/ffmpeg/libavfilter/vidstabutils.c \
../include/ffmpeg/libavfilter/vsink_nullsink.c \
../include/ffmpeg/libavfilter/vsrc_cellauto.c \
../include/ffmpeg/libavfilter/vsrc_life.c \
../include/ffmpeg/libavfilter/vsrc_mandelbrot.c \
../include/ffmpeg/libavfilter/vsrc_mptestsrc.c \
../include/ffmpeg/libavfilter/vsrc_testsrc.c 

OBJS += \
./include/ffmpeg/libavfilter/aeval.o \
./include/ffmpeg/libavfilter/af_aconvert.o \
./include/ffmpeg/libavfilter/af_adelay.o \
./include/ffmpeg/libavfilter/af_aecho.o \
./include/ffmpeg/libavfilter/af_afade.o \
./include/ffmpeg/libavfilter/af_aformat.o \
./include/ffmpeg/libavfilter/af_amerge.o \
./include/ffmpeg/libavfilter/af_amix.o \
./include/ffmpeg/libavfilter/af_anull.o \
./include/ffmpeg/libavfilter/af_apad.o \
./include/ffmpeg/libavfilter/af_aphaser.o \
./include/ffmpeg/libavfilter/af_aresample.o \
./include/ffmpeg/libavfilter/af_asetnsamples.o \
./include/ffmpeg/libavfilter/af_asetrate.o \
./include/ffmpeg/libavfilter/af_ashowinfo.o \
./include/ffmpeg/libavfilter/af_astats.o \
./include/ffmpeg/libavfilter/af_astreamsync.o \
./include/ffmpeg/libavfilter/af_asyncts.o \
./include/ffmpeg/libavfilter/af_atempo.o \
./include/ffmpeg/libavfilter/af_biquads.o \
./include/ffmpeg/libavfilter/af_bs2b.o \
./include/ffmpeg/libavfilter/af_channelmap.o \
./include/ffmpeg/libavfilter/af_channelsplit.o \
./include/ffmpeg/libavfilter/af_compand.o \
./include/ffmpeg/libavfilter/af_earwax.o \
./include/ffmpeg/libavfilter/af_flanger.o \
./include/ffmpeg/libavfilter/af_join.o \
./include/ffmpeg/libavfilter/af_ladspa.o \
./include/ffmpeg/libavfilter/af_pan.o \
./include/ffmpeg/libavfilter/af_replaygain.o \
./include/ffmpeg/libavfilter/af_resample.o \
./include/ffmpeg/libavfilter/af_silencedetect.o \
./include/ffmpeg/libavfilter/af_volume.o \
./include/ffmpeg/libavfilter/af_volumedetect.o \
./include/ffmpeg/libavfilter/allfilters.o \
./include/ffmpeg/libavfilter/asink_anullsink.o \
./include/ffmpeg/libavfilter/asrc_anullsrc.o \
./include/ffmpeg/libavfilter/asrc_flite.o \
./include/ffmpeg/libavfilter/asrc_sine.o \
./include/ffmpeg/libavfilter/audio.o \
./include/ffmpeg/libavfilter/avcodec.o \
./include/ffmpeg/libavfilter/avf_avectorscope.o \
./include/ffmpeg/libavfilter/avf_concat.o \
./include/ffmpeg/libavfilter/avf_showcqt.o \
./include/ffmpeg/libavfilter/avf_showspectrum.o \
./include/ffmpeg/libavfilter/avf_showwaves.o \
./include/ffmpeg/libavfilter/avfilter.o \
./include/ffmpeg/libavfilter/avfiltergraph.o \
./include/ffmpeg/libavfilter/bbox.o \
./include/ffmpeg/libavfilter/buffer.o \
./include/ffmpeg/libavfilter/buffersink.o \
./include/ffmpeg/libavfilter/buffersrc.o \
./include/ffmpeg/libavfilter/deshake_opencl.o \
./include/ffmpeg/libavfilter/drawutils.o \
./include/ffmpeg/libavfilter/dualinput.o \
./include/ffmpeg/libavfilter/f_ebur128.o \
./include/ffmpeg/libavfilter/f_interleave.o \
./include/ffmpeg/libavfilter/f_perms.o \
./include/ffmpeg/libavfilter/f_select.o \
./include/ffmpeg/libavfilter/f_sendcmd.o \
./include/ffmpeg/libavfilter/f_zmq.o \
./include/ffmpeg/libavfilter/fifo.o \
./include/ffmpeg/libavfilter/filtfmts.o \
./include/ffmpeg/libavfilter/formats.o \
./include/ffmpeg/libavfilter/framesync.o \
./include/ffmpeg/libavfilter/generate_wave_table.o \
./include/ffmpeg/libavfilter/graphdump.o \
./include/ffmpeg/libavfilter/graphparser.o \
./include/ffmpeg/libavfilter/lavfutils.o \
./include/ffmpeg/libavfilter/lswsutils.o \
./include/ffmpeg/libavfilter/opencl_allkernels.o \
./include/ffmpeg/libavfilter/pthread.o \
./include/ffmpeg/libavfilter/setpts.o \
./include/ffmpeg/libavfilter/settb.o \
./include/ffmpeg/libavfilter/split.o \
./include/ffmpeg/libavfilter/src_movie.o \
./include/ffmpeg/libavfilter/transform.o \
./include/ffmpeg/libavfilter/trim.o \
./include/ffmpeg/libavfilter/unsharp_opencl.o \
./include/ffmpeg/libavfilter/vf_alphamerge.o \
./include/ffmpeg/libavfilter/vf_aspect.o \
./include/ffmpeg/libavfilter/vf_bbox.o \
./include/ffmpeg/libavfilter/vf_blackdetect.o \
./include/ffmpeg/libavfilter/vf_blackframe.o \
./include/ffmpeg/libavfilter/vf_blend.o \
./include/ffmpeg/libavfilter/vf_boxblur.o \
./include/ffmpeg/libavfilter/vf_colorbalance.o \
./include/ffmpeg/libavfilter/vf_colorchannelmixer.o \
./include/ffmpeg/libavfilter/vf_colormatrix.o \
./include/ffmpeg/libavfilter/vf_copy.o \
./include/ffmpeg/libavfilter/vf_crop.o \
./include/ffmpeg/libavfilter/vf_cropdetect.o \
./include/ffmpeg/libavfilter/vf_curves.o \
./include/ffmpeg/libavfilter/vf_dctdnoiz.o \
./include/ffmpeg/libavfilter/vf_decimate.o \
./include/ffmpeg/libavfilter/vf_dejudder.o \
./include/ffmpeg/libavfilter/vf_delogo.o \
./include/ffmpeg/libavfilter/vf_deshake.o \
./include/ffmpeg/libavfilter/vf_drawbox.o \
./include/ffmpeg/libavfilter/vf_drawtext.o \
./include/ffmpeg/libavfilter/vf_edgedetect.o \
./include/ffmpeg/libavfilter/vf_elbg.o \
./include/ffmpeg/libavfilter/vf_extractplanes.o \
./include/ffmpeg/libavfilter/vf_fade.o \
./include/ffmpeg/libavfilter/vf_field.o \
./include/ffmpeg/libavfilter/vf_fieldmatch.o \
./include/ffmpeg/libavfilter/vf_fieldorder.o \
./include/ffmpeg/libavfilter/vf_format.o \
./include/ffmpeg/libavfilter/vf_fps.o \
./include/ffmpeg/libavfilter/vf_framepack.o \
./include/ffmpeg/libavfilter/vf_framestep.o \
./include/ffmpeg/libavfilter/vf_frei0r.o \
./include/ffmpeg/libavfilter/vf_geq.o \
./include/ffmpeg/libavfilter/vf_gradfun.o \
./include/ffmpeg/libavfilter/vf_hflip.o \
./include/ffmpeg/libavfilter/vf_histeq.o \
./include/ffmpeg/libavfilter/vf_histogram.o \
./include/ffmpeg/libavfilter/vf_hqdn3d.o \
./include/ffmpeg/libavfilter/vf_hqx.o \
./include/ffmpeg/libavfilter/vf_hue.o \
./include/ffmpeg/libavfilter/vf_idet.o \
./include/ffmpeg/libavfilter/vf_il.o \
./include/ffmpeg/libavfilter/vf_interlace.o \
./include/ffmpeg/libavfilter/vf_kerndeint.o \
./include/ffmpeg/libavfilter/vf_libopencv.o \
./include/ffmpeg/libavfilter/vf_lut.o \
./include/ffmpeg/libavfilter/vf_lut3d.o \
./include/ffmpeg/libavfilter/vf_mcdeint.o \
./include/ffmpeg/libavfilter/vf_mergeplanes.o \
./include/ffmpeg/libavfilter/vf_mp.o \
./include/ffmpeg/libavfilter/vf_mpdecimate.o \
./include/ffmpeg/libavfilter/vf_noise.o \
./include/ffmpeg/libavfilter/vf_null.o \
./include/ffmpeg/libavfilter/vf_overlay.o \
./include/ffmpeg/libavfilter/vf_owdenoise.o \
./include/ffmpeg/libavfilter/vf_pad.o \
./include/ffmpeg/libavfilter/vf_perspective.o \
./include/ffmpeg/libavfilter/vf_phase.o \
./include/ffmpeg/libavfilter/vf_pixdesctest.o \
./include/ffmpeg/libavfilter/vf_pp.o \
./include/ffmpeg/libavfilter/vf_psnr.o \
./include/ffmpeg/libavfilter/vf_pullup.o \
./include/ffmpeg/libavfilter/vf_removelogo.o \
./include/ffmpeg/libavfilter/vf_rotate.o \
./include/ffmpeg/libavfilter/vf_sab.o \
./include/ffmpeg/libavfilter/vf_scale.o \
./include/ffmpeg/libavfilter/vf_separatefields.o \
./include/ffmpeg/libavfilter/vf_setfield.o \
./include/ffmpeg/libavfilter/vf_showinfo.o \
./include/ffmpeg/libavfilter/vf_shuffleplanes.o \
./include/ffmpeg/libavfilter/vf_signalstats.o \
./include/ffmpeg/libavfilter/vf_smartblur.o \
./include/ffmpeg/libavfilter/vf_spp.o \
./include/ffmpeg/libavfilter/vf_stereo3d.o \
./include/ffmpeg/libavfilter/vf_subtitles.o \
./include/ffmpeg/libavfilter/vf_super2xsai.o \
./include/ffmpeg/libavfilter/vf_swapuv.o \
./include/ffmpeg/libavfilter/vf_telecine.o \
./include/ffmpeg/libavfilter/vf_thumbnail.o \
./include/ffmpeg/libavfilter/vf_tile.o \
./include/ffmpeg/libavfilter/vf_tinterlace.o \
./include/ffmpeg/libavfilter/vf_transpose.o \
./include/ffmpeg/libavfilter/vf_unsharp.o \
./include/ffmpeg/libavfilter/vf_vflip.o \
./include/ffmpeg/libavfilter/vf_vidstabdetect.o \
./include/ffmpeg/libavfilter/vf_vidstabtransform.o \
./include/ffmpeg/libavfilter/vf_vignette.o \
./include/ffmpeg/libavfilter/vf_w3fdif.o \
./include/ffmpeg/libavfilter/vf_yadif.o \
./include/ffmpeg/libavfilter/vf_zoompan.o \
./include/ffmpeg/libavfilter/video.o \
./include/ffmpeg/libavfilter/vidstabutils.o \
./include/ffmpeg/libavfilter/vsink_nullsink.o \
./include/ffmpeg/libavfilter/vsrc_cellauto.o \
./include/ffmpeg/libavfilter/vsrc_life.o \
./include/ffmpeg/libavfilter/vsrc_mandelbrot.o \
./include/ffmpeg/libavfilter/vsrc_mptestsrc.o \
./include/ffmpeg/libavfilter/vsrc_testsrc.o 

C_DEPS += \
./include/ffmpeg/libavfilter/aeval.d \
./include/ffmpeg/libavfilter/af_aconvert.d \
./include/ffmpeg/libavfilter/af_adelay.d \
./include/ffmpeg/libavfilter/af_aecho.d \
./include/ffmpeg/libavfilter/af_afade.d \
./include/ffmpeg/libavfilter/af_aformat.d \
./include/ffmpeg/libavfilter/af_amerge.d \
./include/ffmpeg/libavfilter/af_amix.d \
./include/ffmpeg/libavfilter/af_anull.d \
./include/ffmpeg/libavfilter/af_apad.d \
./include/ffmpeg/libavfilter/af_aphaser.d \
./include/ffmpeg/libavfilter/af_aresample.d \
./include/ffmpeg/libavfilter/af_asetnsamples.d \
./include/ffmpeg/libavfilter/af_asetrate.d \
./include/ffmpeg/libavfilter/af_ashowinfo.d \
./include/ffmpeg/libavfilter/af_astats.d \
./include/ffmpeg/libavfilter/af_astreamsync.d \
./include/ffmpeg/libavfilter/af_asyncts.d \
./include/ffmpeg/libavfilter/af_atempo.d \
./include/ffmpeg/libavfilter/af_biquads.d \
./include/ffmpeg/libavfilter/af_bs2b.d \
./include/ffmpeg/libavfilter/af_channelmap.d \
./include/ffmpeg/libavfilter/af_channelsplit.d \
./include/ffmpeg/libavfilter/af_compand.d \
./include/ffmpeg/libavfilter/af_earwax.d \
./include/ffmpeg/libavfilter/af_flanger.d \
./include/ffmpeg/libavfilter/af_join.d \
./include/ffmpeg/libavfilter/af_ladspa.d \
./include/ffmpeg/libavfilter/af_pan.d \
./include/ffmpeg/libavfilter/af_replaygain.d \
./include/ffmpeg/libavfilter/af_resample.d \
./include/ffmpeg/libavfilter/af_silencedetect.d \
./include/ffmpeg/libavfilter/af_volume.d \
./include/ffmpeg/libavfilter/af_volumedetect.d \
./include/ffmpeg/libavfilter/allfilters.d \
./include/ffmpeg/libavfilter/asink_anullsink.d \
./include/ffmpeg/libavfilter/asrc_anullsrc.d \
./include/ffmpeg/libavfilter/asrc_flite.d \
./include/ffmpeg/libavfilter/asrc_sine.d \
./include/ffmpeg/libavfilter/audio.d \
./include/ffmpeg/libavfilter/avcodec.d \
./include/ffmpeg/libavfilter/avf_avectorscope.d \
./include/ffmpeg/libavfilter/avf_concat.d \
./include/ffmpeg/libavfilter/avf_showcqt.d \
./include/ffmpeg/libavfilter/avf_showspectrum.d \
./include/ffmpeg/libavfilter/avf_showwaves.d \
./include/ffmpeg/libavfilter/avfilter.d \
./include/ffmpeg/libavfilter/avfiltergraph.d \
./include/ffmpeg/libavfilter/bbox.d \
./include/ffmpeg/libavfilter/buffer.d \
./include/ffmpeg/libavfilter/buffersink.d \
./include/ffmpeg/libavfilter/buffersrc.d \
./include/ffmpeg/libavfilter/deshake_opencl.d \
./include/ffmpeg/libavfilter/drawutils.d \
./include/ffmpeg/libavfilter/dualinput.d \
./include/ffmpeg/libavfilter/f_ebur128.d \
./include/ffmpeg/libavfilter/f_interleave.d \
./include/ffmpeg/libavfilter/f_perms.d \
./include/ffmpeg/libavfilter/f_select.d \
./include/ffmpeg/libavfilter/f_sendcmd.d \
./include/ffmpeg/libavfilter/f_zmq.d \
./include/ffmpeg/libavfilter/fifo.d \
./include/ffmpeg/libavfilter/filtfmts.d \
./include/ffmpeg/libavfilter/formats.d \
./include/ffmpeg/libavfilter/framesync.d \
./include/ffmpeg/libavfilter/generate_wave_table.d \
./include/ffmpeg/libavfilter/graphdump.d \
./include/ffmpeg/libavfilter/graphparser.d \
./include/ffmpeg/libavfilter/lavfutils.d \
./include/ffmpeg/libavfilter/lswsutils.d \
./include/ffmpeg/libavfilter/opencl_allkernels.d \
./include/ffmpeg/libavfilter/pthread.d \
./include/ffmpeg/libavfilter/setpts.d \
./include/ffmpeg/libavfilter/settb.d \
./include/ffmpeg/libavfilter/split.d \
./include/ffmpeg/libavfilter/src_movie.d \
./include/ffmpeg/libavfilter/transform.d \
./include/ffmpeg/libavfilter/trim.d \
./include/ffmpeg/libavfilter/unsharp_opencl.d \
./include/ffmpeg/libavfilter/vf_alphamerge.d \
./include/ffmpeg/libavfilter/vf_aspect.d \
./include/ffmpeg/libavfilter/vf_bbox.d \
./include/ffmpeg/libavfilter/vf_blackdetect.d \
./include/ffmpeg/libavfilter/vf_blackframe.d \
./include/ffmpeg/libavfilter/vf_blend.d \
./include/ffmpeg/libavfilter/vf_boxblur.d \
./include/ffmpeg/libavfilter/vf_colorbalance.d \
./include/ffmpeg/libavfilter/vf_colorchannelmixer.d \
./include/ffmpeg/libavfilter/vf_colormatrix.d \
./include/ffmpeg/libavfilter/vf_copy.d \
./include/ffmpeg/libavfilter/vf_crop.d \
./include/ffmpeg/libavfilter/vf_cropdetect.d \
./include/ffmpeg/libavfilter/vf_curves.d \
./include/ffmpeg/libavfilter/vf_dctdnoiz.d \
./include/ffmpeg/libavfilter/vf_decimate.d \
./include/ffmpeg/libavfilter/vf_dejudder.d \
./include/ffmpeg/libavfilter/vf_delogo.d \
./include/ffmpeg/libavfilter/vf_deshake.d \
./include/ffmpeg/libavfilter/vf_drawbox.d \
./include/ffmpeg/libavfilter/vf_drawtext.d \
./include/ffmpeg/libavfilter/vf_edgedetect.d \
./include/ffmpeg/libavfilter/vf_elbg.d \
./include/ffmpeg/libavfilter/vf_extractplanes.d \
./include/ffmpeg/libavfilter/vf_fade.d \
./include/ffmpeg/libavfilter/vf_field.d \
./include/ffmpeg/libavfilter/vf_fieldmatch.d \
./include/ffmpeg/libavfilter/vf_fieldorder.d \
./include/ffmpeg/libavfilter/vf_format.d \
./include/ffmpeg/libavfilter/vf_fps.d \
./include/ffmpeg/libavfilter/vf_framepack.d \
./include/ffmpeg/libavfilter/vf_framestep.d \
./include/ffmpeg/libavfilter/vf_frei0r.d \
./include/ffmpeg/libavfilter/vf_geq.d \
./include/ffmpeg/libavfilter/vf_gradfun.d \
./include/ffmpeg/libavfilter/vf_hflip.d \
./include/ffmpeg/libavfilter/vf_histeq.d \
./include/ffmpeg/libavfilter/vf_histogram.d \
./include/ffmpeg/libavfilter/vf_hqdn3d.d \
./include/ffmpeg/libavfilter/vf_hqx.d \
./include/ffmpeg/libavfilter/vf_hue.d \
./include/ffmpeg/libavfilter/vf_idet.d \
./include/ffmpeg/libavfilter/vf_il.d \
./include/ffmpeg/libavfilter/vf_interlace.d \
./include/ffmpeg/libavfilter/vf_kerndeint.d \
./include/ffmpeg/libavfilter/vf_libopencv.d \
./include/ffmpeg/libavfilter/vf_lut.d \
./include/ffmpeg/libavfilter/vf_lut3d.d \
./include/ffmpeg/libavfilter/vf_mcdeint.d \
./include/ffmpeg/libavfilter/vf_mergeplanes.d \
./include/ffmpeg/libavfilter/vf_mp.d \
./include/ffmpeg/libavfilter/vf_mpdecimate.d \
./include/ffmpeg/libavfilter/vf_noise.d \
./include/ffmpeg/libavfilter/vf_null.d \
./include/ffmpeg/libavfilter/vf_overlay.d \
./include/ffmpeg/libavfilter/vf_owdenoise.d \
./include/ffmpeg/libavfilter/vf_pad.d \
./include/ffmpeg/libavfilter/vf_perspective.d \
./include/ffmpeg/libavfilter/vf_phase.d \
./include/ffmpeg/libavfilter/vf_pixdesctest.d \
./include/ffmpeg/libavfilter/vf_pp.d \
./include/ffmpeg/libavfilter/vf_psnr.d \
./include/ffmpeg/libavfilter/vf_pullup.d \
./include/ffmpeg/libavfilter/vf_removelogo.d \
./include/ffmpeg/libavfilter/vf_rotate.d \
./include/ffmpeg/libavfilter/vf_sab.d \
./include/ffmpeg/libavfilter/vf_scale.d \
./include/ffmpeg/libavfilter/vf_separatefields.d \
./include/ffmpeg/libavfilter/vf_setfield.d \
./include/ffmpeg/libavfilter/vf_showinfo.d \
./include/ffmpeg/libavfilter/vf_shuffleplanes.d \
./include/ffmpeg/libavfilter/vf_signalstats.d \
./include/ffmpeg/libavfilter/vf_smartblur.d \
./include/ffmpeg/libavfilter/vf_spp.d \
./include/ffmpeg/libavfilter/vf_stereo3d.d \
./include/ffmpeg/libavfilter/vf_subtitles.d \
./include/ffmpeg/libavfilter/vf_super2xsai.d \
./include/ffmpeg/libavfilter/vf_swapuv.d \
./include/ffmpeg/libavfilter/vf_telecine.d \
./include/ffmpeg/libavfilter/vf_thumbnail.d \
./include/ffmpeg/libavfilter/vf_tile.d \
./include/ffmpeg/libavfilter/vf_tinterlace.d \
./include/ffmpeg/libavfilter/vf_transpose.d \
./include/ffmpeg/libavfilter/vf_unsharp.d \
./include/ffmpeg/libavfilter/vf_vflip.d \
./include/ffmpeg/libavfilter/vf_vidstabdetect.d \
./include/ffmpeg/libavfilter/vf_vidstabtransform.d \
./include/ffmpeg/libavfilter/vf_vignette.d \
./include/ffmpeg/libavfilter/vf_w3fdif.d \
./include/ffmpeg/libavfilter/vf_yadif.d \
./include/ffmpeg/libavfilter/vf_zoompan.d \
./include/ffmpeg/libavfilter/video.d \
./include/ffmpeg/libavfilter/vidstabutils.d \
./include/ffmpeg/libavfilter/vsink_nullsink.d \
./include/ffmpeg/libavfilter/vsrc_cellauto.d \
./include/ffmpeg/libavfilter/vsrc_life.d \
./include/ffmpeg/libavfilter/vsrc_mandelbrot.d \
./include/ffmpeg/libavfilter/vsrc_mptestsrc.d \
./include/ffmpeg/libavfilter/vsrc_testsrc.d 


# Each subdirectory must supply rules for building sources it contributes
include/ffmpeg/libavfilter/%.o: ../include/ffmpeg/libavfilter/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Compiler'
	gcc -I./include -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


