/* soapvideooverlayProxy.h
   Generated by gSOAP 2.8.17r from videooverlayws.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapvideooverlayProxy_H
#define soapvideooverlayProxy_H
#include "soapH.h"

class SOAP_CMAC videooverlayProxy : public soap
{ public:
	/// Endpoint URL of service 'videooverlayProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	videooverlayProxy();
	/// Construct from another engine state
	videooverlayProxy(const struct soap&);
	/// Constructor with endpoint URL
	videooverlayProxy(const char *url);
	/// Constructor with engine input+output mode control
	videooverlayProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	videooverlayProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	videooverlayProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~videooverlayProxy();
	/// Initializer used by constructors
	virtual	void videooverlayProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'addsource' (returns error code or SOAP_OK)
	virtual	int addsource(char *sourceurl, char *sourcename, struct voverlay_add_source_result *result) { return this->addsource(NULL, NULL, sourceurl, sourcename, result); }
	virtual	int addsource(const char *endpoint, const char *soap_action, char *sourceurl, char *sourcename, struct voverlay_add_source_result *result);

	/// Web service operation 'delsource' (returns error code or SOAP_OK)
	virtual	int delsource(char *sourceurl, struct soap_overlay_status *result) { return this->delsource(NULL, NULL, sourceurl, result); }
	virtual	int delsource(const char *endpoint, const char *soap_action, char *sourceurl, struct soap_overlay_status *result);

	/// Web service operation 'runsource' (returns error code or SOAP_OK)
	virtual	int runsource(int command, char *sourceurl, struct soap_overlay_status *result) { return this->runsource(NULL, NULL, command, sourceurl, result); }
	virtual	int runsource(const char *endpoint, const char *soap_action, int command, char *sourceurl, struct soap_overlay_status *result);

	/// Web service operation 'runserver' (returns error code or SOAP_OK)
	virtual	int runserver(int command, struct soap_overlay_status *result) { return this->runserver(NULL, NULL, command, result); }
	virtual	int runserver(const char *endpoint, const char *soap_action, int command, struct soap_overlay_status *result);

	/// Web service operation 'settextposition' (returns error code or SOAP_OK)
	virtual	int settextposition(int lanepos, int staffpos, int classpos, int licensenumberpos, int pricepos, int timestamppos, struct soap_overlay_status *result) { return this->settextposition(NULL, NULL, lanepos, staffpos, classpos, licensenumberpos, pricepos, timestamppos, result); }
	virtual	int settextposition(const char *endpoint, const char *soap_action, int lanepos, int staffpos, int classpos, int licensenumberpos, int pricepos, int timestamppos, struct soap_overlay_status *result);
};
#endif
